### ISSUE TITLE
Export to CSV attribute 'filter_dict_source_tlp' not found

### ISSUE THREAD

**Issue by bigman22** [crits/crits#1008]
When I export from Indicators, Domains, or IPs, The CSV exports but I always only get this output in the CSV.

"ERROR: 'unicode' object has no attribute 'filter_dict_source_tlp'. Sort performed on:"

I am not sure why I am getting this. This is a fresh, unmodified instance of CRITs.

Thank you in advance for your help.

-John

**Comment by mgoffin** [comment]
Looks like a legit bug. We will look into it!

**Comment by bigman22** [comment]
Thank you for the update! You guys are always on top of things!

**Comment by mgoffin** [comment]
Ok I think I just fixed it. Can you pull the latest master (I assume that's what you are using given the tlp stuff doesn't exist in stable) and let me know?

**Comment by bigman22** [comment]
Worked like a charm! And yes I am using master instead of the stable version (I like to live on the edge I guess lol).

Thanks Mike!

**Comment by mgoffin** [comment]
Glad it worked :) If you have any other issues, please let us know!
