### ISSUE TITLE
new installation fails on authentication

### ISSUE THREAD

**Issue by 0x3a** [crits/crits#1015]
I just setup a new install of CRITs and after setting up a user account the Web UI comes back with:

> Unknown user, bad password, or user does not have permission to log on using the web UI. 

Checking the logs I get back:

> ERROR 2018-09-14 18:26:04,498 crits.core.user No ROLES defined for user: ****

I can it based on the installation documentation and simply added a user, no reason why I shouldn't be able to log in. I can see the user in the DB and can also see it is an active user.

**Comment by mgoffin** [comment]
It is fairly confusing I apologize. The installation instructions are for the stable branch, not Master which is in the new Roles platform.

In short, you need to add the default UberAdmin role to that user and it should allow you to authenticate.

**Comment by 0x3a** [comment]
How would I do that from the commandline? I even tried setting up users again like this:

> ./manage.py users -a -u <nick> -f <fname> -l <lname> -e <email> --role uberabmin

But doesn't seem to set any roles, don't think there's documentation on the new role system yet as far as I can tell.

**Comment by mgoffin** [comment]
I think the role might be case sensitive.

**Comment by 0x3a** [comment]
Ahhh, yeah they are case sensitive works now. Thanks for the quick replies!

**Comment by mgoffin** [comment]
No problem! Sorry about the confusion!
