### ISSUE TITLE
unable to add any IOCs via the API

### ISSUE THREAD

**Issue by paulpc** [crits/crits#103]
using the standard pcap upload API code, but i get the following response: 

> import requests
> url = 'https://[server_ip]/crits/api/v1/pcaps/'
> files={'filedata':open('path to pcap','rb')}
> data = {'api_key': 'api_key','username':'username','source':'legitimate source'}
> r = requests.post(url, data=data, files=files, verify=False)
> r.text()
> u'{"error": "No data object passed in"}'

getting the same result with domains, and IPs. I am sure it's a stupid error i am making, but not sure which one.

**Comment by TejaRamachandran** [comment]
Hi Guys,

I am facing same issue my requirement is to GET IP's in CRITs server using API call. Here the code i used to get IP's 

```
import requests
import json
url = 'http://127.0.0.1:8080/api/v1/samples/'
data = {'api_key': 'xxxxxxxxxxxx','username': 'abcd', 'source': u'ZeusTracker'}
r = requests.get(url, data=data , verify=False)
print r.content
print r
````

My response is also ````,<RESPONSE[500]>

Please correct me if anything wrong in the code.

Thanks.

**Comment by frbapolkosnik** [comment]
3 quick questions:
1. Did you run "git pull" and then restarted the web server?
2. Is "ZeusTracker" already in your Sources?
3. Can you check the apache error log for the error?
