### ISSUE TITLE
Error when adding new user or adding default admin user

### ISSUE THREAD

**Issue by GrantBirki** [crits/crits#1052]
When I go to install a new user or even add the first admin user I am getting an error and the program breaks. Below is the code and output. 

sudo python manage.py users -h
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 206, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/crits/crits/core/management/commands/users.py", line 9, in <module>
    import settings
  File "/home/crits/crits/settings.py", line 200, in <module>
    replicaset=MONGO_REPLICASET)
  File "/usr/local/lib/python2.7/dist-packages/mongoengine/connection.py", line 363, in connect
    'A different connection with alias `%s` was already registered. Use disconnect() first' % alias)
mongoengine.connection.MongoEngineConnectionError: A different connection with alias `default` was already registered. Use disconnect() first

**Comment by apolkosnik** [comment]
It looks like an error caused by the latest version of Mongoengine.

**Comment by GrantBirki** [comment]
@apolkosnik Thanks for the quick response! I am fairly new to using Mongo and crits. Do you know if this is fixable or a better way to go about this?

**Comment by GrantBirki** [comment]
@apolkosnik 
The only thing I have done of this test system are the following commands:
apt-get update/upgrade
install a vnc client
download the git repo for crits and run the "bootstrap" set up

**Comment by apolkosnik** [comment]
Force downgrade of mongo engine to what you have in requirements.txt

**Comment by GrantBirki** [comment]
Awesome thank you so much! I'm going to look up how to do that and let you know of the outcome. Thank you!

**Comment by GrantBirki** [comment]
@apolkosnik Thank you so much for the help again. I just started up a new instance on AWS and only installed the CRITs repo and ran the start up script and still could not add a user (same error). This is as far as I have gotten so far. Will adding this new user allow me to log into the CRITs UI? I'm looking for guidance on how to roll down Mongo to an earlier version (not quite sure how). I ran the requirements.txt with the default script and when adding a user it keeps failing with the same issues as above.

**Comment by GrantBirki** [comment]
I solved my problem with the help of @apolkosnik. The issue was mongoengine. After rolling back to mongoengine 0.8.7 I was able to successfully install CRITs and all install processes worked correctly.

**Comment by huddaannaa** [comment]
I have the same error now, I will give this a try

**Comment by apolkosnik** [comment]
Try this instead
pip install -U "git+https://github.com/apolkosnik/mongoengine.git@v0.8.10"

you might need to run it via sudo (or not if you are using virtualenv)
