### ISSUE TITLE
How to add samples?

### ISSUE THREAD

**Issue by GrantBirki** [crits/crits#1053]
I have installed and added the source "VirusTotal" to CRITs. I am a first time user and a little confused reading the documentation on how to set up sources. Here is my currently outlook on how I think and would like the work flow to go:
1. Add virustotal as a sample for all sorts of files
2. Upload a suspected file that could contain malware to CRITS
3. VirusTotal then compares an MD5 of the file to its own MD5 of known bad signatures
4. CRITs generates a report

From reading the documentation I am very unsure how to effectively go about this. Any and all guidance would be greatly appreciated.

**Comment by apolkosnik** [comment]
Add the VirusTotal source to your user first.

**Comment by GrantBirki** [comment]
@apolkosnik I added VirusTotal to my user but I'm not exactly sure what that does. Does it make an API call and actually allow CRITs to use the VirusTotal service?

**Comment by apolkosnik** [comment]
You need to have your user profile associated with the source in order to be able to use it

**Comment by GrantBirki** [comment]
The comment above says it all. By adding a "source" to the user I was able to allow virus total to run on all uploaded samples. Problem solved!
