### ISSUE TITLE
Will CRITS be updated to python 3.x support as 2.7 is being deprecated

### ISSUE THREAD

**Issue by Sealteam56** [crits/crits#1060]
How is the deprecation of python 2.7 impacting CRITS requirements for this variant of python? Will CRITS still function with Python 3.x

**Comment by mgoffin** [comment]
The deprecation of 2.7 doesn't mean everything written for 2.7 will cease to function come January. There has been efforts from folks to bring CRITs to 3.x (see #714) but nothing official. I anticipate the workload required to make CRITs work with 3.x is more than anyone currently has time for as everyone who is currently active with the project is volunteer only during their personal time.

We've also realized that the way CRITs is designed has become extremely old, lacks the usefulness of newer technology, and deserves a complete rewrite. Some effort has been made in that arena to attempt to design a more flexible, modular, and non-constraining set of projects with that in mind. The progress, however, has been extremely slow given everyone's situation.

We are more than happy to review PRs which push CRITs in that direction, but efforts going forward will most likely be on a replacement project people can deploy over their existing dataset (for the most part).

**Comment by Sealteam56** [comment]
Thank You
