### ISSUE TITLE
Results of analyses

### ISSUE THREAD

**Issue by ratcates** [crits/crits#1062]
Is it possible to get the results of the analyses and add them as domains or IPs?

I have noticed that once an analysis is performed the results can only be checked from the analysis tab. I think it would be interesting to add the results (domains, IPs, emails, ...) to their corresponding categories. 

From the API documentation I have seen that these results cannot be checked. Do you know if there is any way?

Thank you

**Comment by mgoffin** [comment]
Most services do that, or at least present the gained intel in a way the analyst can decide if it's worth adding. Lots of malware, for example, use benign IP addresses (think 8.8.8.8) to check for connectivity. If we automatically added that as an IP it wouldn't make sense, so we err on the side of presenting and letting the analyst decide.

**Comment by ratcates** [comment]
Thank you very much. That makes a lot of sense.
