### ISSUE TITLE
Error Running Crits On Apache

### ISSUE THREAD

**Issue by Brambopulos** [crits/crits#1065]
Hello! I've followed all the steps from the official README, and then further took steps from [this updated guide](https://www.secopshub.com/t/installing-crits-collaborative-research-into-threats-on-ubuntu-16-04-lts-x64-part-1/136) in order to set up a CRITS production server; however, I'm having trouble getting it to start properly.

From /var/log/apache2/error.log:
>
[Wed Aug 12 22:16:25.637001 2020] [mpm_event:notice] [pid 32689:tid 140277725960064] AH00489: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g mod_wsgi/4.3.0 Python/2.7.12 configured -- resuming normal operations
[Wed Aug 12 22:16:25.637022 2020] [core:notice] [pid 32689:tid 140277725960064] AH00094: Command line: '/usr/sbin/apache2'
[Wed Aug 12 22:16:48.690459 2020] [wsgi:error] [pid 32694:tid 140277423486720] [client 73.71.166.171:64517] mod_wsgi (pid=32694): Target WSGI script '/data/crits/django.wsgi' cannot be loaded as Python module.
[Wed Aug 12 22:16:48.690504 2020] [wsgi:error] [pid 32694:tid 140277423486720] [client 73.71.166.171:64517] mod_wsgi (pid=32694): Exception occurred processing WSGI script '/data/crits/django.wsgi'.
[Wed Aug 12 22:16:48.690529 2020] [wsgi:error] [pid 32694:tid 140277423486720] [client 73.71.166.171:64517] Traceback (most recent call last):
[Wed Aug 12 22:16:48.690545 2020] [wsgi:error] [pid 32694:tid 140277423486720] [client 73.71.166.171:64517]   File "/data/crits/django.wsgi", line 9, in <module>
[Wed Aug 12 22:16:48.690594 2020] [wsgi:error] [pid 32694:tid 140277423486720] [client 73.71.166.171:64517]     application = get_wsgi_application()
[Wed Aug 12 22:16:48.690605 2020] [wsgi:error] [pid 32694:tid 140277423486720] [client 73.71.166.171:64517]   File "/usr/local/lib/python2.7/dist-packages/django/core/wsgi.py", line 13, in get_wsgi_application
[Wed Aug 12 22:16:48.690634 2020] [wsgi:error] [pid 32694:tid 140277423486720] [client 73.71.166.171:64517]     django.setup(set_prefix=False)
[Wed Aug 12 22:16:48.690642 2020] [wsgi:error] [pid 32694:tid 140277423486720] [client 73.71.166.171:64517]   File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 22, in setup
[Wed Aug 12 22:16:48.690669 2020] [wsgi:error] [pid 32694:tid 140277423486720] [client 73.71.166.171:64517]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Wed Aug 12 22:16:48.690678 2020] [wsgi:error] [pid 32694:tid 140277423486720] [client 73.71.166.171:64517]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 56, in __getattr__
[Wed Aug 12 22:16:48.690740 2020] [wsgi:error] [pid 32694:tid 140277423486720] [client 73.71.166.171:64517]     self._setup(name)
[Wed Aug 12 22:16:48.690746 2020] [wsgi:error] [pid 32694:tid 140277423486720] [client 73.71.166.171:64517]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 41, in _setup
[Wed Aug 12 22:16:48.690759 2020] [wsgi:error] [pid 32694:tid 140277423486720] [client 73.71.166.171:64517]     self._wrapped = Settings(settings_module)
[Wed Aug 12 22:16:48.690764 2020] [wsgi:error] [pid 32694:tid 140277423486720] [client 73.71.166.171:64517]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 110, in __init__
[Wed Aug 12 22:16:48.690772 2020] [wsgi:error] [pid 32694:tid 140277423486720] [client 73.71.166.171:64517]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Wed Aug 12 22:16:48.690782 2020] [wsgi:error] [pid 32694:tid 140277423486720] [client 73.71.166.171:64517]   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
[Wed Aug 12 22:16:48.690810 2020] [wsgi:error] [pid 32694:tid 140277423486720] [client 73.71.166.171:64517]     __import__(name)
[Wed Aug 12 22:16:48.690815 2020] [wsgi:error] [pid 32694:tid 140277423486720] [client 73.71.166.171:64517]   File "/data/crits/crits/__init__.py", line 1, in <module>
[Wed Aug 12 22:16:48.690835 2020] [wsgi:error] [pid 32694:tid 140277423486720] [client 73.71.166.171:64517]     from crits.settings import CRITS_VERSION as __version__
[Wed Aug 12 22:16:48.690840 2020] [wsgi:error] [pid 32694:tid 140277423486720] [client 73.71.166.171:64517]   File "/data/crits/crits/settings.py", line 11, in <module>
[Wed Aug 12 22:16:48.691071 2020] [wsgi:error] [pid 32694:tid 140277423486720] [client 73.71.166.171:64517]     from mongoengine import connect
[Wed Aug 12 22:16:48.691080 2020] [wsgi:error] [pid 32694:tid 140277423486720] [client 73.71.166.171:64517]   File "/usr/local/lib/python2.7/dist-packages/mongoengine/__init__.py", line 3, in <module>
[Wed Aug 12 22:16:48.691108 2020] [wsgi:error] [pid 32694:tid 140277423486720] [client 73.71.166.171:64517]     from mongoengine import document
[Wed Aug 12 22:16:48.691151 2020] [wsgi:error] [pid 32694:tid 140277423486720] [client 73.71.166.171:64517]   File "/usr/local/lib/python2.7/dist-packages/mongoengine/document.py", line 56
[Wed Aug 12 22:16:48.691155 2020] [wsgi:error] [pid 32694:tid 140277423486720] [client 73.71.166.171:64517]     class EmbeddedDocument(BaseDocument, metaclass=DocumentMetaclass):
[Wed Aug 12 22:16:48.691158 2020] [wsgi:error] [pid 32694:tid 140277423486720] [client 73.71.166.171:64517]                                                   ^`
>
I thought the issue was the improper version of Python at first, but once I confirmed that it's python2.7 I can't wrap my head around what's going on! Any help would be appreciated.

**Comment by apolkosnik** [comment]
Can you run pip freeze and post the results?

**Comment by Brambopulos** [comment]
The results of `pip freeze`:

>
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support

amqp==2.6.1
anyjson==0.3.3
billiard==3.6.3.0
biplist==1.0.3
boto==2.38.0
celery==4.4.7
chardet==2.3.0
contextlib2==0.6.0.post1
crcmod==1.7
dateutils==0.6.8
defusedxml==0.6.0
Django==1.11.29
django-celery==3.3.1
django-debug-toolbar==2.2
django-debug-toolbar-mongo==0.3.1
django-debug-toolbar-template-profiler==2.0.1
django-debug-toolbar-template-timings==0.9
django-debug-toolbar-vcs-info==1.2.0
django-mongoengine==0.3
django-tastypie==0.14.3
django-tastypie-mongoengine==0.4.6+work4.3
future==0.18.2
google-compute-engine==20190801.0
importlib-metadata==1.7.0
kombu==5.0.0
lxml==4.5.2
mongoengine==0.10.6
olefile==0.46
pathlib2==2.3.5
pefile==2019.4.18
Pillow==6.2.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycrypto==2.6.1
pydeep==0.4
pyimpfuzzy==0.5
pymongo==3.11.0
pyparsing==2.4.7
python-dateutil==2.8.1
python-ldap==3.3.1
python-magic==0.4.18
python-mimeparse==1.6.0
pytz==2020.1
PyYAML==5.3.1
qrcode==6.1
requests==2.9.1
scandir==1.10.0
simplejson==3.17.2
six==1.10.0
sqlparse==0.3.1
UNKNOWN==0.0.0
urllib3==1.13.1
ushlex==0.99.1
vine==1.3.0
virtualenv==15.0.1
wrapt==1.12.1
>

**Comment by apolkosnik** [comment]
For CRITs to function properly you need to install specific patched version of Mongoengine and some other specific packages that should be present in requirements.txt. You already have it in virtualenv installed, so it should be pretty easy to pull that off without messing up your python libraries on your system

**Comment by Brambopulos** [comment]
Thank you for your help @apolkosnik 

I have updated Mongo to the patched version available in requirements.txt, this has resolved the Apache issue just fine.

Before the update, my `script/server` would work just fine when attempting to set up CRITS for demo purposes, so it must have been using venv (appropriately configured) to get itself working. I don't know nearly enough about the venv or how WSGI works to do this on my own, but I'm okay with this being my CRITS setup for now.

I'm encountering a new issue, but I will resolve this one for the sake of continuity. Thanks again.
