### ISSUE TITLE
CRITS Not Accepting Login Information

### ISSUE THREAD

**Issue by Brambopulos** [crits/crits#1066]
Hello! I've followed all the steps from the official README, and then further took steps from [this updated guide](https://www.secopshub.com/t/installing-crits-collaborative-research-into-threats-on-ubuntu-16-04-lts-x64-part-1/136) in order to set up a CRITS production server; however, I'm having trouble getting it to accept web requests.

I can access the CRITS webpage successfully (domain'ed and cert'ed), and the 'Forgot Password' button will successfully redirect me, but I have no luck logging in. No 'wrong password' prompt, no indication that my Login button is being pressed whatsoever.

The official guide has a section which accounts for dropped web requests:
> \# This step is required prior to starting the apache2 service.  
> \# Failing to do so will cause two active SSL configurations attempting 
> \# to fight for control and will cause the server to be unresponsive to web requests. `

However, the steps that it suggests refer to files (specifically `default-le-ssl.conf`) that do not exist. From what I understand, these are auto-generated by Let's Encrypt - though running LE did not produce them for me:
>  cd /etc/apache2/sites-enabled/
> sudo mv default-le-ssl.conf default-le-ssl.bu
> sudo cp default-ssl default-le-ssl.conf
> cd /etc/apache2/sites-available/
> sudo mv default-le-ssl.conf default-le-ssl.bu
> cp default-ssl default-le-ssl.conf`

Since I am new to CRITS (and running a webapp altogether) I'm not sure where to look for error logs related to the dropped or non-functioning user input. Once again - any help is very appreciated!

**Comment by apolkosnik** [comment]
One of the recently closed issues had the same problem. Please also make sure to use mongoengine v0.8.10 from my fork

**Comment by Brambopulos** [comment]
Could you point me to which issue solved this problem? Not finding it in my own searching.

My Mongo version is the one recommended by the `required.txt`, and I was not able to find v0.8.10 in your repo.

**Comment by apolkosnik** [comment]
Take a look here https://github.com/crits/crits/pull/1057

**Comment by apolkosnik** [comment]
Or just do 
```pip install -U "git+https://github.com/apolkosnik/mongoengine.git@v0.8.10"```

**Comment by Brambopulos** [comment]
I installed your fork of mongoengine, and received this error upon success:

>django-tastypie-mongoengine 0.4.6+work4.3 requires mongoengine>=0.13.0, but you'll have mongoengine 0.8.10 which is incompatible.

Still no love getting the Web UI to work, still hammering away at it.

**Comment by apolkosnik** [comment]
You may be able to get some error messages if you look with the browsers' dev tools to inspect the requests and responses

**Comment by Brambopulos** [comment]
Getting 

> jquery-1.10.2.min.js:6 POST https://shane.tips/login/ 403 (Forbidden)
> send @ jquery-1.10.2.min.js:6
> ajax @ jquery-1.10.2.min.js:6
> processLogin @ core.js:42
> (anonymous) @ VM49:1

Think I can work with this... let's find out

**Comment by Brambopulos** [comment]
Looks like this relates to #922, they have not found a permanent workaround but I will update this ticket if I do

**Comment by nathanhunstad** [comment]
I added the following to get around this, give this a try:
In crits/core/views.py add the following import:

`from django.views.decorators.csrf import ensure_csrf_cookie`

Also add "@ensure_csrf_cookie"  above def login(request) in the same file so it looks like this:
```
# Mongo Auth
@ensure_csrf_cookie
def login(request):
```

**Comment by Brambopulos** [comment]
@nathanhunstad was able to solve my problem.

I also found a setting in `settings.py`, where the CSRF cookie protection was enabled for HTTPOnly, which is curious as it is primarily used for SSL authentication. As it were, changing that to FALSE also fixed the issue in another test instance.

Thanks all
