### ISSUE TITLE
Initial Installation: Unknown command: 'create_default_collections'

### ISSUE THREAD

**Issue by nitrogear** [crits/crits#132]
Following the build instructions, crits_dependencies successfully loaded on clean install of Ubuntu LTS 14.04. When trying to run:

``` bash
python manage.py create_default_collections
```

I get error:

``` bash
Unknown command: 'create_default_collections'
Type 'manage.py help' for usage.
```

**Comment by Halo89** [comment]
Hi everyone. I´m getting this error:
"ImportError: Could not import settings 'crits.settings' (Is it on sys.path?): No module named bson.errors"
Could you please, one of you, take me a hand.
Thanks in advance

**Comment by dsnellgrove** [comment]
@Halo89 Necro-posting on someone else's bug report is the wrong place to ask for installation assistance. Check out the community links on https://crits.github.io/ for correct places to ask for help installing dependencies.
