### ISSUE TITLE
Virus Total Service not showing

### ISSUE THREAD

**Issue by Shersto** [crits/crits#157]
Any idea why the Virus Total service would fail to appear under services in Control Panel when the directory is pointing correctly. All in all its in the same directory as the rest, but the others show with the exception of VT. Strange.

**Comment by affvei** [comment]
Did you solved ?

**Comment by frbapolkosnik** [comment]
The bootstrap should have taken care of the dependencies, so likely you need to get an  API key from VirusTotal to get this to work.

**Comment by affvei** [comment]
I just installed simplejson (pip install simplejson) and it worked
