### ISSUE TITLE
running services against metadata only samples?

### ISSUE THREAD

**Issue by villain** [crits/crits#177]
not sure how much of a unique use case this is .. but certain products(?) in the crits services (virustotal, cuckoo, totalhash..) allow for the querying of md5s with results being returned via their api. it would be nice to be able to submit a metadata only sample to crits (for when you don't have the actual sample) and have the crits services pull back whatever data they can from the respective apis as if you had the actual sample

this would mostly be catering for situations when threat reports are released by the various vendors and you don't have access to the actual samples but they exist on virustotal for example

**Comment by brlogan** [comment]
Since this was never fixed in the distributed_services branch, I've submitted a new PR #755.
