### ISSUE TITLE
Support recursive parsing of cybox related objects

### ISSUE THREAD

**Issue by mgoffin** [crits/crits#214]
CybOX allows you to define embedded objects as "Related Objects". We currently don't look at Related Objects to see if there are any to parse. We would need to loop over each one and parse it separately, including checking for more embedded Related Objects.

This completely ignores the potential for an object which is just an IDREF to another object in the document (not sure if that's STIX land or CybOX land).

**Comment by mgoffin** [comment]
CybOX/STIX are no longer a part of core. They are a part of the TAXII service and if there are issues now that the code has moved, new ones should be created in the `crits_services` Issue tracker.

**Comment by brlogan** [comment]
Totally have addressed this...hopefully I can share it one of these days...sigh
