### ISSUE TITLE
STIX backwards compatibility

### ISSUE THREAD

**Issue by paulpc** [crits/crits#253]
when trying to upload a doc, i get this:Your python-stix library supports STIX 1.1.1. Document version was 1.0

I know this is a function of python-stix and other things outside of CRITs, but i was curious if anybody has a solution  / workaround / converter.
Thanks!

**Comment by mgoffin** [comment]
CybOX/STIX are no longer a part of core. They are a part of the TAXII service and if there are issues now that the code has moved, new ones should be created in the `crits_services` Issue tracker.
