### ISSUE TITLE
Improper handling of pcap files from S3

### ISSUE THREAD

**Issue by puhley** [crits/crits#255]
When using /crits/pcaps/pcap.py, the class will set filedata = getFileField(collection_name) when it initializes. The getFileField() method from /crits/core/fields.py splits its logic based on whether the FILE_DB variable is set to GRIDFS or S3. If FILE_DB is set to S3, then it will return an S3FileField(db_alias, collection_name) object which will utilize the S3Proxy class to abstract the filesystem. The S3FileField object is assigned to pcap.filedata.

The chopshop service will initialize a pcap object for the file id that it wants to analyze. It will then call pcap.filedata.read(). Since filedata is an S3FileField object based on the S3Proxy class, this read() call is sent to the S3Proxy.read(size) method in /crits/core/fields.py.  The read() function calls S3Proxy.get(id) in order to initialize gridout with the pcap data associated with that id. In turn, the get(id) function will call S3.get_file_s3(grid_id, collection_name) from /crits/core/s3_tools.py. The get_file_s3 function() will return the file obtained from S3 using k.get_contents_as_string(). This string gets returned all the way back up the stack to the S3Proxy.read(size) method where the string is assigned to the gridout variable (fields.py line 94). The problem is that the S3Proxy.read(size) function will try to return gridout.read(size) at line 99. The method expected gridout to be a file which is what happens when FILE_DB is set to GRIDFS. Since gridout is returned as a string in the S3 workflow, Python throws an exception because the string class doesn't contain a read() method.

There are a couple ways to fix this depending on the intended architecture.  Since gridout is already a string, the S3Proxy.read() function could just return the string. Although, this would result in the function ignoring the size parameter that was passed in. If you wanted to honor the size parameter, then you could add code to S3_tools.py which could return the data as a file rather than as a string.

In my extremely limited tests with the chopshop service, I would catch the exception thrown for the missing read method and just return gridout itself (ignoring the size request). This appeared to work for my short term needs. Although, I did not try using this rough patch with other services or with a large number of files.

**Comment by puhley** [comment]
I believe there is also an issue in the download_object_handler function in /crits/crits/core/handlers.py where the code tries to call: obj.filedata.seek(0)  Similar to the issue described above, the S3 file is a string and therefore does not have a seek method. This issue can be reproduced when you try to download a Sample via the CRITs UI. The error that is thrown is an AttributeError from __getattr__ in fields.py line 57.  I temporarily addressed it by adding, "if settings.FILE_DB != settings.S3:" before the seek call in handlers.py. I'll see if I can find some time to propose an official solution for both issues. In the meantime, does anyone have any suggestions as to the correct approach?  Should S3_tools just return items as files instead of strings?

**Comment by frbapolkosnik** [comment]
The same kind of thing happens when a service is attempted to be run against things like domains... Example is running virustotal lookup against a domain.
