### ISSUE TITLE
STIX import issue

### ISSUE THREAD

**Issue by paulpc** [crits/crits#278]
I am testing out the STIX import thing, but am seeing some odd behavior:
URI	ID: None
"Observable" is currently unsupported for input into CRITs.
URI	ID: None
"Observable" is currently unsupported for input into CRITs.
For the FWQN list at: http://stix.mitre.org/downloads/APT1-STIX.zip

I will confess i just  changed the version in the document from 1.0.1 to 1.1.1, but i'm not sure that's the issue.

**Comment by mgoffin** [comment]
CybOX/STIX are no longer a part of core. They are a part of the TAXII service and if there are issues now that the code has moved, new ones should be created in the `crits_services` Issue tracker.
