### ISSUE TITLE
crits_mongoengine can create schema invalid STIX

### ISSUE THREAD

**Issue by MarkDavidson** [crits/crits#289]
The way CRITs assigns STIX Package IDs can sometimes create schema-invalid STIX [1]

```python
stix_msg['stix_obj'] = STIXPackage(indicators=stix_msg['stix_indicators'],
                        observables=Observables(stix_msg['stix_observables']),
                        threat_actors=stix_msg['stix_actors'],
                        stix_header=header,
                        id_=uuid.uuid4())
```
The STIX_Package/id field must adhere to the XML QName structure. Only some of the UUIDs that CRITs generates are valid. An unprefixed QName (e.g., what the UUID would be) can not start with a number. Therefore a UUID of `cc6b5684-cd92-4987-89c6-df03b192cff2` is valid, and a UUID of `466d060d-0500-41b7-be88-6df46af466c8` is invalid.

Currently, I see three possible remediations, all probably belong in the CRITs code:
1. Prefix all IDs with `package` (per the suggested practices [2])
2. Have CRITs use the defined namespace prefix.
3. Both

[1] https://github.com/crits/crits/blob/424af38a1213912ea802dc80cd2362aa64fb34d6/crits/core/crits_mongoengine.py#L764

**Comment by mgoffin** [comment]
CybOX/STIX are no longer a part of core. They are a part of the TAXII service and if there are issues now that the code has moved, new ones should be created in the `crits_services` Issue tracker.
