### ISSUE TITLE
STIX import says no version attribute set, but version attribute is set

### ISSUE THREAD

**Issue by bond-alexander** [crits/crits#302]
I'm trying to import a STIX file from IT-ISAC into CRITs, but when I try to import it, it gives the following error:
```
No version attribute set on xml instance. Unable to determine version compatibility
```
The problem is that there is a version set on the XML tag, and in the stix:STIX_PACKAGE tag.

```
<?xml version='1.0' encoding='UTF-8'?>
```

Why would CRITs be unable to recognize the version tag?

**Comment by SyntaxGeek** [comment]
I know this is an old issue but I've just recently ran into this, and these IT-ISAC stix files are using a custom header that is not STIX compliant, there is a couple of simple edits that need to be done and they'll import just fine, the consolidated CISCP files are another story and I believe that's what stix-ramrod is for (awesome name btw).

**Comment by drakearonhalt** [comment]
@SyntaxGeek could you share those edits on the IT-ISAC forum? I'm having the same issue.

**Comment by mgoffin** [comment]
CybOX/STIX are no longer a part of core. They are a part of the TAXII service and if there are issues now that the code has moved, new ones should be created in the `crits_services` Issue tracker.
