### ISSUE TITLE
Downloading Indicators

### ISSUE THREAD

**Issue by taylormd** [crits/crits#339]
As I am am looking at an indicator, I try to download it as a STIX document and this error is what comes up. 'UUID' object has no attribute 'replace'
The code down in there says this is causing issues. Any ideas how to correct it?
entities {'\t': '&#9;', '\n': '&#10;', '\r': '&#13;'}
data	UUID('1a7e753a-4491-44f5-89af-3ca536ea9fca')

**Comment by mgoffin** [comment]
Since we removed CybOX and STIX from core, if this is still a problem it exists in the TAXII service and should be fixed there.
