### ISSUE TITLE
Fresh Install Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by danielheth** [crits/crits#356]
I ran into several issues trying to get CRITs setup on a fresh install of Ubuntu 14.04 LTS... here is what i did to fix... suggest updating crits_dependencies and crits instructions...

1. pip install stix
2. pip install ushlex
3. DocumentType=None  (anything else is not supported by 2.2.7 apache)
4. chgrp -R crits /data/crits/
5. chown -R crits /data/crits/

**Comment by asko123** [comment]
@danielheth were you able to install crits production successfully ? I have been beating through it for weeks with no success.. any tips would be awesome
