### ISSUE TITLE
CRITs API seems not to support creation of indicator relationships to observables

### ISSUE THREAD

**Issue by treyka** [crits/crits#369]
Hey, y'all -

I'm trying to create indicators via the api. After pulling my hair out for hours, flipping between the CRITs source and my debugger session, I'm convinced that either I'm doing it wrong or something is broken.

Here's an example of the json I'm posting to the indicators endpoint...

<snip>
{'username': '<sanitized>', 'impact': {'rating': 'unknown'}, 'confidence': {'rating': 'unknown'}, 'relationships': [{'rel_confidence': 'unknown', 'relationship': 'Contains', 'value': '54b69ceab9451e6bb27b43e3', 'type': 'IP'}], 'value': '8263b258-516b-49a3-b093-ead9ef8d1f76_sample_indicator', 'source': 'example', 'api_key': '<sanitized>', 'type': 'Reference', 'add_relationship': True}
</snip>

The ip object referred to by 54b69ceab9451e6bb27b43e3 already exists. From what I'm seeing, the indicator gets created fine but no relationships are created.

Help? Thanks a mil, guys!

**Comment by mgoffin** [comment]
Doesn't seem like you are reading the documentation for the API. Passing a dictionary into things like confidence and impact isn't correct.

Please read the documentation found here: https://github.com/crits/crits/wiki/Authenticated-API#indicator-api

I would also read the API documentation in general as you can't create relationships like that. There's an entirely separate API for relationship generation found here: https://github.com/crits/crits/wiki/Authenticated-API#relationship-api

**Comment by treyka** [comment]
I have read the (sparse) documentation and have been triangulating off api/v1/indicators/schema/, json output of indicators created through the web, and examination of the source code. If I mention in my issue (as I did) both the use of a debugger and review of source, it's fair to assume that I've rtfm. So don't lmgtfy me. o_O

The indicator api documentation (as it currently reads) strongly suggests that relationship creation is possible via the indicator endpoint.

I'll experiment with the relationship api.

Thank you for your response.

**Comment by mgoffin** [comment]
Let's review what the documentation shows for available POST parameters.

Common parameters available to set when adding any TLO would be:

* bucket_list:	Comma-separated list of buckets.
* source:	Name of the source which provided this information.
  * should be a source already in your CRITs instance.
* method:	Method in which the information was acquired from the source.
* reference:	Reference for the source of the information.
* campaign:	Campaign associated with this information.
* confidence:	Campaign confidence associated with this information.
  * must be one of "low", "medium", or "high"
* ticket:	Associated Ticket.

Parameters specific to Indicators:

* add_domain:	Add a Domain to CRITs if this is a domain indicator.
* add_relationship:	Add a relationship if this is a Domain, IP, etc.
* indicator_confidence:	The confidence level of this Indicator.
  * Must be one of "unknown", "benign", "low", "medium", "high".
* indicator_impact:	The impact level of this Indicator.
  * Must be one of "unknown", "benign", "low", "medium", "high".
* type:	The type of the Indicator.
* value:	Indicator value.

Based on this information, let's look at what you are telling us you are submitting as post data:

```python
{'username': '',
'impact': {'rating': 'unknown'},
'confidence': {'rating': 'unknown'},
'relationships': [{'rel_confidence': 'unknown', 'relationship': 'Contains','value': '54b69ceab9451e6bb27b43e3','type': 'IP'}],
'value': '8263b258-516b-49a3-b093-ead9ef8d1f76_sample_indicator',
'source': 'example',
'api_key': '',
'type': 'Reference',
'add_relationship': True}
```

Using the documentation, I can see the following issues:

* You are trying to set the Indicator impact using an "impact" parameter but the documentation says to use "indicator_impact".
* You are setting the Indicator impact to a dictionary but the documentation says to set it to a string of "unknown", "benign", "low", "medium", or "high".
* You are trying to set the Indicator confidence using a "confidence" parameter but the documentation says to use "indicator_confidence".
* You are setting the Indicator confidence to a dictionary but the documentation says to set it to a string of "unknown", "benign", "low", "medium", or "high".
* You are setting a "relationships" parameter in an attempt to create a relationship but the documentation shows that there is no such parameter available in either the common or Indicator-specific POST parameters.

The above reasons would be why I suggested you might need to read the documentation to figure this out. You are using `/schema/` which is telling you the document format of the content in the database, not the POST parameters that are allowed.

Good  luck!

**Comment by webstergd** [comment]
Hey treyka,
I am having some trouble understanding what you are doing from your JSON blob. Hopefully this is actually useful to you. 

Anyway attached is a snippet of I wrote that adds samples and domains to crits and creates a relationship. It seems to work pretty well. 

```python   
    url = "{0}/api/v1/relationships/".format(config.get('Maltrieve', 'crits'))
    relationship_data = {
        'api_key': cfg['crits_key'],
        'username': cfg['crits_user'],
        'source': cfg['crits_source'],
        'right_type': domain_response_data['type'],
        'right_id': domain_response_data['id'],
        'left_type': sample_response_data['type'],
        'left_id': sample_response_data['id'],
        'rel_type': 'Downloaded_From',
        'rel_confidence': 'high',
        'rel_date': datetime.datetime.now()
    }
    relationship_response = requests.post(url, headers=headers, data=relationship_data, verify=False)
```

You would need to do something similar based on the indicator or common API options. This is in the documentation but you can also find it in the python code crits/indicators/api.py. Most of the inputs are all string with a few bools.
```python
        analyst = bundle.request.user.username
        value = bundle.data.get('value', None)
        ctype = bundle.data.get('type', None)
        source = bundle.data.get('source', None)
        reference = bundle.data.get('reference', None)
        method = bundle.data.get('method', None)
        add_domain = bundle.data.get('add_domain', False)
        add_relationship = bundle.data.get('add_relationship', False)
        campaign = bundle.data.get('campaign', None)
        campaign_confidence = bundle.data.get('confidence', None)
        confidence = bundle.data.get('indicator_confidence', None)
        impact = bundle.data.get('indicator_impact', None)
        bucket_list = bundle.data.get('bucket_list', None)
        ticket = bundle.data.get('ticket', None)
```

Hopefully that helps.

**Comment by treyka** [comment]
Thanks, guys! Dunno how I missed the relationship endpoint but that did the trick!
