### ISSUE TITLE
Error while uploading a STIX Document

### ISSUE THREAD

**Issue by frbapolkosnik** [crits/crits#377]
I've encountered errors while trying to upload the STIX docs listed at 
https://stix.mitre.org/language/version1.1.1/samples.html in particular the documents inside: poison_ivy-stix-1.1.1.zip

ERROR 2015-01-28 12:48:47,011 crits.standards.handlers local variable 'item' referenced before assignment
Traceback (most recent call last):
  File "/data/crits/crits/standards/handlers.py", line 42, in import_standards_doc
    parser.parse_stix(reference=ref, make_event=make_event, source=source)
  File "/data/crits/crits/standards/parsers.py", line 113, in parse_stix
    self.parse_indicators(self.package.indicators)
  File "/data/crits/crits/standards/parsers.py", line 154, in parse_indicators
    self.failed.append((e.message, type(item).__name__, item.parent.id_)) # note for display in UI
UnboundLocalError: local variable 'item' referenced before assignment
ERROR 2015-01-28 12:49:07,619 crits.standards.handlers local variable 'item' referenced before assignment
Traceback (most recent call last):
  File "/data/crits/crits/standards/handlers.py", line 42, in import_standards_doc
    parser.parse_stix(reference=ref, make_event=make_event, source=source)
  File "/data/crits/crits/standards/parsers.py", line 113, in parse_stix
    self.parse_indicators(self.package.indicators)
  File "/data/crits/crits/standards/parsers.py", line 154, in parse_indicators
    self.failed.append((e.message, type(item).__name__, item.parent.id_)) # note for display in UI
UnboundLocalError: local variable 'item' referenced before assignment

**Comment by johnfellers** [comment]
i get the same error.

I found that if i check the 'create event' checkbox it results in a different error message as well.

With 'create event' checked:
ERROR 2015-09-18 11:26:32,034 crits.standards.handlers list index out of range
Traceback (most recent call last):
  File "/data/crits/crits/standards/handlers.py", line 42, in import_standards_doc
    parser.parse_stix(reference=ref, make_event=make_event, source=source)
  File "/data/crits/crits/standards/parsers.py", line 128, in parse_stix
    event_type = str(header.package_intents[0])
  File "/usr/local/lib/python2.7/site-packages/stix/base.py", line 449, in __getitem__
    return self._inner.__getitem__(key)
IndexError: list index out of range

With 'create event' unchecked:
ERROR 2015-09-18 11:26:43,121 crits.standards.handlers local variable 'item' referenced before assignment
Traceback (most recent call last):
  File "/data/crits/crits/standards/handlers.py", line 42, in import_standards_doc
    parser.parse_stix(reference=ref, make_event=make_event, source=source)
  File "/data/crits/crits/standards/parsers.py", line 160, in parse_stix
    self.parse_indicators(self.package.indicators)
  File "/data/crits/crits/standards/parsers.py", line 274, in parse_indicators
    self.failed.append((e.message, type(item).__name__, item.parent.id_)) # note for display in UI
UnboundLocalError: local variable 'item' referenced before assignment

anyone gotten any progress on this?

**Comment by gtback** [comment]
@johnfellers: What version of CRITs are you running? The STIX support was removed to to the TAXII service in #523.

**Comment by johnfellers** [comment]
@gtback 

did not see that. thanks for the update.

for the record i am running 15244f7f231505bc9024c55d91ba16759d4f91f0 - master

**Comment by gtback** [comment]
Whatever is causing the error was probably a problem with the code in `crits/standards/parsers.py`, but since that code is no longer in master, I doubt it will get fixed in the old branches of CRITs.

**Comment by packet-rat** [comment]
You might want to check stable_4 branch.  We (Brad Logan et al) cleaned up a lot of issues with STIX Ingestion/Extraction and have TAXII exchange working fairly well (at least between CRITs instances).  Also within stable_4 branch we have the Soltra Edge CRITs API Adapter working as well.

Patrick Maroney



On Sep 18, 2015, at 3:17 PM, Greg Back <notifications@github.com> wrote:

Whatever is causing the error was probably a problem with the code in crits/standards/parsers.py, but since that code is no longer in master, I doubt it will get fixed in the old branches of CRITs.

**Comment by mgoffin** [comment]
I wouldn't count on that :) master will get merged to stable_4 soon and
I'll bet there will be some work people will want to contribute to the
TAXII service for more support.

**Comment by johnfellers** [comment]
It was. I dug in the code and found that in the parse indicators function there was a variable 'item' that was not properly getting assigned.

Respectfully,

John Fellers

**Comment by johnfellers** [comment]
Awesome, I'll have to check that out... Literally.. heh. I had been messing with the soltra->crits adapter and it was having issues as well, but it was on the soltra side and not crits. I was able to use datagen.py and push test data over to crits just fine.

Respectfully,

John Fellers

**Comment by mgoffin** [comment]
https://github.com/crits/crits_services/commit/d7456a079371c8615d514c7366332af016eaff39

See if that fixes anything!

**Comment by johnfellers** [comment]
Hey thanks Mike! I pulled down the changes and I will test it out. Won't be able to get back to this until Monday but will report back results. Thanks.

Respectfully,

John Fellers

**Comment by mgoffin** [comment]
CybOX/STIX are no longer a part of core. They are a part of the TAXII service and if there are issues now that the code has moved, new ones should be created in the `crits_services` Issue tracker.
