### ISSUE TITLE
def refresh_services assumes crits type will have source attribute

### ISSUE THREAD

**Issue by SyntaxGeek** [crits/crits#389]
In crits/services/views.py @ 206

klass = class_from_type(crits_type)
obj = klass.objects(id=identifier,source__name__in=sources).first()

This is throwing an error for refreshing services on Targets Analysis tab as Target doesn't have attribute of "source".

From my understanding, I'm not sure why this filter would be needed at all, seems like this being hidden is incorrect and should be moved to a setting like "Filter available crits type services based on type source".

**Comment by frbapolkosnik** [comment]
I've seen this in my logs recently after I've done some surgery/maintenance on my user accounts and their sources. It could be related to a missing user or a missing source. I guess these should not occur unless you remove stuff through mongo.

**Comment by wxsBSD** [comment]
I thinks this can easily be fixed by checking if klaus has a source attribute and if not then don't include it in the query.

**Comment by wxsBSD** [comment]
Fixed in #391.
