### ISSUE TITLE
def run_service in crits/services/handlers.py assumes obj has attribute "filedata"

### ISSUE THREAD

**Issue by SyntaxGeek** [crits/crits#390]
Running through some modifications for CRITS in allowing crits_type "Target" the ability to have service modules executed and running into the error for this portion of code:

    # Give the service a chance to check for required fields.
    try:
        service_class.valid_for(local_obj.obj)
        # Reset back to the start so the service gets the full file.
        local_obj.obj.filedata.seek(0)
    except ServiceConfigError as e:
        result['html'] = str(e)
        return result

The above code assumes that the obj being referenced will have filedata attribute, I'm assuming this is just an area where further use cases need to be defined, (eg: uncharted territory :D)

I've done a simple modification (extra lines skipped for brevity):

        if hasattr(local_obj.obj, 'filedata'):
            local_obj.obj.filedata.seek(0)

I haven't seen anything in the documentation that references the current design state and what services are supposed to be run against - it seems as though it's left up to the service creator as they can specify the crits_types supported by the service but it seems crits itself is only supporting services for a subset of the crits_types.

**Comment by frbapolkosnik** [comment]
That's fixed as of Friday... in #388

**Comment by frbapolkosnik** [comment]
You can close this issue, as the exact fix went into the master tree last Friday.

**Comment by SyntaxGeek** [comment]
Ah, sorry about that. Thanks!
