### ISSUE TITLE
Add more features to bootstrap

### ISSUE THREAD

**Issue by mgoffin** [crits/crits#398]
* Ask to clone crits_services repo to a specific location.
* Ask to start MongoDB as a local single-server instance.
  * If so:
    * Copy `crits/config/database_example.py` to `crits/config/database.py`.
      * Create and set a SECRET_KEY in the `database.py` file.
    * Run `python manage.py create_default_collections`.
    * Ask for user information to create admin user.
    * If we cloned crits_services repo, add it to database configuration using `setconfig`.
    * (?) Ask about setting up default cronjobs and automatically add them for the current user.
    * Ask to start runserver for them.

There might be some other things we want to do in there like ask the name of the user's Organization and use it when creating the user, adding it as the first Source in the system, and giving the user access to it. There might also be some other Control Panel related configuration items that we want to ask about to make sure all is well when runserver starts.

I don't think we want to get into Apache configuration with this. Using runserver as a quick "hey, it works!" is probably sufficient. If the user wishes to dive into the world of production installations they can do so after that.

**Comment by krmaxwell** [comment]
I'd also add "detect virtualenv" in here, so that `pip install` doesn't automatically get prepended with sudo if not necessary.

**Comment by mgoffin** [comment]
Good call :) I'm hoping we don't have to do much more than virtualenv stuff. If people want to use bootsrap in docker/vagrant/etc. then I think it should stay away from bootstrap unless someone can give me a really good reason (which might not be hard since I tend not to use these technologies).
