### ISSUE TITLE
Attribute error when running services for MetaData-only sample.

### ISSUE THREAD

**Issue by TalonStryk** [crits/crits#399]
There appears to be an issue with services on MetaData-only samples in the latest master.  On the analysis tab, none of the services will run.  The service I am testing with is the VirusTotal service.  I don't think the issue is with the VirusTotal service itself, as the code hasn't changed since I used it with one of the stable branches back in November, where it worked properly.  I enabled debug logging, and this is the error that is generated when I attempt to run the VirusTotal service:

DEBUG 2015-02-18 19:37:11,273 crits.core.errors ['Traceback (most recent call last):\n', '  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 112, in get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n', '  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view\n    return view_func(request, *args, **kwargs)\n', '  File "/data/crits/crits/services/views.py", line 189, in get_form\n    return service_run(request, name, crits_type, identifier)\n', '  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view\n    return view_func(request, *args, **kwargs)\n', '  File "/data/crits/crits/services/views.py", line 266, in service_run\n    custom_config=custom_config)\n', '  File "/data/crits/crits/services/handlers.py", line 192, in run_service\n    local_obj.obj.filedata.seek(0)\n', '  File "build/bdist.linux-x86_64/egg/mongoengine/fields.py", line 1099, in __getattr__\n    raise AttributeError\n', 'AttributeError\n']

**Comment by wxsBSD** [comment]
I think I know what is going on. Will get a fix in shortly.

**Comment by wxsBSD** [comment]
I think I know what is going on. Will get a fix in shortly.

**Comment by wxsBSD** [comment]
Fix will have to wait until tomorrow. Sorry!
