### ISSUE TITLE
Could not import settings 'crits.settings'

### ISSUE THREAD

**Issue by Halo89** [crits/crits#413]
Hi everyone. I´m getting this error:
"ImportError: Could not import settings 'crits.settings' (Is it on sys.path?): No module named bson.errors"
Could you please, one of you, take me a hand.
Thanks in advance

**Comment by mgoffin** [comment]
It's telling you that you are missing a module. Please make sure you've installed all of the dependencies properly.

**Comment by Halo89** [comment]
I just take a look for al dependencies, one by one, y pip sais that all of then are installed. In fact, i had to make a manual installation(i not used the bootstrap script) because and trying to install in Debian.
First i created a crits/crits folder and put all files there. Then, i follow the steps that you describes in the script. apt-get end next all pipy install. Mongo started sucefully, i created de secret key ando put it on the database, create /data/db. All of the steps.

**Comment by mgoffin** [comment]
Debian is not a supported distro, so please be aware you are treading into territory we don't support and will provide minimal/no assistance for as far as installation/setup goes.

That being said, the error above is showing you exactly what module is missing: `bson.errors`. If I had to take a guess, you have a bson package installed that is *not* the one that comes with pymongo.

**Comment by Halo89** [comment]
Ok, thanks for that, but i´m trying to use Debian cause Ubuntu is a distro from Debian, but i will get in mind your comments, i would try to search bson.errors. If I not find anything, i will install Ubuntu then. Thanks again. Good support from you guys

**Comment by Halo89** [comment]
"mgoffin", sorry if I came again to put some doubt. This is the error that raise once the bootstrap linecode has been executed "python manage.py create_default_collections" 

from mongoengine import QuerySetNoCache as QS
ImportError: cannot import name QuerySetNoCache

Please, could you give me some comments!!!

**Comment by mgoffin** [comment]
You either don't have mongo engine installed or the wrong version. Please
review all of the dependencies and make sure they are installed. You can
also move away from Debian and over to a supported OS.

**Comment by Halo89** [comment]
Thanks again, minutes after post my comment, i don´t know why i supposed the idea that you explanained and i install AGAIN "mongo-engine" and IT WORKS!!!, like said on lastest post, in Debian. 
Thanks for you support, we keep in touch!!!
