### ISSUE TITLE
STIX Parsers - Email [Branch: parsers_use_handlers]

### ISSUE THREAD

**Issue by packet-rat** [crits/crits#416]
Branch: parsers_use_handlers

Mike,

So far in testing, the new parsers are all working well with the exception of Email ingestion via the TAXII Agent (A number of different packages with email have been tested with the same outcome):

EmailMessage: 'NoneType' object has no attribute 'to_list'

You can re-create by sending a STIX package to MITRE via TAXII Service from either DCRITs instance .

![voila_capture 2015-03-11_10-04-28_pm](https://cloud.githubusercontent.com/assets/3220193/6611151/0ea05b26-c83f-11e4-8de0-00a3064f9b12.jpg)

**Comment by mgoffin** [comment]
Thanks for testing! I'll see if I can take a look at that and see what the deal is. I think this is probably the same issue I'm in the midst of debugging but I'll soon find out :)

**Comment by mgoffin** [comment]
Just pushed a quick change. See if that works for you!

**Comment by brlogan** [comment]
I believe this was addressed as part of #427.
