### ISSUE TITLE
Add the ability to create a Campaign TLO from the Event Details page

### ISSUE THREAD

**Issue by kfaber** [crits/crits#418]
For the Campaign TLO you already can link from Event Details, but you cannot Create directly from this page. 

I'd like to propose adding functionality to Create and automatically link a Campaign TLO from Event Details. This should include automatically creating a bi-directional Relationship as well.

**Comment by mgoffin** [comment]
You can already attribute campaigns for each TLO. This is also a subset request of another one that was just added so it will be closed.
