### ISSUE TITLE
Log out of CRITs

### ISSUE THREAD

**Issue by advancedeng** [crits/crits#426]
Am I missing something? Is there a way to log out?

**Comment by mgoffin** [comment]
Nav Menu -> Log Out

**Comment by dsnellgrove** [comment]
You may be suffering from https://github.com/crits/crits/issues/63 which was not fixed at the time of the last stable release.

**Comment by advancedeng** [comment]
True, this is the problem. Could not see at the bottom of the Nav Menu

**Comment by wxsBSD** [comment]
I tried to take a stab at fixing this as discussed in #63, but anytime I touch front-end things I end up horribly confused and questioning my life choices. I'm hoping someone who is better at this can tackle it.

**Comment by dsnellgrove** [comment]
The "perfect" solution is to switch to a better routine (and even full-on package manager; see Bower for example) of managing the amalgamation of frontend libraries that have been accumulated and ensuring they're kept up to date as needed/desired.

The "good enough" solution is to upgrade the buggy library on its own.

The "well, it works now" solution for folks on 3.1 (and possibly master) is to apply the patch in https://github.com/crits/crits/issues/63#issuecomment-66346372 (it's what I've done in my local fork to avoid wading into the larger challenges of the above options)
