### ISSUE TITLE
Raw email upload causes crash (when malformed, ish)

### ISSUE THREAD

**Issue by dsnellgrove** [crits/crits#431]
This could be 2-3 bugs depending on your design decisions.

Calling add_email in pycrits creates a post with a file upload. If you upload type "raw" with this function it sends the file bundle to the API. crits.emails.api.EmailResource.obj_create which puts the file data in as the first parameter to the function crits.emails.handlers.handle_pasted_eml.  This function calls .split() on that file blob (a InMemoryFileObject) at this point which it does not support since it isn't text. This makes CRITs crash.

So either pycrits is creating the request incorrectly or the API is sending the request to the wrong function (or the code in crits.core.api that does that strange stuff with file bundles is messing up the original design of the email API). Either way crashing is never the correct response to a malformed request :)

To recreate the crash of CRITs, use pycrits and call add_email('raw', 'somesource', filepath='somefilepath')

**Comment by mgoffin** [comment]
I say we leave this issue here until we decide if this is a pycrits or CRITs thing (I suspect the latter as pycrits is a very light wrapper around the API at this time).

**Comment by mgoffin** [comment]
Looking at it I suspect the simple fix is just to add `.read()` to https://github.com/crits/crits/blob/master/crits/emails/api.py#L100
