### ISSUE TITLE
Email Attachments not included during STIX Import/Export

### ISSUE THREAD

**Issue by brlogan** [crits/crits#437]
When an Email is exported from CRITs to a STIX document, the email's attachments are not included. Similarly, if a STIX document contains an Email with attachments, those attachments are not imported into CRITs.

**Comment by brlogan** [comment]
Due to a bug in python-cybox, relationships are not properly maintained when using the `add_related` function to generate a STIX document. See CybOXProject/python-cybox#237 for further details.

**Comment by mgoffin** [comment]
CybOX/STIX are no longer a part of core. They are a part of the TAXII service and if there are issues now that the code has moved, new ones should be created in the `crits_services` Issue tracker.
