### ISSUE TITLE
String Indicator does not properly export to STIX

### ISSUE THREAD

**Issue by brlogan** [crits/crits#442]
When exporting a Indicator of type String to a STIX document, the resulting XML does not include the Indicator value.

**Comment by brlogan** [comment]
After some poking, I'm still not certain how to correctly handle this, so I'm going to bug @gtback again. :)

**Comment by gtback** [comment]
@brlogan - Is this also addressed by #493? Is there anything else you need from me regarding this one?

**Comment by brlogan** [comment]
Thanks for the reminder, Greg.
I don't need anything else from you at the moment, but I will be sure to let you know if I think of something.
