### ISSUE TITLE
Problem adding targets to campaign

### ISSUE THREAD

**Issue by robertsjw** [crits/crits#443]
There's a problem with the expected functionality of the "Targets" object and their association with campaigns.  I would expect the ability to add a "target" to a campaign regardless of whether or not I have imported any email into CRITs to this campaign.  As it currently exists, "Targets" only show up in a campaign if I have added a target to the campaign and imported an email targeting the user that is also associated with the campaign.

**Comment by brlogan** [comment]
I noticed this issue many months ago and finally did some work on it a few weeks back, but got re-prioritized. I'll see if I can get a PR in relatively soon to address this.
