### ISSUE TITLE
Users Control Panel - Document Schema

### ISSUE THREAD

**Issue by sgerlach** [crits/crits#454]
Hi,

I may have missed a step in an upgrade, after our CRITs upgrade today to commit version bc39e840b05ba077797e31971534885b61e3351f we are getting an error when loading the Users Control Panel of "ERROR: Document schema is unrecognized: 0. Sort performed on: username" I've been poking around for a user upgrade command and haven't seen one. Is there a mongo command or a manage.py command I should have run?

We will be working on upgrading to the latest commit in parallel but want to make sure we get the problem corrected..

**Comment by thelok** [comment]
Login to mongo and do:

db.users.find( { "schema_version" : { "$exists" : false } } )

This will identify which users have the issue. I guess you could remove/add the users or manually specify a schema version. I don't know what causes this issue as I've run into it recently creating campaigns.

**Comment by sgerlach** [comment]
Hmmm, yup that fixed it. Removed the one user that didn't have a schema and works again. Thanks!
