### ISSUE TITLE
Bootstrap Issues: File Permission and Python Version Hades

### ISSUE THREAD

**Issue by pixel5919** [crits/crits#460]
The bootstrap script works however with the use of sudo, in CentOS the python modules are attached to the sudo's python and not to the user's upgraded python that supports Crits.

In OS X, the use of sudo to run the script leads to the creation of folders only accessible to the root as well as python modules being only installed to the default system and not to the user's version of python. 

In both operating systems, Crits will only run as a root process in order to access the folders and locks of the database. 

At least for OS X and CentOS we should add the script:
if (($EUID = 0)) ; then
       echo "Do not run this script as sudo"
       exit
fi

The installation of Homebrew already includes this warning.

**Comment by frbapolkosnik** [comment]
After the latest commit to the bootstrap this doesn't apply since python2.7/pip2.7 are used.
