### ISSUE TITLE
Email API - Associated Tickets Being Added as Campaigns

### ISSUE THREAD

**Issue by TheDr1ver** [crits/crits#465]
I noticed when attempting to upload an email (.msg or .eml) via the API, and passing it the associated 'ticket' number, rather than adding a ticket number to the Email TLO, CRITs creates a bogus campaign using the given ticket number and relates the email to that campaign instead. 

Afterwards, when visiting the list of available campaigns, CRITs gives an error indicating an invalid schema number. At this point, CRITs will not display the campaign list until the newly-created, invalid campaign is manually removed from the mongodb.

My install was cloned from the master branch on April 6th.

**Comment by mgoffin** [comment]
None of the email handlers allow for adding a ticket when you upload a new email, thus the API doesn't allow for it. You'd have to show me your API call because the only way I can see this happening is you passing in a ticket as a campaign.

**Comment by TheDr1ver** [comment]
Yes, I later noticed that tickets were not included in the handler (though I assumed they were universal based on the API documentation).

I also though it was strange that the campaign was being added that way, as I never pass a campaign attribute in my calls. The final POST for .eml and .msg files contains the following attributes:

type, source, ticket, filedata, and upload_type

Source is here: https://github.com/TheDr1ver/WIPSTER/blob/master/func/crits.php#L223

**Comment by mgoffin** [comment]
Yea, the docs say "common across most" which doesn't tell you very much. We should be more explicit and also just support tickets across the board if we're going to do that.
