### ISSUE TITLE
CSRF protection is broken

### ISSUE THREAD

**Issue by frbapolkosnik** [crits/crits#467]
CRITs instance running on Apache becomes unusable, 304 and 403 messages show up in apache's access log and error log is peppered with:
[Mon Apr 27 17:26:52 2015] [error] 7591 WARNING: Forbidden (CSRF cookie not set.): /items/editor/
Mon Apr 27 17:26:55 2015] [error] 6956 WARNING: Forbidden (CSRF cookie not set.): /services/list/
[Mon Apr 27 17:40:38 2015] [error] 6960 WARNING: Forbidden (CSRF cookie not set.): /notifications/poll/
[Mon Apr 27 17:41:56 2015] [error] 162437 WARNING: Forbidden (CSRF cookie not set.): /login/

**Comment by mgoffin** [comment]
@dsnellgrove any ideas on this? We don't run master in prod so I don't want to give it a test there :)

**Comment by dsnellgrove** [comment]
It doesn't require apache to recreate the issue with /login/, there's a missing token from the login template. I'll try to recreate the other views' issues as well. Building PR shortly.

**Comment by dsnellgrove** [comment]
Not sure how to trigger the notifications (I never use the feature). Other URLs work though
```
[28/Apr/2015 07:44:25] "POST /services/list/ HTTP/1.1" 200 1293
[28/Apr/2015 07:45:51] "POST /items/editor/ HTTP/1.1" 200 2102
```

**Comment by frbapolkosnik** [comment]
Testing the master today, looks like it's still broken for 

[Tue Apr 28 10:33:10 2015] [error] 7694 WARNING: Forbidden (CSRF cookie not set.): /notifications/poll/
[Tue Apr 28 10:33:11 2015] [error] 8621 WARNING: Forbidden (CSRF cookie not set.): /users/list/
[Tue Apr 28 10:33:17 2015] [error] 15266 WARNING: Forbidden (CSRF cookie not set.): /audit/list/
[Tue Apr 28 10:33:22 2015] [error] 19904 WARNING: Forbidden (CSRF cookie not set.): /items/editor/
