### ISSUE TITLE
AttributeError: 'WSGIRequest' object has no attribute 'user'

### ISSUE THREAD

**Issue by sdsponger** [crits/crits#475]
Things were up and running fine, but as soon as I added the crits_services dir and restarted apache2, I haven't been able to log back into the GUI.  It just throws a 500 Internal Server Error. 

My apache2 error.log and crits.log are below.

Thanks for the help on this!

tail -f /var/log/apache2/error.log 
[Thu Apr 30 12:23:39.670593 2015] [:error] [pid 944:tid 140586032006912]
[client 192.168.100.101:64491]     resolver, sys.exc_info())
[Thu Apr 30 12:23:39.670603 2015] [:error] [pid 944:tid 140586032006912]
[client 192.168.100.101:64491]   File
"/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line
236, in handle_uncaught_exception [Thu Apr 30 12:23:39.670660 2015] [:error]
[pid 944:tid 140586032006912]
[client 192.168.100.101:64491]     return callback(request, **param_dict)
[Thu Apr 30 12:23:39.670683 2015] [:error] [pid 944:tid 140586032006912]
[client 192.168.100.101:64491]   File "/data/crits/crits/core/errors.py",
line 17, in custom_500
[Thu Apr 30 12:23:39.670701 2015] [:error] [pid 944:tid 140586032006912]
[client 192.168.100.101:64491]     RequestContext(request))
[Thu Apr 30 12:23:39.670712 2015] [:error] [pid 944:tid 140586032006912]
[client 192.168.100.101:64491]   File
"/usr/local/lib/python2.7/dist-packages/django/template/context.py", line
169, in __init__ [Thu Apr 30 12:23:39.670727 2015] [:error] [pid 944:tid
140586032006912]
[client 192.168.100.101:64491]     self.update(processor(request))
[Thu Apr 30 12:23:39.670737 2015] [:error] [pid 944:tid 140586032006912]
[client 192.168.100.101:64491]   File "/data/crits/crits/core/views.py",
line 1056, in base_context
[Thu Apr 30 12:23:39.670751 2015] [:error] [pid 944:tid 140586032006912]
[client 192.168.100.101:64491]     if request.user.is_authenticated():
[Thu Apr 30 12:23:39.670767 2015] [:error] [pid 944:tid 140586032006912]
[client 192.168.100.101:64491] AttributeError: 'WSGIRequest' object has no
attribute 'user'

tail -f /data/crits/logs/crits.log
WARNING 2015-04-30 13:00:03,754 crits.services.core Failed to import service (shodan_service): No module named shodan
WARNING 2015-04-30 13:00:03,756 crits.services.core Failed to import service (pyinstaller_service): No module named PyInstaller.cliutils.archive_viewer
WARNING 2015-04-30 13:00:03,756 crits.services.core Failed to import service (unswf_service): No module named pylzma
WARNING 2015-04-30 13:00:03,758 crits.services.core Failed to import service (pdfinfo_service): No module named numpy
WARNING 2015-04-30 13:00:03,759 crits.services.core Failed to import service (chminfo_service): No module named chm
WARNING 2015-04-30 13:00:03,767 crits.services.core Failed to import service (shodan_service): No module named shodan
WARNING 2015-04-30 13:00:03,769 crits.services.core Failed to import service (pyinstaller_service): No module named PyInstaller.cliutils.archive_viewer
WARNING 2015-04-30 13:00:03,769 crits.services.core Failed to import service (unswf_service): No module named pylzma
WARNING 2015-04-30 13:00:03,771 crits.services.core Failed to import service (pdfinfo_service): No module named numpy
WARNING 2015-04-30 13:00:03,772 crits.services.core Failed to import service (chminfo_service): No module named chm

**Comment by mgoffin** [comment]
If you are going to install all of the services, you need to install all of the dependencies.

**Comment by sdsponger** [comment]
Roger...Noob question here then, if I don't want to run all the services atm, what's the best practice to disable?  Just move out of the crits_services directory?

Thanks

**Comment by mgoffin** [comment]
basically that, or if you'd rather, you can point to a different directory and copy only the services you want into there.

**Comment by sdsponger** [comment]
Thanks, working this now for the services bombing in my crits.log.  Once done I'll bounce apache2 and report back.  Thanks!

**Comment by gtback** [comment]
@mgoffin: The service import warnings are definitely annoying, and removing the offending services entirely is the best solution, but does that actually explain the `AttributeError: 'WSGIRequest' object has no attribute 'user'`?

@sdsponger: are there any other lines above that in the log file which are otherwise informative?

**CAVEAT**: It's been a *LONG* time since I've been involved with the service code; it's entirely possible that something changed any my questions are meaningless.

**Comment by mgoffin** [comment]
@gtback Removing the errors to clean things up. I suspect right now seeing one error and all the others makes the whole thing look like a mess.

I'm also wanting to get all of that cleaned up since it was noted this only started after installing services. Could be a red herring but I've seen crazier things :)

**Comment by sdsponger** [comment]
@gtback Nope, those are the only lines, they just repeat in their respective logs after each apache2 bounce I've done and subsequent page refresh.  In the process of installing all dependencies for the services I want to use and moving the others to another directory.

**Comment by markmaunu** [comment]
I am seeing the exact same issue this morning after doing a git pull for 4-stable. 

AttributeError: 'WSGIRequest' object has no attribute 'user'?

**Comment by dsnellgrove** [comment]
I wonder if your allowed_hosts setting is set correctly

**Comment by sdsponger** [comment]
@dsnellgrove I have mine set to our domain and had no issue logging before activating the services directory.  I'll be looking at all dependencies today, so will report back later.

**Comment by sdsponger** [comment]
Just wanted to update things here...I've installed service dependencies and no longer receive any import errors in my crits.log file.  However, I'm still unable to log into the GUI (500 Internal Server Error) and get the attribute error in my apache error.log

crits@essorgcrits:~$ sudo tail -f /var/log/apache2/error.log
[Fri May 01 13:06:14.172753 2015] [:error] [pid 999:tid 140393328920320] [client 192.168.100.101:61242]     resolver, sys.exc_info())
[Fri May 01 13:06:14.172765 2015] [:error] [pid 999:tid 140393328920320] [client 192.168.100.101:61242]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 236, in handle_uncaught_exception
[Fri May 01 13:06:14.172783 2015] [:error] [pid 999:tid 140393328920320] [client 192.168.100.101:61242]     return callback(request, **param_dict)
[Fri May 01 13:06:14.172795 2015] [:error] [pid 999:tid 140393328920320] [client 192.168.100.101:61242]   File "/data/crits/crits/core/errors.py", line 17, in custom_500
[Fri May 01 13:06:14.172813 2015] [:error] [pid 999:tid 140393328920320] [client 192.168.100.101:61242]     RequestContext(request))
[Fri May 01 13:06:14.172826 2015] [:error] [pid 999:tid 140393328920320] [client 192.168.100.101:61242]   File "/usr/local/lib/python2.7/dist-packages/django/template/context.py", line 169, in __init__
[Fri May 01 13:06:14.172842 2015] [:error] [pid 999:tid 140393328920320] [client 192.168.100.101:61242]     self.update(processor(request))
[Fri May 01 13:06:14.172854 2015] [:error] [pid 999:tid 140393328920320] [client 192.168.100.101:61242]   File "/data/crits/crits/core/views.py", line 1056, in base_context
[Fri May 01 13:06:14.172870 2015] [:error] [pid 999:tid 140393328920320] [client 192.168.100.101:61242]     if request.user.is_authenticated():
[Fri May 01 13:06:14.172887 2015] [:error] [pid 999:tid 140393328920320] [client 192.168.100.101:61242] AttributeError: 'WSGIRequest' object has no attribute 'user'

**Comment by mgoffin** [comment]
I suspect you did more than start using crits_services, or you did so in the wrong way. How did you start using the services?

**Comment by sdsponger** [comment]
I added the crits_services directory via the GUI, not this way:  python manage.py setconfig service_dirs "/data/crits_services"

Can I use the manage.py setconfig to take that setting out and bring it back to the default?

The only other changes I made prior to being locked out was to add a couple of sources, change my timezone, added allowed_host (my domain) and changed my password.  I never received any kind of error for those when the changes were applied.

**Comment by markmaunu** [comment]
So I had a working 4_master with a working crits_services up until a few days ago when I did a git pull of crits and crits_services. Everything was working correctly and I had been running maltrieve and sending those samples for domains and IPs from where they were downloaded into the same crits.

I've just vleared my error.log for apache and restarted it and I get the same 500 error when logging into the main page. Fresh apache logs below after restart of apache:

crits@ubuntu:/var/log/apache2$ cat /var/log/apache2/error.log
[Fri May 01 15:46:32.944067 2015] [ssl:warn] [pid 10363:tid 139838406178688] AH01909: RSA certificate configured for 127.0.1.1:443 does NOT include an ID which matches the server name
[Fri May 01 15:46:32.951465 2015] [ssl:warn] [pid 10364:tid 139838406178688] AH01909: RSA certificate configured for 127.0.1.1:443 does NOT include an ID which matches the server name
[Fri May 01 15:46:32.952192 2015] [mpm_event:notice] [pid 10364:tid 139838406178688] AH00489: Apache/2.4.7 (Ubuntu) OpenSSL/1.0.1f mod_wsgi/3.4 Python/2.7.6 configured -- resuming normal operations
[Fri May 01 15:46:32.952219 2015] [core:notice] [pid 10364:tid 139838406178688] AH00094: Command line: '/usr/sbin/apache2'
[Fri May 01 15:51:06.251981 2015] [:error] [pid 10368:tid 139838292113152] /usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py:1225: UserWarning: /tmp is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
[Fri May 01 15:51:06.252013 2015] [:error] [pid 10368:tid 139838292113152]   warnings.warn(msg, UserWarning)
fatal: Not a git repository (or any of the parent directories): .git
[Fri May 01 15:51:08.493750 2015] [:error] [pid 10368:tid 139838292113152] 2440 DEBUG: Found service subclass: cuckoo version 1.0.2
[Fri May 01 15:51:08.493865 2015] [:error] [pid 10368:tid 139838292113152] 2440 DEBUG: Registering Service cuckoo
[Fri May 01 15:51:08.500375 2015] [:error] [pid 10368:tid 139838292113152] 2446 DEBUG: Found service subclass: pdfinfo version 1.2.0
[Fri May 01 15:51:08.500467 2015] [:error] [pid 10368:tid 139838292113152] 2447 DEBUG: Registering Service pdfinfo
[Fri May 01 15:51:08.502039 2015] [:error] [pid 10368:tid 139838292113152] 2448 DEBUG: Found service subclass: meta_checker version 1.0.2
[Fri May 01 15:51:08.502108 2015] [:error] [pid 10368:tid 139838292113152] 2448 DEBUG: Registering Service meta_checker
[Fri May 01 15:51:08.503647 2015] [:error] [pid 10368:tid 139838292113152] 2450 DEBUG: Found service subclass: MetaCap version 0.0.2
[Fri May 01 15:51:08.503719 2015] [:error] [pid 10368:tid 139838292113152] 2450 DEBUG: Registering Service MetaCap
[Fri May 01 15:51:08.506016 2015] [:error] [pid 10368:tid 139838292113152] 2452 DEBUG: Found service subclass: passivetotal_lookup version 1.0.0
[Fri May 01 15:51:08.506145 2015] [:error] [pid 10368:tid 139838292113152] 2452 DEBUG: Registering Service passivetotal_lookup
[Fri May 01 15:51:08.508747 2015] [:error] [pid 10368:tid 139838292113152] 2455 DEBUG: Found service subclass: stix_validator_service version 0.0.1
[Fri May 01 15:51:08.508844 2015] [:error] [pid 10368:tid 139838292113152] 2455 DEBUG: Registering Service stix_validator_service
[Fri May 01 15:51:08.510560 2015] [:error] [pid 10368:tid 139838292113152] 2457 DEBUG: Found service subclass: opendns_investigate version 1.0.0
[Fri May 01 15:51:08.510645 2015] [:error] [pid 10368:tid 139838292113152] 2457 DEBUG: Registering Service opendns_investigate
[Fri May 01 15:51:08.579792 2015] [:error] [pid 10368:tid 139838292113152] 2526 DEBUG: Found service subclass: ChopShop version 0.0.5
[Fri May 01 15:51:08.579907 2015] [:error] [pid 10368:tid 139838292113152] 2526 DEBUG: Registering Service ChopShop
[Fri May 01 15:51:08.581657 2015] [:error] [pid 10368:tid 139838292113152] 2528 DEBUG: Found service subclass: Pyew version 0.0.1
[Fri May 01 15:51:08.581736 2015] [:error] [pid 10368:tid 139838292113152] 2528 DEBUG: Registering Service Pyew
[Fri May 01 15:51:08.584228 2015] [:error] [pid 10368:tid 139838292113152] 2530 DEBUG: Found service subclass: ssdeep_compare version 1.0.2
[Fri May 01 15:51:08.584308 2015] [:error] [pid 10368:tid 139838292113152] 2530 DEBUG: Registering Service ssdeep_compare
[Fri May 01 15:51:08.585800 2015] [:error] [pid 10368:tid 139838292113152] 2532 DEBUG: Found service subclass: totalhash version 0.1.0
[Fri May 01 15:51:08.585871 2015] [:error] [pid 10368:tid 139838292113152] 2532 DEBUG: Registering Service totalhash
[Fri May 01 15:51:08.589788 2015] [:error] [pid 10368:tid 139838292113152] 2535 DEBUG: Found service subclass: relationships_service version 0.0.2
[Fri May 01 15:51:08.589915 2015] [:error] [pid 10368:tid 139838292113152] 2536 DEBUG: Registering Service relationships_service
[Fri May 01 15:51:08.591705 2015] [:error] [pid 10368:tid 139838292113152] 2538 DEBUG: Found service subclass: unswf version 0.0.2
[Fri May 01 15:51:08.591790 2015] [:error] [pid 10368:tid 139838292113152] 2538 DEBUG: Registering Service unswf
[Fri May 01 15:51:08.595423 2015] [:error] [pid 10368:tid 139838292113152] 2542 DEBUG: Found service subclass: farsight_lookup version 1.0.0
[Fri May 01 15:51:08.595568 2015] [:error] [pid 10368:tid 139838292113152] 2542 DEBUG: Registering Service farsight_lookup
[Fri May 01 15:51:08.597995 2015] [:error] [pid 10368:tid 139838292113152] 2544 DEBUG: Found service subclass: threatrecon_lookup version 1.0.0
[Fri May 01 15:51:08.598076 2015] [:error] [pid 10368:tid 139838292113152] 2544 DEBUG: Registering Service threatrecon_lookup
[Fri May 01 15:51:08.599955 2015] [:error] [pid 10368:tid 139838292113152] 2546 DEBUG: Found service subclass: zip_meta version 1.0.0
[Fri May 01 15:51:08.600033 2015] [:error] [pid 10368:tid 139838292113152] 2546 DEBUG: Registering Service zip_meta
[Fri May 01 15:51:08.601517 2015] [:error] [pid 10368:tid 139838292113152] 2548 DEBUG: Found service subclass: shodan_lookup version 1.0.0
[Fri May 01 15:51:08.601588 2015] [:error] [pid 10368:tid 139838292113152] 2548 DEBUG: Registering Service shodan_lookup
[Fri May 01 15:51:08.603262 2015] [:error] [pid 10368:tid 139838292113152] 2549 DEBUG: Found service subclass: virustotal_lookup version 3.1.0
[Fri May 01 15:51:08.603406 2015] [:error] [pid 10368:tid 139838292113152] 2549 DEBUG: Registering Service virustotal_lookup
[Fri May 01 15:51:08.606680 2015] [:error] [pid 10368:tid 139838292113152] 2553 DEBUG: Found service subclass: anb version 0.0.1
[Fri May 01 15:51:08.606783 2015] [:error] [pid 10368:tid 139838292113152] 2553 DEBUG: Registering Service anb
[Fri May 01 15:51:08.609441 2015] [:error] [pid 10368:tid 139838292113152] 2556 DEBUG: Found service subclass: DataMiner version 1.0.0
[Fri May 01 15:51:08.609535 2015] [:error] [pid 10368:tid 139838292113152] 2556 DEBUG: Registering Service DataMiner
[Fri May 01 15:51:08.611304 2015] [:error] [pid 10368:tid 139838292113152] 2557 DEBUG: Found service subclass: office_meta version 1.0.2
[Fri May 01 15:51:08.611383 2015] [:error] [pid 10368:tid 139838292113152] 2558 DEBUG: Registering Service office_meta
[Fri May 01 15:51:08.612946 2015] [:error] [pid 10368:tid 139838292113152] 2559 DEBUG: Found service subclass: machoinfo version 0.0.1
[Fri May 01 15:51:08.613021 2015] [:error] [pid 10368:tid 139838292113152] 2559 DEBUG: Registering Service machoinfo
[Fri May 01 15:51:08.614531 2015] [:error] [pid 10368:tid 139838292113152] 2561 DEBUG: Found service subclass: peinfo version 1.1.3
[Fri May 01 15:51:08.614600 2015] [:error] [pid 10368:tid 139838292113152] 2561 DEBUG: Registering Service peinfo
[Fri May 01 15:51:08.616152 2015] [:error] [pid 10368:tid 139838292113152] 2562 DEBUG: Found service subclass: taxii_service version 2.0.1
[Fri May 01 15:51:08.616219 2015] [:error] [pid 10368:tid 139838292113152] 2562 DEBUG: Registering Service taxii_service
[Fri May 01 15:51:08.618985 2015] [:error] [pid 10368:tid 139838292113152] 2565 DEBUG: Found service subclass: entropycalc version 0.0.1
[Fri May 01 15:51:08.619059 2015] [:error] [pid 10368:tid 139838292113152] 2565 DEBUG: Registering Service entropycalc
[Fri May 01 15:51:08.620855 2015] [:error] [pid 10368:tid 139838292113152] 2567 DEBUG: Found service subclass: threatgrid version 1.0.0
[Fri May 01 15:51:08.620934 2015] [:error] [pid 10368:tid 139838292113152] 2567 DEBUG: Registering Service threatgrid
[Fri May 01 15:51:08.624153 2015] [:error] [pid 10368:tid 139838292113152] 2570 DEBUG: Found service subclass: clamd version 0.0.3
[Fri May 01 15:51:08.624251 2015] [:error] [pid 10368:tid 139838292113152] 2570 DEBUG: Registering Service clamd
[Fri May 01 15:51:08.628106 2015] [:error] [pid 10368:tid 139838292113152] 2574 DEBUG: Found service subclass: whois version 1.0.0
[Fri May 01 15:51:08.628223 2015] [:error] [pid 10368:tid 139838292113152] 2574 DEBUG: Registering Service whois
[Fri May 01 15:51:08.630453 2015] [:error] [pid 10368:tid 139838292113152] 2577 DEBUG: Found service subclass: timeline_service version 0.0.1
[Fri May 01 15:51:08.630534 2015] [:error] [pid 10368:tid 139838292113152] 2577 DEBUG: Registering Service timeline_service
[Fri May 01 15:51:08.632178 2015] [:error] [pid 10368:tid 139838292113152] 2578 DEBUG: Found service subclass: chminfo version 1.0.0
[Fri May 01 15:51:08.632251 2015] [:error] [pid 10368:tid 139838292113152] 2578 DEBUG: Registering Service chminfo
[Fri May 01 15:51:08.633705 2015] [:error] [pid 10368:tid 139838292113152] 2580 DEBUG: Found service subclass: pyinstaller version 0.0.1
[Fri May 01 15:51:08.633774 2015] [:error] [pid 10368:tid 139838292113152] 2580 DEBUG: Registering Service pyinstaller
[Fri May 01 15:51:08.635219 2015] [:error] [pid 10368:tid 139838292113152] 2581 DEBUG: Found service subclass: upx version 1.0.2
[Fri May 01 15:51:08.635289 2015] [:error] [pid 10368:tid 139838292113152] 2581 DEBUG: Registering Service upx
[Fri May 01 15:51:08.637028 2015] [:error] [pid 10368:tid 139838292113152] 2583 DEBUG: Found service subclass: carver version 0.0.1
[Fri May 01 15:51:08.637099 2015] [:error] [pid 10368:tid 139838292113152] 2583 DEBUG: Registering Service carver
[Fri May 01 15:51:08.638745 2015] [:error] [pid 10368:tid 139838292113152] 2585 DEBUG: Found service subclass: yara version 2.0.1
[Fri May 01 15:51:08.638830 2015] [:error] [pid 10368:tid 139838292113152] 2585 DEBUG: Registering Service yara
[Fri May 01 15:51:08.677693 2015] [:error] [pid 10368:tid 139838292113152] 2624 DEBUG: Found service subclass: OPSWAT version 1.0.0
[Fri May 01 15:51:08.677793 2015] [:error] [pid 10368:tid 139838292113152] 2624 DEBUG: Registering Service OPSWAT
[Fri May 01 15:51:08.680073 2015] [:error] [pid 10368:tid 139838292113152] 2626 DEBUG: Found service subclass: diffie version 0.0.1
[Fri May 01 15:51:08.680143 2015] [:error] [pid 10368:tid 139838292113152] 2626 DEBUG: Registering Service diffie
[Fri May 01 15:51:08.681616 2015] [:error] [pid 10368:tid 139838292113152] 2628 DEBUG: Found service subclass: snugglefish_service version 0.3
[Fri May 01 15:51:08.681691 2015] [:error] [pid 10368:tid 139838292113152] 2628 DEBUG: Registering Service snugglefish_service
[Fri May 01 15:51:08.863477 2015] [:error] [pid 10368:tid 139838292113152] 2809 ERROR: Internal Server Error: /
[Fri May 01 15:51:08.863504 2015] [:error] [pid 10368:tid 139838292113152] Traceback (most recent call last):
[Fri May 01 15:51:08.863507 2015] [:error] [pid 10368:tid 139838292113152]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 180, in get_response
[Fri May 01 15:51:08.863510 2015] [:error] [pid 10368:tid 139838292113152]     response = callback(request, **param_dict)
[Fri May 01 15:51:08.863513 2015] [:error] [pid 10368:tid 139838292113152]   File "/data/crits/crits/core/errors.py", line 32, in custom_400
[Fri May 01 15:51:08.863516 2015] [:error] [pid 10368:tid 139838292113152]     RequestContext(request))
[Fri May 01 15:51:08.863518 2015] [:error] [pid 10368:tid 139838292113152]   File "/usr/local/lib/python2.7/dist-packages/django/template/context.py", line 169, in __init__
[Fri May 01 15:51:08.863521 2015] [:error] [pid 10368:tid 139838292113152]     self.update(processor(request))
[Fri May 01 15:51:08.863523 2015] [:error] [pid 10368:tid 139838292113152]   File "/data/crits/crits/core/views.py", line 1056, in base_context
[Fri May 01 15:51:08.863526 2015] [:error] [pid 10368:tid 139838292113152]     if request.user.is_authenticated():
[Fri May 01 15:51:08.863529 2015] [:error] [pid 10368:tid 139838292113152] AttributeError: 'WSGIRequest' object has no attribute 'user'
[Fri May 01 15:51:08.863683 2015] [:error] [pid 10368:tid 139838292113152] 2810 DEBUG: ['Traceback (most recent call last):\\n', '  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 180, in get_response\\n    response = callback(request, **param_dict)\\n', '  File "/data/crits/crits/core/errors.py", line 32, in custom_400\\n    RequestContext(request))\\n', '  File "/usr/local/lib/python2.7/dist-packages/django/template/context.py", line 169, in __init__\\n    self.update(processor(request))\\n', '  File "/data/crits/crits/core/views.py", line 1056, in base_context\\n    if request.user.is_authenticated():\\n', "AttributeError: 'WSGIRequest' object has no attribute 'user'\\n"]
[Fri May 01 15:51:08.865258 2015] [:error] [pid 10368:tid 139838292113152] [client 127.0.0.1:39226] mod_wsgi (pid=10368): Exception occurred processing WSGI script '/data/crits/django.wsgi'.
[Fri May 01 15:51:08.865279 2015] [:error] [pid 10368:tid 139838292113152] [client 127.0.0.1:39226] Traceback (most recent call last):
[Fri May 01 15:51:08.865293 2015] [:error] [pid 10368:tid 139838292113152] [client 127.0.0.1:39226]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 206, in __call__
[Fri May 01 15:51:08.865362 2015] [:error] [pid 10368:tid 139838292113152] [client 127.0.0.1:39226]     response = self.get_response(request)
[Fri May 01 15:51:08.865375 2015] [:error] [pid 10368:tid 139838292113152] [client 127.0.0.1:39226]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in get_response
[Fri May 01 15:51:08.865390 2015] [:error] [pid 10368:tid 139838292113152] [client 127.0.0.1:39226]     resolver, sys.exc_info())
[Fri May 01 15:51:08.865400 2015] [:error] [pid 10368:tid 139838292113152] [client 127.0.0.1:39226]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 236, in handle_uncaught_exception
[Fri May 01 15:51:08.865413 2015] [:error] [pid 10368:tid 139838292113152] [client 127.0.0.1:39226]     return callback(request, **param_dict)
[Fri May 01 15:51:08.865421 2015] [:error] [pid 10368:tid 139838292113152] [client 127.0.0.1:39226]   File "/data/crits/crits/core/errors.py", line 17, in custom_500
[Fri May 01 15:51:08.865434 2015] [:error] [pid 10368:tid 139838292113152] [client 127.0.0.1:39226]     RequestContext(request))
[Fri May 01 15:51:08.865443 2015] [:error] [pid 10368:tid 139838292113152] [client 127.0.0.1:39226]   File "/usr/local/lib/python2.7/dist-packages/django/template/context.py", line 169, in __init__
[Fri May 01 15:51:08.865455 2015] [:error] [pid 10368:tid 139838292113152] [client 127.0.0.1:39226]     self.update(processor(request))
[Fri May 01 15:51:08.865463 2015] [:error] [pid 10368:tid 139838292113152] [client 127.0.0.1:39226]   File "/data/crits/crits/core/views.py", line 1056, in base_context
[Fri May 01 15:51:08.865475 2015] [:error] [pid 10368:tid 139838292113152] [client 127.0.0.1:39226]     if request.user.is_authenticated():
[Fri May 01 15:51:08.865487 2015] [:error] [pid 10368:tid 139838292113152] [client 127.0.0.1:39226] AttributeError: 'WSGIRequest' object has no attribute 'user'

**Comment by sdsponger** [comment]
Wanted to follow-up here.  Anyways, I spun up a new VM this AM, used the bootstrap script, installed the correct mongoengine, followed the production directions and was able to get things installed with no issues.  I've only logged in to verify I could and haven't done anything else yet.

This doesn't explain Mark's issue though

Damon

**Comment by sdsponger** [comment]
I totally jinxed myself...Just logged in and made the following changes in the GUI--unchecked debug, filled in crits email, changed timezone and added my instance url.  All of these required apache to be bounced, so I issued "sudo service apache2 restart"

Now I'm right back at the 500 internal server error screen, can't log in and see the same stuff in the apache error.log.  My crits.log file is empty...


[Sun May 03 20:48:24.205695 2015] [:error] [pid 13535:tid 140565505054464] [client 192.168.99.105:60028] mod_wsgi (pid=13535): Exception occurred processing WSGI script '/data/crits/django.wsgi'.

[Sun May 03 20:48:24.205765 2015] [:error] [pid 13535:tid 140565505054464] [client 192.168.99.105:60028] Traceback (most recent call last):

[Sun May 03 20:48:24.205792 2015] [:error] [pid 13535:tid 140565505054464] [client 192.168.99.105:60028]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 206, in __call__

[Sun May 03 20:48:24.205843 2015] [:error] [pid 13535:tid 140565505054464] [client 192.168.99.105:60028]     response = self.get_response(request)

[Sun May 03 20:48:24.205858 2015] [:error] [pid 13535:tid 140565505054464] [client 192.168.99.105:60028]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in get_response

[Sun May 03 20:48:24.205876 2015] [:error] [pid 13535:tid 140565505054464] [client 192.168.99.105:60028]     resolver, sys.exc_info())

[Sun May 03 20:48:24.205887 2015] [:error] [pid 13535:tid 140565505054464] [client 192.168.99.105:60028]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 236, in handle_uncaught_exception

[Sun May 03 20:48:24.205903 2015] [:error] [pid 13535:tid 140565505054464] [client 192.168.99.105:60028]     return callback(request, **param_dict)

[Sun May 03 20:48:24.205913 2015] [:error] [pid 13535:tid 140565505054464] [client 192.168.99.105:60028]   File "/data/crits/crits/core/errors.py", line 17, in custom_500

[Sun May 03 20:48:24.205933 2015] [:error] [pid 13535:tid 140565505054464] [client 192.168.99.105:60028]     RequestContext(request))

[Sun May 03 20:48:24.205944 2015] [:error] [pid 13535:tid 140565505054464] [client 192.168.99.105:60028]   File "/usr/local/lib/python2.7/dist-packages/django/template/context.py", line 169, in __init__

[Sun May 03 20:48:24.205962 2015] [:error] [pid 13535:tid 140565505054464] [client 192.168.99.105:60028]     self.update(processor(request))

[Sun May 03 20:48:24.205972 2015] [:error] [pid 13535:tid 140565505054464] [client 192.168.99.105:60028]   File "/data/crits/crits/core/views.py", line 1056, in base_context

[Sun May 03 20:48:24.205988 2015] [:error] [pid 13535:tid 140565505054464] [client 192.168.99.105:60028]     if request.user.is_authenticated():

[Sun May 03 20:48:24.206006 2015] [:error] [pid 13535:tid 140565505054464] [client 192.168.99.105:60028] AttributeError: 'WSGIRequest' object has no attribute 'user'

**Comment by packet-rat** [comment]
Try zapping the instance URL (I knew i'd seen this error before).

On May 3, 2015, at 11:59 PM, sdsponger <notifications@github.com> wrote:

I totally jinxed myself...Just logged in and made the following changes in the GUI--unchecked debug, filled in crits email, changed timezone and added my instance url. All of these required apache to be bounced, so I issued "sudo service apache2 restart"

Now I'm right back at the 500 internal server error screen, can't log in and see the same stuff in the apache error.log. My crits.log file is empty...

[Sun May 03 20:48:24.205695 2015] [:error] [pid 13535:tid 140565505054464] [client 192.168.99.105:60028] mod_wsgi (pid=13535): Exception occurred processing WSGI script '/data/crits/django.wsgi'.

[Sun May 03 20:48:24.205765 2015] [:error] [pid 13535:tid 140565505054464] [client 192.168.99.105:60028] Traceback (most recent call last):

[Sun May 03 20:48:24.205792 2015] [:error] [pid 13535:tid 140565505054464] [client 192.168.99.105:60028] File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 206, in call

[Sun May 03 20:48:24.205843 2015] [:error] [pid 13535:tid 140565505054464] [client 192.168.99.105:60028] response = self.get_response(request)

[Sun May 03 20:48:24.205858 2015] [:error] [pid 13535:tid 140565505054464] [client 192.168.99.105:60028] File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in get_response

[Sun May 03 20:48:24.205876 2015] [:error] [pid 13535:tid 140565505054464] [client 192.168.99.105:60028] resolver, sys.exc_info())

[Sun May 03 20:48:24.205887 2015] [:error] [pid 13535:tid 140565505054464] [client 192.168.99.105:60028] File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 236, in handle_uncaught_exception

[Sun May 03 20:48:24.205903 2015] [:error] [pid 13535:tid 140565505054464] [client 192.168.99.105:60028] return callback(request, **param_dict)

[Sun May 03 20:48:24.205913 2015] [:error] [pid 13535:tid 140565505054464] [client 192.168.99.105:60028] File "/data/crits/crits/core/errors.py", line 17, in custom_500

[Sun May 03 20:48:24.205933 2015] [:error] [pid 13535:tid 140565505054464] [client 192.168.99.105:60028] RequestContext(request))

[Sun May 03 20:48:24.205944 2015] [:error] [pid 13535:tid 140565505054464] [client 192.168.99.105:60028] File "/usr/local/lib/python2.7/dist-packages/django/template/context.py", line 169, in init

[Sun May 03 20:48:24.205962 2015] [:error] [pid 13535:tid 140565505054464] [client 192.168.99.105:60028] self.update(processor(request))

[Sun May 03 20:48:24.205972 2015] [:error] [pid 13535:tid 140565505054464] [client 192.168.99.105:60028] File "/data/crits/crits/core/views.py", line 1056, in base_context

[Sun May 03 20:48:24.205988 2015] [:error] [pid 13535:tid 140565505054464] [client 192.168.99.105:60028] if request.user.is_authenticated():

[Sun May 03 20:48:24.206006 2015] [:error] [pid 13535:tid 140565505054464] [client 192.168.99.105:60028] AttributeError: 'WSGIRequest' object has no attribute 'user'

**Comment by mgoffin** [comment]
If it's that that is causing the problem id assume you are entering an
invalid instance URL and should check the django docs.

**Comment by sdsponger** [comment]
Thanks

In the meantime, is there a way to fix/rollback or will I have to roll back
to my working VM snapshot?

**Comment by dsnellgrove** [comment]
Turn DEBUG back on. If this resolves your error than the issue is very likely your allowed_host setting (which is ignored when DEBUG is enabled) or a similar item.

**Comment by sdsponger** [comment]
Can you please let me know how to turn it back on since I can't log into
the GUI. Thanks!

**Comment by mgoffin** [comment]
https://github.com/crits/crits/wiki/Production-grade-CRITs-install#optional-configure-crits-via-management-command

**Comment by sdsponger** [comment]
Thanks...Back in after turning debug back on.  I'll review syntax on my allowed hosts and url

**Comment by sdsponger** [comment]
I'm all good and have been stable since getting my config reset.  Not sure about Mark, but you can close this from my end.

Thanks again for all the help
Damon

**Comment by apolkosnik** [comment]
I ran into this AttributeError when transplanting the database from another
instance of CRITs, after changing the config setting for "allowed_hosts" to
the default value through mongo shell it went away.
