### ISSUE TITLE
Can't Save Service API Key

### ISSUE THREAD

**Issue by sdsponger** [crits/crits#488]
I've added a couple services and they populate as "misconfigured" under the services menu.  I go into each service to add my respective API key, upon hitting submit, I get the error below (debug output).  Is there a fix/workaround for this?  I'd like to get these services running.

Thanks
Damon

Forbidden (403)
CSRF verification failed. Request aborted.
Help
Reason given for failure:
    CSRF token missing or incorrect.
    
In general, this can occur when there is a genuine Cross Site Request Forgery, or when Django's CSRF mechanism has not been used correctly. For POST forms, you need to ensure:
Your browser is accepting cookies.
The view function uses RequestContext for the template, instead of Context.
In the template, there is a {% csrf_token %} template tag inside each POST form that targets an internal URL.
If you are not using CsrfViewMiddleware, then you must use csrf_protect on any views that use the csrf_token template tag, as well as those that accept the POST data.
You're seeing the help section of this page because you have DEBUG = True in your Django settings file. Change that to False, and only the initial error message will be displayed.
You can customize this page using the CSRF_FAILURE_VIEW setting.

**Comment by sdsponger** [comment]
Same for me, multiple browsers on multiple machines.
I saw Kyle's post, but have no idea how to "ajaxify" it :)

**Comment by sdsponger** [comment]
Is there a fix or workaround for this?
Thanks!

**Comment by gbartz** [comment]
I have no issues editing service configs.  It is possible you have cached javascript and or cookies.  The simplest way to avoid this problem (and verify there is an issue) is to log in to CRITs using chrome in incognito mode.  Another useful tool to ensure a clean slate (also in chrome) is with dev tools opened, right-click on the refresh button and select "Empty Cache and Hard Reload".  Hope this helps!

**Comment by mgoffin** [comment]
This was fixed in Master.
