### ISSUE TITLE
uploading sample metadata only with SHA1

### ISSUE THREAD

**Issue by ranmit** [crits/crits#489]
Hello,
Is there any way for uploading a sample metadata (no binary attached), but also specifying its SHA1 \ SHA256, in addition to the MD5 specification ?
I see that the Crits metadata Import UI does not provide with such functionality, nor does it seem that the matching authenticated API does.
I've also tried to manipulate a STIX document to contain both types of hashes, but when uploading the STIX doc I only get the specified MD5.
can this be done in any way ?

**Comment by mgoffin** [comment]
There is an open PR for this already. Waiting on the developer to respond to some issues. See #408.

**Comment by ranmit** [comment]
missed this.
thx a lot.
