### ISSUE TITLE
Moving CybOX/STIX support to the TAXII Service

### ISSUE THREAD

**Issue by mgoffin** [crits/crits#496]
CybOX/STIX support in CRITs has always been a sore point. Some people like it but are annoyed at the lack of 100% support, others do not like the fact that they are forced to use CybOX/STIX in the first place. It's always been in our minds that we need a better way to support both types of people as well as offer a way to make CybOX/STIX version support de-coupled from core so it can be maintained "in real time" instead of on a CRITs-release basis.

My proposal is the following:

- Remove CybOX/STIX from core.
  - The "Download" feature for a TLO will revert back to JSON.
  - The STIX Import nav menu item will go away (see below).
  - The Indicator Type vocabulary will be gutted and replaced with a vocabulary we control.
  - Object Types will continue to use the same vocabulary as Indicators.
  - Relationship Types vocabulary will be gutted and replaced with a vocabulary we control.
  - The Event Types vocabulary will be gutted and replaced with a vocabulary we control.
  - Migration script to convert all Objects and Indicators to the new vocabulary.
  - The "standards" folder will be removed and any core code related to CybOX/STIX removed.
  - The CRITs API "format=stix" will go away.

- Add CybOX/STIX to TAXII Service
  - The STIX Import nav menu item will get added to the TAXII service.
  - The core "standards" folder will get moved over into the TAXII service and leveraged there.
  - The TAXII service will use the migrated core code to do all of the CybOX/STIX conversions.
  - The object-mapper will be in TAXII for it to convert CRITs->CybOX/STIX->CRITs.
    - Will be expanded to handle Relationship Types and Event Types.

This will give us several things:

- Those who don't want to use CybOX/STIX don't have to!
- Those who want to use CybOX/STIX can!
- CybOX/STIX support is now outside of the realm of core releases!
  - People who wish to support CybOX/STIX in CRITs can now maintain it in real time!
    - No more waiting on core developers. You can now write code to help too! :)
  - New versions of CybOX/STIX can be supported with existing CRITs installs!

This won't give us:

- The ability to add your own items to the vocabularies.
  - You can however, submit an Issue to our Github with the proposed addition and if it's approved you can then submit a PR to add that new item to the vocabulary.
    - Keep in mind this might require adding the mapping to the TAXII service if applicable!
  - We want to ensure everyone is using the same vocabulary even if we aren't a sharing platform. It makes talking about content easier when we all refer to things the same way.

The Drive to use CybOX/STIX in the project has always been sharing-specific. Now we can keep it clean and driven with that focus.

I'd like to get some feedback on this. I can be missing some details here and would like to get it ironed out. An Issue will be up on Github with the exact same content as this message so it can be discussed there as well.

Mike

**Comment by brlogan** [comment]
This probably makes quite a bit of sense and I think you did a good job of covering most the changes that would need to be made. Something you didn't explicitly say is that all the to_cybox, from_cybox, to_stix, and from_stix functions would need to be converted and moved from their respective <TLO>.py files. There's also quite a bit of code in crits_mongoengine.py

How much do you foresee types and relationships changing? As we discussed the other day, the further they are from CybOX, the more difficult things will be to share.

**Comment by mgoffin** [comment]
Yea, the `to_*` for CybOX and STIX will be going with this change.

As for the Types, Relationship Types, and Event Types, I think it would be in our best interest to have a "one-to-one" mapping of existing CybOX/STIX terms to whatever the new vocabulary is. There will be some fallout to this as I anticipate some of the features in CybOX/STIX that were there and not well supported might fall off if we determine it has little value (I'm looking at you `Windows File` and `Unix File`!).

This means that the object_mapper will get redone to accommodate the new vocabulary and mappers for the Event Types and Relationship Types will also need to be done.

**Comment by mgoffin** [comment]
`remove_cybox_stix` branch for core, and `add_cybox_stix` branch for services are pushed.

They don't change any vocabulary (we still have issues to go over for what the vocab should focus on) but the features/functionality have been migrated.

**Comment by packet-rat** [comment]
Mike,

I've not had the time to respond to your transformative proposal with the substantive details it deserves 
but do want to quickly respond to:

1) Fully endorse this change to core and how we integrate the data models.
2) Fully endorse the concept of common table driven class/methods for doing the transforms.
2) Fully endorse anything we can do to align the internal CRITs data models to the OASIS CTI conceptual models.

Hopefully this makes sense in the context of discourse around your initiative.

Patrick Maroney
Cell: (609)841-5104


On May 18, 2015, at 2:39 PM, Mike Goffin <notifications@github.com> wrote:

remove_cybox_stix branch for core, and add_cybox_stix branch for services are pushed.

They don't change any vocabulary (we still have issues to go over for what the vocab should focus on) but the features/functionality have been migrate

**Comment by mgoffin** [comment]
It does! I think you are right that we (by we I mean anyone interested in actually doing development for the standards) will be able to better align the CRITs data model to the OASIS CTI by pushing the mapping off to the service where it can be revised in real-time to keep things in check.

**Comment by gtback** [comment]
I'm guessing this can be closed since #523 was merged?

**Comment by mgoffin** [comment]
yep!
