### ISSUE TITLE
New Relationship Types Vocabulary

### ISSUE THREAD

**Issue by mgoffin** [crits/crits#502]
We need to come up with a new set of vocabulary for Relationship Types.

Currently they are based on CybOX vocabulary. They doesn't necessarily have to change if we all agree the current options are adequate. But it would mean de-coupling them from CybOX meaning it will not be updated if the CybOX vocabulary changes. If some don't seem to work well they can be removed. If there are ones we want to see that aren't listed we can add them.

The idea here is that we will maintain our own "gold standard" vocabulary that all CRITs users will have.

Related to #496

**Comment by mgoffin** [comment]
For reference:
https://github.com/crits/crits/blob/master/crits/core/management/commands/create_relationship_types.py#L27

**Comment by ckane** [comment]
FWIW I ignore the relationship type description entirely and attempt to extrapolate it through other means if necessary. So far the most significant piece of information has been "things are related" rather than the exact nature of said relationship.
