### ISSUE TITLE
New Object Type Vocabulary

### ISSUE THREAD

**Issue by mgoffin** [crits/crits#503]
We need to come up with a new set of vocabulary for Object Types.

Currently they are based on CybOX vocabulary. They doesn't necessarily have to change if we all agree the current options are adequate. But it would mean de-coupling them from CybOX meaning it will not be updated if the CybOX vocabulary changes. If some don't seem to work well they can be removed. If there are ones we want to see that aren't listed we can add them.

The idea here is that we will maintain our own "gold standard" vocabulary that all CRITs users will have.

Object Types is touchy because it handles several things:

- IP Address types
- Indicator types
- Object types

We will no longer have this awkward hyphenated interpretation of the vocabulary where things are in sub-categories based on how we parse them. 

Since we will be controlling the vocabulary we will continue to make IP Address types a proper sub-set of Object Types. I am also going to propose the following:

- Type
- Threat Type

We have had so many requests for adding context to Indicators (outside of having to fill out a description). I think adding a Threat Type vocabulary will go a long way with helping this. For example, we can have an Indicator with:

- Type: IPv4 Address
- Threat Type: Proxy IP

This gives much more information to the analyst as to what this IP was used for. I want to extend this Threat Type to objects as well. This means when you add an Object to something like a Sample, instead of just seeing a Domain, you'll get to see some context as to what the domain is used for (like being a C2, hosting a malicious binary, etc.).

Related to #496

**Comment by mgoffin** [comment]
For reference:
https://github.com/crits/crits/blob/master/crits/core/management/commands/create_object_types.py#L27

This will hopefully get cleaned up dramatically.

**Comment by dsnellgrove** [comment]
In my experience sharing is a key concern for nearly every organization that is using CRITs. Diverging from a standard that is on a strong trajectory to be THE standard would have serious consequences in terms of interoperability and sharing with other platforms, mandating a translation layer for nearly any interaction. I have deep concerns that the cons significantly outweigh the pros in a move like this.

See also http://xkcd.com/927/

**Comment by mgoffin** [comment]
I think you are missing the point of this completely :)

We aren't abandoning CybOX/STIX. Our support for it is lacking because it exists in core and keeping up with their versions can only be accomplished by releasing a new version of CRITs. We are breaking that requirement and pushing it to the TAXII service, which is currently the *only* sharing capability offered by a bolt-on (CRITs at its heart is *NOT* a sharing platform).

The vocabularies we maintain will give us full control over what is used and how it is used. We don't have to bend over backwards to compensate for the layout and object requirements for CybOX/STIX. No more random parsing of "-" in a string to determine object types and such. Mapping our vocabulary to *ANY* sharing platform and standard can be done in a service, rev'd in real time, and made available to any CRITs install that can support the service itself.

The vast majority of complaints from the community are either 1) our lack of CybOX/STIX integration, or 2) the fact that we integrate with CybOX/STIX. This solves both by not having them be a requirement to use CRITs and also giving you a way to leverage them for what they were brought into the project for: sharing.

**Comment by ckane** [comment]
I am usually lurking. However, I would like to voice my agreement with what Mike is proposing. I feel like at this time CRITs data model is attempting to simultaneously be driven by internal organizational needs to represent their biz/sec models in a storage tool and also to organize the database in such a way that it is organized to meet a single common language, which itself isn't being influenced much by the same base.

This would IMO effectively spin off the interchange-language project into two bundles: 1) per-Crits, per-interchange translator, 2) Interchange object model (stix / cybox)

I have enjoyed the flexibility of being able to define CRITs object model to my org's needs, as well as on my home instance I tinker with.

Let org's that are needing to meet specific interchange requirements build those pieces, or contribute to a smaller dev community who's focus is the open-source delivery of those pieces.

As usual, I like to break things, so my comments could be totally off base here. Props to drew for citing one of my favorite XKCD comics.

**Comment by dsnellgrove** [comment]
I still have reservations but this makes more sense now. Sometimes you do have to break things a bit to fix them.

:+1:

**Comment by Cimabue** [comment]
As someone who processes hundreds of indicators a day, it would be great to just look at an indicator and be able to quickly tell why it's there and some context, as opposed to drilling into the events, samples, emails to determine why it's there.

I would love to see something along these lines for additional attributes:

Domains:
Compromised Legit
Watering Hole
Actor Owned
Drive-by Delivery
	Adobe
	Microsoft
	Other
Download Delivery
	Payload
	Carrier
		XLS
		DOC
		PPT
		PDF
		Other
Email Sender Domain
C2 Domain

Email Addresses:
Spoofed Sender
Compromised Legit
Domain Registrant
Actor Owned
Phish
Targeting Only
Delivery - URL
Delivery - Attachment

IP Address:
Email Sender IP
Email X-Sender IP
SMTP Link
Compromised Legit
Actor Owned
Drive-by Delivery
Download Delivery
C2 IP
Scanning IP
Intrusion IP

I am sure I could go deeper, but event some high levels. What's this IP that I see in lookbacks? Oh, it's been used by "Actor X" to send email, host malware and scanning activity. Just saved me 5 minutes of digging thru other objects trying to figure out if I should be concerned or not.

**Comment by Cimabue** [comment]
And somehow being able to keep this context when exported into other CRITs (or other mechanisms) would be really cool. Currently you lose all context, so you need to re-evaluate indicators from external sources. And even the, you might not have observed the same contexts as your partner.

**Comment by Cimabue** [comment]
Addition for Domains:
DDNS

**Comment by mgoffin** [comment]
I recently worked with this list doing some other development and most of them make a lot of sense:

```
ADJUST_TOKEN 
API_KEY 
AS_NUMBER 
AS_NAME 
ATTACK
BANNER 
CHECKSUM_CRC16 
CMD_LINE 
COOKIE_NAME 
COUNTRY 
CRX 
DEBUG_STRING 
DESCRIPTION 
DEST_PORT 
DEVICE_IO 
DIRECTORY_QUERIED 
DOC_FORM_URL 
DOMAIN 
EMAIL_ADDRESS 
EVENT_ID 
EVENT_REF 
EXPIRED_TIME 
FBID 
FILE_CREATED 
FILE_DELETED 
FILE_MOVED 
FILE_NAME 
FILE_OPENED 
FILE_READ 
FILE_WRITTEN 
FRONTIER_URL 
GET_PARAM 
HASH_IMPHASH 
HASH_MD5 
HASH_SHA1 
HASH_SHA256 
HASH_SSDEEP 
HEX_STRING 
HTML_ID 
HTTP_REQUEST 
HTTP_RESP_CODE 
IP_ADDRESS 
ISP 
LATITUDE 
LAUNCH_AGENT 
LOCATION 
LONGITUDE 
MALWARE_NAME 
MEMORY_ALLOC 
MEMORY_PROTECT 
MEMORY_READ 
MEMORY_WRITTEN 
MUTANT_CREATED 
MUTEX 
NAME 
NAME_SERVER 
OTHER_FILE_OP 
PASSWORD 
PASSWORD_SALT 
PAYLOAD_DATA 
PAYLOAD_TYPE 
PRIVACY_TYPE 
PRIVACY_MEMBERS 
POST_DATA 
PROTOCOL 
REFERER 
REFERER_OF_REFERER 
REGISTRAR 
REGISTRY_KEY 
REG_KEY_CREATED 
REG_KEY_DELETED 
REG_KEY_ENUMERATED 
REG_KEY_MONITORED 
REG_KEY_OPENED 
REG_KEY_VALUE_CREATED 
REG_KEY_VALUE_DELETED 
REG_KEY_VALUE_MODIFIED 
REG_KEY_VALUE_QUERIED 
REPORT_URL 
ROLE 
RULE 
SIGNATURE 
SIGNATURE_TYPE 
SMS_ORIGIN 
SOURCE_PORT 
TELEPHONE 
TIME_CREATED 
TIME_UPDATED 
TS_END 
TS_START 
URI 
USER_AGENT 
USER_ID 
VICTIM_IP 
VOLUME_QUERIED 
WEBSTORAGE_KEY 
WEB_PAYLOAD 
WHITELIST 
WHOIS_NAME 
WHOIS_ADDR1 
WHOIS_ADDR2 
XPI 
```

Some of these are not accurate. For example, ATTACK is an enumerated list of values which are supposed to describe "If you see this Indicator, it's most likely this type of attack...". For those, I suspect it would be worth either:

1) Not using them at all at this time, or
2) Adding an additional attribute to Indicators to support them

I am leaning towards the latter because it really helps provide details and context about the Indicator.

One thing I might suggest we stay away from are the signatures. In CRITs I suspect that having an entire TLO dedicated to signatures/rules makes more sense than coupling them into Indicators and having to do special searches and such to get at them.

There's also a list of Threat Types, again some which may or may not make sense for us:

```
    BAD_ACTOR
    COMPROMISED_CREDENTIAL
    COMMAND_EXEC
    MALICIOUS_AD
    MALICIOUS_CONTENT
    MALICIOUS_DOMAIN
    MALICIOUS_INJECT
    MALICIOUS_IP
    MALICIOUS_URL
    MALICIOUS_URLCHUNK
    MALWARE_ARTIFACTS
    MALWARE_SAMPLE
    MALWARE_SIGNATURE
    MALWARE_VICTIM
    PROXY_IP
    SIGNATURE
    SINKHOLE_EVENT
    SMS_SPAM
    VICTIM_IP_USAGE
    WEB_REQUEST
    WHITELIST_DOMAIN
    WHITELIST_IP
    WHITELIST_URL
```
