### ISSUE TITLE
Snugglefish indexing errors

### ISSUE THREAD

**Issue by DigitalMaxim** [crits/crits#509]
Hello,

When I run the following : find /home/wxs/FOO -type f | snugglefish -i -o /home/wxs/snugglefish-indexes/FOO -m 100000 (with my own directory and name)

I am receiving this error: snugglefish : command not found
If I run it like this : find /home/wxs/FOO -type f |  python snugglefish.py -i -o /home/wxs/snugglefish-indexes/FOO -m 100000
I am receiving this error:
ImportError: No module named crits.core.crits_mongoengine

Can you please advice.

Thank you.

**Comment by wxsBSD** [comment]
The first command fails because you don't have snugglefish installed. The second one errors because snugglefish.py is part of CRITs and not meant to be run directly. If you don't intend to use the snugglefish features (which is likely true) you can just remove the snugglefish service entirely by deleting the directory.

**Comment by DigitalMaxim** [comment]
Thank you for your response but I do want use snugglefish service in CRITs.

I've installed snugglefish and now when I run the command ind /home/wxs/FOO -type f | snugglefish -i -o /home/wxs/snugglefish-indexes/FOO -m 100000
I am receiving following errors:
Error: Endian Mismatch
Error: signal 11:
As I found through online searching that it might be connected to some memory problem. Ca

Maybe you can give me suggestions what might be a problem or what should I do to check what a cause of this?

Thanks,

**Comment by wxsBSD** [comment]
Looks like you might have old indexes laying around. Can you make sure your snugglefish-indexes directory is empty.

**Comment by DigitalMaxim** [comment]
I've removed all indexes from snugglefish-indexes directory. It is empty.

Now I am receiving this output while running the command:
invalid option --'m'
Processed: 0% --0/1   Error in thread:Statting File
Error: signal 11:

**Comment by DigitalMaxim** [comment]
When I run this command without "-m 100000" I am receiving following output:
Processed: 9223372036854775808% -- 0/0

**Comment by wxsBSD** [comment]
The -m option was removed and the documentation in the service was never updated. I'll update it later today but for now just don't use -m.

**Comment by DigitalMaxim** [comment]
Thank you.
Can you please confirm that the output I received without option 'm' is valid?
All .sngfs files that have been created are the same size. Is it ok?

**Comment by wxsBSD** [comment]
That doesn't seem right. Are you sure you have actual files to be indexed in /home/wxs/FOO (or whatever your directory is). In any case, this is not a problem with CRITs. Feel free to continue this discussion in the snugglefish repository as a new issue.

**Comment by DigitalMaxim** [comment]
Ok.
Thank you for your help.
