### ISSUE TITLE
Unable to add domain

### ISSUE THREAD

**Issue by AndyDove** [crits/crits#513]
I'm trying to add a domain with a .cymru TLD.  I have updated the list of TLDs using the web interface with the latest list downloaded from the web.  This list shows the TLD in question but when I try and add a domain with this TLD it tells me that it is invalid.  Any pointers would be much appreciated.

**Comment by thelok** [comment]
Can you try to restart your web server and try again?

**Comment by AndyDove** [comment]
I shall try that in the morning and get back to you.

**Comment by AndyDove** [comment]
I've restarted the server and it's now working correctly.  Thank you.

**Comment by thelok** [comment]
I'll make a more permanent fix soon
