### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by Shersto** [crits/crits#520]
I am getting this error and all dependencies are installed correctly. Any idea how to fix? This appears when trying to get to UI via DJANGO.

ValueError at /login/
dictionary update sequence element #0 has length 0; 2 is required
Request Method:	GET
Request URL:	http://10.10.10.143:8000/login/?next=/
Django Version:	1.8.2
Exception Type:	ValueError
Exception Value:	
dictionary update sequence element #0 has length 0; 2 is required
Exception Location:	/usr/local/lib/python2.7/dist-packages/django/template/context.py in bind_template, line 235
Python Executable:	/usr/bin/python
Python Version:	2.7.6
Python Path:	
['/home/dd/crits/crits',
 '/home/dd/crits',
 '/usr/local/lib/python2.7/dist-packages/pip-7.0.3-py2.7.egg',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages']
Server time:	Fri, 19 Jun 2015 23:51:17 -0400

**Comment by apolkosnik** [comment]
Looks like you need to downgrade Django to <1.7

I am getting this error and all dependencies are installed correctly. Any
idea how to fix? This appears when trying to get to UI via DJANGO.

ValueError at /login/
dictionary update sequence element #0 has length 0; 2 is required
Request Method: GET
Request URL: http://10.10.10.143:8000/login/?next=/
Django Version: 1.8.2
Exception Type: ValueError
Exception Value:

dictionary update sequence element #0 has length 0; 2 is required
Exception Location:
/usr/local/lib/python2.7/dist-packages/django/template/context.py in
bind_template, line 235
Python Executable: /usr/bin/python
Python Version: 2.7.6
Python Path:

['/home/dd/crits/crits',
'/home/dd/crits',
'/usr/local/lib/python2.7/dist-packages/pip-7.0.3-py2.7.egg',
'/usr/lib/python2.7',
'/usr/lib/python2.7/plat-x86_64-linux-gnu',
'/usr/lib/python2.7/lib-tk',
'/usr/lib/python2.7/lib-old',
'/usr/lib/python2.7/lib-dynload',
'/usr/local/lib/python2.7/dist-packages',
'/usr/lib/python2.7/dist-packages']
Server time: Fri, 19 Jun 2015 23:51:17 -0400

—
Reply to this email directly or view it on GitHub
<https://github.com/crits/crits/issues/520>.

**Comment by mgoffin** [comment]
Yep. All dependencies aren't installed correctly :)

**Comment by Shersto** [comment]
Down graded to DJANGO 1.7 same error no change.

**Comment by Shersto** [comment]
DJANGO 1.5 solved the issue

**Comment by mgoffin** [comment]
Read requirements.txt. Less than 1.7. You should use 1.6.8 and you'll be fine.
