### ISSUE TITLE
No module named crits.settings

### ISSUE THREAD

**Issue by shiv183** [crits/crits#522]
Hi,

When i run ./script/server, i'm getting crits instance. while running the same on production mode with apache, i'm getting this error. 

"mod_wsgi (pid=8781): Exception occurred processing WSGI script '/data/crits/django.wsgi'.
[Fri Jun 26 11:45:29.377549 2015] [:error] [pid 8781:tid 139675400800000] [client 127.0.0.1:37288] Traceback (most recent call last):
[Fri Jun 26 11:45:29.377577 2015] [:error] [pid 8781:tid 139675400800000] [client 127.0.0.1:37288]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 187, in __call__
[Fri Jun 26 11:45:29.377617 2015] [:error] [pid 8781:tid 139675400800000] [client 127.0.0.1:37288]     self.load_middleware()
[Fri Jun 26 11:45:29.377630 2015] [:error] [pid 8781:tid 139675400800000] [client 127.0.0.1:37288]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 44, in load_middleware
[Fri Jun 26 11:45:29.377649 2015] [:error] [pid 8781:tid 139675400800000] [client 127.0.0.1:37288]     for middleware_path in settings.MIDDLEWARE_CLASSES:
[Fri Jun 26 11:45:29.377667 2015] [:error] [pid 8781:tid 139675400800000] [client 127.0.0.1:37288]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
[Fri Jun 26 11:45:29.377685 2015] [:error] [pid 8781:tid 139675400800000] [client 127.0.0.1:37288]     self._setup(name)
[Fri Jun 26 11:45:29.377697 2015] [:error] [pid 8781:tid 139675400800000] [client 127.0.0.1:37288]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 49, in _setup
[Fri Jun 26 11:45:29.377735 2015] [:error] [pid 8781:tid 139675400800000] [client 127.0.0.1:37288]     self._wrapped = Settings(settings_module)
[Fri Jun 26 11:45:29.377747 2015] [:error] [pid 8781:tid 139675400800000] [client 127.0.0.1:37288]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 132, in __init__
[Fri Jun 26 11:45:29.377764 2015] [:error] [pid 8781:tid 139675400800000] [client 127.0.0.1:37288]     % (self.SETTINGS_MODULE, e)
[Fri Jun 26 11:45:29.377787 2015] [:error] [pid 8781:tid 139675400800000] [client 127.0.0.1:37288] ImportError: Could not import settings 'crits.settings' (Is it on sys.path? Is there an import error in the settings file?): No module named crits.settings"

I need solution for it. Thanks in advance. @mgoffin  @superhac

**Comment by mgoffin** [comment]
This was just answered on the mailing list. You don't have your CRITs install directory in your Apache users PYTHONPATH. Please refer to the mailing list for more info.
