### ISSUE TITLE
CSRF verification failure when submitting objects

### ISSUE THREAD

**Issue by 0x3a** [crits/crits#525]
When adding a new object the following dialog is brought up:
https://github.com/crits/crits/blob/master/crits/objects/templates/dialogs/add-object.html

When submitting an error is returned regarding the fact that the CSRF verification failed.
![crits_csrf_object_error](https://cloud.githubusercontent.com/assets/7872766/8433135/445e3d30-1f44-11e5-9e17-da34d0734675.png)

**Comment by mgoffin** [comment]
I actually had to fix this in my PR for removing cybox/stix when i redesigned stuff. Once that PR is accepted, this will get fixed too :)

**Comment by 0x3a** [comment]
Good to know, thanks!
