### ISSUE TITLE
sed command in bootstrap script fails on mac (yosemite)

### ISSUE THREAD

**Issue by JeffAMcGee** [crits/crits#527]
When I run the bootstrap script, it has problems setting the SECRET_KEY:

    Dependency installations complete!
    Setting up crits.log file
    Creating default database configuration file
    sed: 1: "s/^\(SECRET_KEY = \).*$ ...": bad flag in substitute command: 'T'
    Creating default collections
    Unknown command: 'create_default_collections'
    Type 'manage.py help' for usage.

I was able to make things work by setting SECRET_KEY in crits/config/database.py by hand.  I think the problem may be that sed on a mac is BSD sed, not GNU sed.

**Comment by frbapolkosnik** [comment]
I think I've fixed that already, can you please close the issue?
