### ISSUE TITLE
After reinstall, Django errors

### ISSUE THREAD

**Issue by bond-alexander** [crits/crits#532]
I'm reinstalling CRITs on top of my previous install, which was both out of date and broken.

After installation and configuration, it was working until I defined the CRITs services path. I went through and updated all of the services, which resolved several errors. Now I'm left with a Django error that I don't know how to resolve.

```
Environment:


Request Method: GET
Request URL: https://10.10.131.211/crits/login/

Django Version: 1.6.5
Python Version: 2.7.6
Installed Applications:
('crits.core',
 'crits.dashboards',
 'django.contrib.auth',
 'mongoengine.django.mongo_auth',
 'django.contrib.contenttypes',
 'django.contrib.messages',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.staticfiles',
 'crits.actors',
 'crits.campaigns',
 'crits.certificates',
 'crits.domains',
 'crits.emails',
 'crits.events',
 'crits.indicators',
 'crits.ips',
 'crits.locations',
 'crits.objects',
 'crits.pcaps',
 'crits.raw_data',
 'crits.relationships',
 'crits.samples',
 'crits.screenshots',
 'crits.services',
 'crits.stats',
 'crits.targets',
 'tastypie',
 'tastypie_mongoengine')
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware')


Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  112.             if response is None:
File "/data/crits/crits/core/views.py" in login
  404.                               RequestContext(request))
File "/usr/local/lib/python2.7/dist-packages/django/template/context.py" in __init__

File "/usr/local/lib/python2.7/dist-packages/django/template/context.py" in get_standard_processors
  148.     def bind_template(self, template):
File "/usr/local/lib/python2.7/dist-packages/django/utils/module_loading.py" in import_by_path
  26.     module = import_module(module_path)
File "/usr/local/lib/python2.7/dist-packages/django/utils/module_loading.py" in import_by_path
  21.         module_path, class_name = dotted_path.rsplit('.', 1)
File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py" in import_module
  40.             for character in name:
File "/usr/local/lib/python2.7/dist-packages/django/core/context_processors.py" in <module>
  4. from django.utils.deprecation import RemovedInDjango20Warning

Exception Type: ImproperlyConfigured at /login/
Exception Value: Error importing module django.core.context_processors: "cannot import name RemovedInDjango20Warning"
```
I don't know how to resolve this. Any ideas?

**Comment by mgoffin** [comment]
You've improperly configured something in Django. Not sure what but whatever you changed configuration-wise busted something. I'd revert your changes to make it work again and slowly change stuff until it breaks so you know what you are doing.

**Comment by gtback** [comment]
@bond-alexander, It looks like you have a weird combination of Django versions installed. `RemovedInDjango20Warning` in `django/core/context_processors.py` looks like its from a newer version of Django (such as [1.8.2](https://github.com/django/django/blob/1.8.2/django/core/context_processors.py#L4)), not the version of Django the error [says is installed](https://github.com/django/django/blob/1.6.5/django/core/context_processors.py#L4) (`Django Version: 1.6.5`).

Without knowing more about exactly how you reinstalled over an existing installation, I can't say for sure how that could have happened. Stale .pyc files, perhaps? What OS and Python version are you running? How did you install Python? Are you using the system-installed Python?

**Comment by dsnellgrove** [comment]
Manual installations of Django (i.e., not using pip or your system's package manager) will clobber versions of files. You MUST manually uninstall/remove Django before changing versions if you're using anything other than those two methods.

**Comment by frbapolkosnik** [comment]
Has this been resolved by the latest changes?

**Comment by bond-alexander** [comment]
Thanks for checking, I've actually left that role so I no longer have
access to that box and thus can't figure out what borked it. Feel free to
close the ticket.
