### ISSUE TITLE
Dashboards not working after upgrade from CRITs 3.1 to stable_4

### ISSUE THREAD

**Issue by seanthegeek** [crits/crits#536]
After an upgrade to CRITs stable_4, everything works fine except the dashboards:

[Screenshot](https://imgur.com/KIob0QC)

It appears to be caused by a problem with templating, or JavaScript/AJAX.

From the browser console:
>SyntaxError: expected expression, got ',' 127.0.0.1:8080:194:31
>SyntaxError: expected expression, got ',' 127.0.0.1:8080:246:31
>SyntaxError: expected expression, got ',' 127.0.0.1:8080:298:31
>SyntaxError: expected expression, got ',' 127.0.0.1:8080:352:31
>SyntaxError: expected expression, got ',' 127.0.0.1:8080:404:31
>SyntaxError: expected expression, got ',' 127.0.0.1:8080:456:31

Browser source snipit:

```
<div style="width: 100%; margin-bottom: 10px;">
    <div class='content_body'>
        <div id=''></div>
    </div>
</div>
<script type="text/javascript">
            $(document).ready(function() {
                $('#').jtable({
                    "title": "",
                    "sorting": ,
                    "paging": ,
                    "pageSize": ,
                    "pageSizes": [, 10, 25, 50, 100, 250, 500],
                    "defaultSorting": "",
                    "jqueryuiTheme": true,
                    "multiSorting": ,
                    

                    "recordsLoaded": function(event,data) { 
  	                                   jtRecordsLoaded(event,data,""); 
 	                },
                    "actions": {
                        
                        
                        
                    },
                    "fields": {
                        
                    }
                });

                $('#').jtable('load');

            });

</script>
```

I've ran `python manage.py create_default_dashboard -d` And the issue remains.

Dashboards in Mongo:

```
> db.dashboard.findOne()
{
        "_id" : ObjectId("559e7584884e7f29bfe1122c"),
        "schema_version" : 1,
        "name" : "Default",
        "theme" : "default",
        "isPublic" : true,
        "hasParentChanged" : false
}
```

Does anyone know what is going wrong, and how I can fix it?

**Comment by mgoffin** [comment]
Try clearing browser cache and bouncing your web server. Might be old JS trying to load. I know it works as-is on several of my instances so investigating local issues first would be best.

**Comment by seanthegeek** [comment]
I've tried both. Unfortunately, it does not seem to be a client issue.

**Comment by seanthegeek** [comment]
I was able to fix this issue by completely removing everything from `/data/crits`, except `./crits/config/database.py`, before copying over the new files. There must have been some conflicting `.pyc` or `.js` files in there.
