### ISSUE TITLE
Add indicator description via API

### ISSUE THREAD

**Issue by virtugon** [crits/crits#541]
It's currently not possible to add a description to an indicator using the API.

**Comment by dspruell** [comment]
+1 to this - would like to see this as well in order to preserve context coming in from sources that are loaded via the API.

**Comment by armtash** [comment]
You are able to do this now using a patch request: https://github.com/crits/crits/pull/664

Update the description of a TLO:

     import requests
     url = 'http://localhost:8000/api/v1/<TLO_TYPE>/<TLO_ID>'
     params = {
                 'api_key' : '<your api key>',
                  'username' : '<your username>',
              }
     data =  {
                  'action': 'description_update',
                  'description' : '<description>',
                  }
     r = requests.patch(url, params=params, data=data)
     print r.content

**Comment by dspruell** [comment]
This is great. The PATCH request would work for setting a description as an update to an existing object; does this currently work at object creation time via a POST request? Ideally hoping to see #668 come to closure with this type of work, with API object creation supporting description being highest priority.

**Comment by armtash** [comment]
I just tried adding a description to an indicator object with a POST and it didn't work.  My workaround temporarily would be to create an indicator, extract the returned url/id, and perform a PATCH to update the description immediately after.

**Comment by frbapolkosnik** [comment]
Hey guys, take a look at #674.

**Comment by apolkosnik** [comment]
It's been merged, you can close this issue.
