### ISSUE TITLE
Changing IP Address of CRITs

### ISSUE THREAD

**Issue by johncwrobel** [crits/crits#542]
I have a CRITs instance running at 0.0.0.0:8080 right now, but I would like to change the IP address so that you can access CRITs from outside of the server it is actually installed on. I can't find anything about how to do this (I assume because it's very easy and I'm just dumb). If anyone could help me out I'd really appreciate it. Thanks!

Also, if there's a better place to ask questions like this, please let me know.

**Comment by mgoffin** [comment]
This isn't something specific to CRITs. This is about your web server and your network and how you configure it. I'd check out the documentation for the web server of your choice and read up on how to configure it for access.

If you are running django's runserver to do this then just change the IP to be the IP of the box you are on.
