### ISSUE TITLE
Upload of File Object Fails

### ISSUE THREAD

**Issue by init99** [crits/crits#546]
Attempting to upload a file object on a sample fails. Possibly missing csrf_token for POST?

**Comment by mgoffin** [comment]
Which branch are you using? Want to know where to look :) Thanks!

**Comment by init99** [comment]
Thanks!
master - 15244f7

**Comment by mgoffin** [comment]
Yea sounds like you need to update master.

**Comment by init99** [comment]
That did it, thanks!
