### ISSUE TITLE
Downloading master .zip results in missing files (__init__.py) - Prevents Django from finding crits.settings

### ISSUE THREAD

**Issue by armtashjian** [crits/crits#552]
I was trying to setup a test server on RHEL today, and instead of cloning the repository I downloaded the master zip file using the link on the homepage, https://github.com/crits/crits/archive/master.zip

I found after troubleshooting some errors that when extracting the zip file, some  __init__.py files were missing.  A specific __init__.py file that is missing is /crits/crits/__init__.py

Without the  __init__.py file, django will be unable to find the configuration file.
An error similar to this will result:

"ImportError: Could not import settings 'crits.settings' (Is it on sys.path?): No module named 'crits.settings'"

The zip file has an md5 hash of: d9a936dc3a96a99179eb848a034c2ac7

In the past, I have used the zip file with no issues.

Cloning the repository resulted in no missing files.  I had no issues getting CRITs running after cloning.

**Comment by mgoffin** [comment]
If you can clone it and it works, I'd have to assume this is github related and not specific to the code base.

**Comment by armtashjian** [comment]
I agree, however I am sure that others will try to download the zip instead of cloning.  It might be wise to mention this in the readme or something.

**Comment by brlogan** [comment]
I just downloaded the .zip file from that link and crits/crits/__init__.py was in it.

**Comment by armtashjian** [comment]
Indeed the zip file has a different hash now: 5859AEFC258D6FAB8D98740E8637101E

It seems like this was a temporary issue with github.
