### ISSUE TITLE
Screenshot is not visible in CRITs using add_screenshot

### ISSUE THREAD

**Issue by pixel5919** [crits/crits#553]
I am trying to upload screen-shots automatically using add_screenshot from crits/screenshots/handlers. After calling the function, I get a return message of "Screenshot(s) Successfully Uploaded!" but it doesn't appear in CRITs. I checked to see if it was in MongoDB and it is.

**Comment by mgoffin** [comment]
I suspect if you are writing custom code to do this that you aren't using it properly. Could you show us your code and scrub anything sensitive?

**Comment by pixel5919** [comment]
import zipfile
#from crits.screenshots.screenshot import Screenshot
from crits.settings import TEMP_DIR
from crits.screenshots.handlers import add_screenshot

...
def _add_screenshot(self, zip_images, task_id):
        self._debug("Processing Screenshots")
description = "This is for Testing"
	tags = ""
	source = get_user_organization(self.current_task.username)
	method = self.name
	reference = ""
	analyst = self.current_task.username
	screenshot_ids = ""
	oid = str(self.obj.id)
	otype = "Sample"
	
	result = {}
	self._debug(source)
	self._debug(str(method))
	self._debug(str(analyst))
	self._debug(str(oid))
	self._debug(str(otype))
	try:
	    self._debug("	Trying to open Screenshot")
	    screenshot = open("/tmp/107/0002.png","rb")
	    self._debug("	Screenshot Opened")
	    result = add_screenshot(description, tags, source, method, reference, analyst, screenshot, screenshot_ids, oid, otype)
	    self._debug(str(result['message']))
        #screenshot.close()
	except IOError:
	    self._debug("Test Failed: IOError")
        #screenshot.close()
	    return False	
	except:
	    self._debug("Test Failed")
        #screenshot.close()
	    return False
	self._debug("Test Passed")
...

**Comment by mgoffin** [comment]
Ok. And you get a response back (which should contain an ID). When you query for that ID you get a screenshot back? Does it have a source that your account has access to? Is the file actually in GridFS?

**Comment by pixel5919** [comment]
The account that I was using didn't have access to that source, but I thought this would query the source of the sample being sent: 

`source = get_user_organization(self.current_task.username)`

When I added the service, it took the source that I was a part of "Testing". I decided to change the sources that I have access to so that other users/sources could use the service. I took myself off of "Testing" and added myself to "PID". 

This is what the image is in MongoDB: 
`{ "_id" : ObjectId("55c34a2964565a45b367ad0f"), "created" : ISODate("2015-08-06T07:51:04.565Z"), "modified" : ISODate("2015-08-06T07:51:05.402Z"), "schema_version" : 1, "source" : [ { "instances" : [ { "analyst" : "jedi", "date" : ISODate("2015-08-06T07:51:05.401Z"), "method" : "custom_screenshot_service", "reference" : "" } ], "name" : "Testing" } ], "analyst" : "jedi", "description" : "This is for Testing", "filename" : "/tmp/107/0003.png", "height" : 1080, "md5" : "3c5dec54654bb4d3325c09b1addbfb91", "screenshot" : ObjectId("55c34a2964565a45b367ad02"), "tags" : [ ], "thumb" : ObjectId("55c34a2964565a45b367ad0d"), "width" : 1920 }
`
But the service kept the old source "Testing". Is there a better way to get the source of the current user who is running the service?

**Comment by mgoffin** [comment]
There is no specific source for a user. There is an organization they belong to, but that doesn't mean they have access to that as a source. You'll need to decide what organization is generating the screenshots and add that source. Then make sure any users who should see content from that source have access to it.

**Comment by pixel5919** [comment]
Thanks for the help!
