### ISSUE TITLE
Issues relationship issues with samples

### ISSUE THREAD

**Issue by frbapolkosnik** [crits/crits#555]
- On upload of MSG file, the relationship is not forged (or errors out) resulting in attachements and emails not having a relationship
- relationships are also not forged for samples that are containing samples 
- when you try to manually forge a relationship, once you "get the ID from clipboard" the type appears as Email

**Comment by frbapolkosnik** [comment]
Another scenario:

I have an email, then click on add attachment, uploaded the attachment (just some file), and no relationship is forged automatically

**Comment by frbapolkosnik** [comment]
I've tested, #558 fixed the issue

**Comment by mgoffin** [comment]
558 doesn't fix the issue. The issue is not handling spaces in relationship names (if your PR does in fact fix this problem).

**Comment by frbapolkosnik** [comment]
I assumed that the vocabulary didn't change, now I'll make inverse() tolerant of underscores and spaces.

**Comment by mgoffin** [comment]
for the most part, all of the vocabulary changed. see #523

**Comment by frbapolkosnik** [comment]
Then, would you rather prefer to make 1 line change in inverse() or try to hunt down all the instances (in services too) where some of the relationship types are not updated?

**Comment by frbapolkosnik** [comment]
just in case PR #559 for one-liner.

**Comment by frbapolkosnik** [comment]
This morning I've added some debug into crits/core/crits_mongoengine.py:
    Entering add_relationship:
    rel_type: Contained_Within, rev_type: None

looks like rev_type = RelationshipTypes.inverse(rel_type) is not working 

https://github.com/crits/crits/blob/master/crits/vocabulary/relationships.py#L16 defines the relationships containing spaces:
CONTAINED_WITHIN = "Contained Within"

I'm looking through crits_services to hunt down the relationships and replace them with RelationshipTypes.

One puzzling part is what to use to replace "Extracted_From".

**Comment by frbapolkosnik** [comment]
Ok, that's fixed after my changes were merged.
