### ISSUE TITLE
Linking CRITS to Cuckoo

### ISSUE THREAD

**Issue by rprasko** [crits/crits#584]
Hi All,

I am having some troubles trying to link CRITS in to my Cuckoo Sandbox. I have a functioning sandbox and have been able to start the web interface that CRITS runs through. To this point I have not been able to link these two together. I have installed the crits-services and placed the file path for the crits-services folder into the services tab within the CRITS Control Panel. All services remain Unavailable, specifically the Cuckoo service. I have run the api.py that Cuckoo Sandbox provides. It seems to be an easy process to be able to link these two, but I have to be missing something. If anyone could give me a run through of how to accomplish this connection it would be greatly appreciated.

Thanks,
Ryan

**Comment by mgoffin** [comment]
This is something that should be discussed on the mailing lists so we can keep Issues clean :) I think there's also some threads there that might cover this and could help!
