### ISSUE TITLE
Failure to pull Word document attachments in Outlook MSG files

### ISSUE THREAD

**Issue by seanthegeek** [crits/crits#587]
When uploading an MSG file with a word document attachment, the user receives "Error uploading file", but the email object is created, without the attachment.

This issue is probably related to issue #539

**Comment by frbapolkosnik** [comment]
There's a limitation in .MSG parsing code, that doesn't support extraction of the embedded attachments (I forgot exactly what's the term for it).

**Comment by seanthegeek** [comment]
Fix found. See issue #653
