### ISSUE TITLE
Sample Zip Extraction Breaking 7z

### ISSUE THREAD

**Issue by thelok** [crits/crits#589]
Bug introduced from #581

You need to have a dependency on the package p7zip-plugins which provides the 7z binary otherwise you get a error 

ZipFileError: ' 2 No such file or directory'

**Comment by thelok** [comment]
OK fine, this is indicated in the UPDATING file, but not in the DEPENDENCIES file.

**Comment by frbapolkosnik** [comment]
DEPENDENCIES actually says:
7zip
Provides: 7z

Only RHEL/CentOS splits it off into separate packages.
