### ISSUE TITLE
API upload error for "raw" type on emails

### ISSUE THREAD

**Issue by ManoftheSea** [crits/crits#590]
The upload API for emails allows selecting the "raw" type.  Doing so gives an error:
{"error_message": "'InMemoryUploadedFile' object has no attribute 'split'", 
 "traceback": "Traceback (most recent call last):\n\n
  File \"/usr/local/lib/python2.7/dist-packages/django_tastypie-0.11.0-py2.7.egg/tastypie/resources.py\", line 195, in wrapper\n
    response = callback(request, *args, **kwargs)\n\n
  File \"/usr/local/lib/python2.7/dist-packages/django_tastypie-0.11.0-py2.7.egg/tastypie/resources.py\", line 426, in dispatch_list\n
    return self.dispatch('list', request, **kwargs)\n\n
  File \"/usr/local/lib/python2.7/dist-packages/django_tastypie_mongoengine-0.4.5-py2.7.egg/tastypie_mongoengine/resources.py\", line 390, in dispatch\n
    return self._wrap_request(request, lambda: super(MongoEngineResource, self).dispatch(request_type, request, **kwargs))\n\n
  File \"/usr/local/lib/python2.7/dist-packages/django_tastypie_mongoengine-0.4.5-py2.7.egg/tastypie_mongoengine/resources.py\", line 360, in _wrap_request\n
    return fun()\n\n
  File \"/usr/local/lib/python2.7/dist-packages/django_tastypie_mongoengine-0.4.5-py2.7.egg/tastypie_mongoengine/resources.py\", line 390, in <lambda>\n
    return self._wrap_request(request, lambda: super(MongoEngineResource, self).dispatch(request_type, request, **kwargs))\n\n
  File \"/usr/local/lib/python2.7/dist-packages/django_tastypie-0.11.0-py2.7.egg/tastypie/resources.py\", line 458, in dispatch\n    response = method(request, **kwargs)\n\n
  File \"/usr/local/lib/python2.7/dist-packages/django_tastypie-0.11.0-py2.7.egg/tastypie/resources.py\", line 1320, in post_list\n
    updated_bundle = self.obj_create(bundle, **self.remove_api_resource_names(kwargs))\n\n
  File \"/opt/crits/crits/emails/api.py\", line 111, in obj_create\n    ticket=ticket)\n\n  File \"/opt/crits/crits/emails/handlers.py\", line 882, in handle_pasted_eml\n
    for line in data.split(\"\\n\"):\n\nAttributeError: 'InMemoryUploadedFile' object has no attribute 'split'\n"}

This error seems to be due to the upload trying to call the "split" function on 'data', passed from the upload API as an UploadedFile object, rather than a string when passed in from the forms handling code in Views.py.

It would appear that there is a conversion needed, but I don't understand the regex's in handle_pasted_eml to distinguish between "raw" and "eml" upload types.  So I don't know how to test, or what "correct" looks like.

**Comment by mboman** [comment]
Works for me. Please merge to stable_4 :+1:
