### ISSUE TITLE
rawdata chokes on unicode in file data

### ISSUE THREAD

**Issue by qtfkwk** [crits/crits#596]
My CRITs server responded with a 500 error for some files when trying to create a rawdata object via the pycrits.add_raw_data() method. So I attempted the creation directly against the API using the requests module and observed the following error snippet:

```
  File "/opt/crits/crits/raw_data/handlers.py", line 348, in handle_raw_data_file
    data = data.encode('utf-8')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 1234: ordinal not in range(128)
```

I'm not sure why this is being done, as it attempts to downconvert to ASCII rather than perhaps the intention of upconverting to UTF-8. It is already in UTF-8. Example: https://github.com/kumar303/unicode-in-python/blob/master/unicode.txt#L252

The correct solution in my mind is actually to omit the line altogether, which has the benefit of keeping the original bytes intact, especially just prior to the code that generates the MD5 hash of the data.

The line was commented in a local CRITs instance and the same files that produced the 500 error uploaded successfully. No other side effects or issues were observed, however I am not sure if there are other issues that I haven't considered.

**Comment by mgoffin** [comment]
Seems reasonable. I think the ASCII conversion might have had to do with rendering in some situations but I'd have to test.  Ultimately I'd love to enhance support via services for uploading things like PDFs and getting text out so non-ASCII support would help.
