### ISSUE TITLE
Error "No valid TLD found" when trying to create URI indicator "https://mega.nz"

### ISSUE THREAD

**Issue by qtfkwk** [crits/crits#598]
Not sure what is causing this... it isn't quite clear to me where the list of valid TLD's is defined. ".nz" should certainly be on it.

Is that even the real problem?

**Comment by thelok** [comment]
Download https://publicsuffix.org/list/effective_tld_names.dat and upload that under Admin=>Add New Item=>TLDs

**Comment by qtfkwk** [comment]
That worked! Thanks for the help, @thelok!
