### ISSUE TITLE
Service Nav Items not loading

### ISSUE THREAD

**Issue by gtback** [crits/crits#601]
So I know I was the one to cause this one, but Service nav items no longer seem to be working. I think this is caused around [here](https://github.com/crits/crits/blob/18ca08849927edf975088848dfc156804a7b211f/crits/settings.py#L526-L528). When importing settings for the first time, it tries to load various services. The problem is that services (such as taxii_service) that try to in turn load settings can't (because it hasn't finished loading yet), so the import check fails, and the templates are never added to `SERVICE_NAV_TEMPLATES`.

Besides resolving the circular import, an alternate solution is to remove the "import" check (going back to the way it was prior to #585), but this would mean that services with missing dependencies would cause the entire app to fail to load, meaning unwanted service directories would need to be removed to get a functioning system

@mgoffin, do you have any thoughts?

**Comment by mgoffin** [comment]
I was fine with "you told us to install a service and didn't install dependencies so we are bombing" situation. But if we can did an elegant way to handle services it would be better.

Honestly I'd love it if we could dynamically load services after the web server started and without needing a restart. Kind of like installing plugins for Wordpress. You wouldn't need to download the services repo. You can browse them in the UI and install them (which would use the service's own bootstrap) and they're magically available.

**Comment by gtback** [comment]
My only problem with "you told us to install a service and didn't install dependencies" is that by default there are a *LOT* of services in the service repo. Most people are going to want a lot of them, but I doubt anyone wants all of them. So it's an extra step to remove the ones that you don't want, which is especially hard if you're trying to do development off of cloned repos (such as with the Vagrant stuff I've been doing lately). I'd rather have something that gracefully (as in, not throw Django error pages) ignores errors about missing dependencies, while logging the messages to the log file so people can hopefully fix them if they want. The action of "enabling" services is where administrators should specify which services they want to use. 

I just realized, though, that none of the service-customizable templates (nav items, tabs, etc.) depends on whether the service is "enabled" through the UI or not, so it seems like "remove directories for services you don't want" is the desired model for making services available or not. I'll go ahead and revert the part of #585 that caused this, so that at least the nav templates show back up. 

In terms of dynamic uploading and enabling of services, yes that would be great, but the problem with any "magic" behavior is that there's always someone who has to write "real" code behind it :wink:
