### ISSUE TITLE
Ubuntu Bootstrap broken (no executable named pip2.7)

### ISSUE THREAD

**Issue by gtback** [crits/crits#603]
When running the bootstrap script on Ubuntu, Python dependencies do not get installed because there is no `pip2.7` command. This causes cascading errors when trying to run Django management commands, for example.

https://github.com/crits/crits/pull/593#issuecomment-141484667

**Comment by frbapolkosnik** [comment]
Can you check #604?

**Comment by gtback** [comment]
yep, that works. Thanks @frbapolkosnik

**Comment by frbapolkosnik** [comment]
I guess, you can close this since #604 has been merged, and it fixed issue introduced by #593.
