### ISSUE TITLE
New version of pillow breaks vagrant setup due to libjpeg dependency

### ISSUE THREAD

**Issue by twwbond** [crits/crits#613]
There is a new version (3.0) of the pillow library which has a new required dependency on libjpeg-dev.  This needs to be added to the vagrant config.  It is currently breaking fresh vagrant setups (worked with @gtback to resolve).

**Comment by frbapolkosnik** [comment]
Why stop there, just add the dependencies for Pillow on Ubuntu to get the wide variety of image formats supported:
liblcms2-dev
libfreetype6-dev
libtiff-dev
zlib1g-dev
libwebp-dev
libjpeg-dev
libopenjpeg-dev

**Comment by twwbond** [comment]
Makes sense, but the missing libjpeg-dev is actually breaking the vagrant VM for folks just getting started with CRITs.  The rest are optional and can be added later if needed.

**Comment by mgoffin** [comment]
If we're going to add them for Vagrant, might as well add them as standard dependencies for the entire project :)

**Comment by gtback** [comment]
@mgoffin : I think that's what @twwbond meant :wink:. There's no separate list of dependencies for the Vagrant provisioning. It just calls the bootstrap script, so I'm guessing the new Pillow version breaks non-Vagrant provisioning as well.

**Comment by apolkosnik** [comment]
This can be probably closed due to #683.
