### ISSUE TITLE
Events API doesn't allow campaign or confidence

### ISSUE THREAD

**Issue by Magicked** [crits/crits#616]
According to the docs at https://github.com/crits/crits/wiki/Authenticated-API, most TLOs should allow campaign and confidence assignment (I realize it says "most"). When creating events through the API, it doesn't look like campaign or confidence is used. Is this something we should add or was there a reason for not doing this?

**Comment by mgoffin** [comment]
This is mainly because the handler for creating Events doesn't allow for it:

https://github.com/crits/crits/blob/master/crits/events/handlers.py#L229
