### ISSUE TITLE
getAllObjectTypes() - Advanced Search Menu not Displayed and Object Select not Created

### ISSUE THREAD

**Issue by johnatron** [crits/crits#617]
It appears that a deprecated synchronous AJAX call in objects.js (https://github.com/crits/crits/blob/master/extras/www/static/js/objects.js#L37) is causing an exception that is short circuiting the call to show the advanced search menu (https://github.com/crits/crits/blob/master/extras/www/static/js/core.js#L902).  A screen shot of the missing search menu is attached.

There is also an error in the AJAX success function that results in the Objects Select List not being constructed.

Suggest update at (https://github.com/crits/crits/blob/master/extras/www/static/js/objects.js#L49):

```
$.each(sorted, function(index, value) {
	if (sel) {
		sel.append('<option value="'+value+'">'+value+'</option>');
	} else {
		return_data[value] = value;
	}
});
```
![screen shot 2015-10-06 at 10 33 04 am](https://cloud.githubusercontent.com/assets/2894032/10320194/27cc7c24-6c27-11e5-9420-8a0646324176.png)
![screen shot 2015-10-06 at 12 34 57 pm](https://cloud.githubusercontent.com/assets/2894032/10320198/2cc04af8-6c27-11e5-9e52-a0a7c56e4b3f.png)

**Comment by thelok** [comment]
I made your changes and it seems to work now.
