### ISSUE TITLE
Signature Identification/Storage

### ISSUE THREAD

**Issue by dreardon** [crits/crits#625]
I wanted to follow-up on a part of an old post from June 2015 and request a way to handle/store signatures:
https://github.com/crits/crits/issues/503#issuecomment-108079377

That discussion was more based on the CRITs vocabulary, but I’m looking for the best place or method to store signatures that have been developed. I guess I see a few different ways of going about it, but I wanted to approach the community to hear how others might be handling it, or if it should be considered as new development. Options I see are:

 - Start the process to make Signatures a new TLO, realizing that this is not trivial work
 - Use the “Raw Data” TLO. If I put it there, I can also identify the tool (Snort, Yara, etc.)
 - Change the vocabulary in the Indicators TLO to define/categorize an indicator...something that the June 2015 suggested against

Thanks.

**Comment by mgoffin** [comment]
I still think the third option is out. Signatures to me are not Indicators of Compromise, they are used as detectors of lots of those Indicators as well as other malicious content.

The second option isn't the worst thing in the world as it would cater to the immediate need, but I still think the first option is the best. It gives us a specific place for all signatures/rules to live and makes it easier for building services around them.

**Comment by dreardon** [comment]
Thanks for the response. I’ve done *some* development, but before I go too far, I wanted to pass along my thoughts on the Signature TLO to see if anyone has any thoughts or suggestions for changes. My approach is to model it after the Raw Data TLO with some differences. Essentially, I kept it pretty simple on purpose. The data elements I wanted to capture in the Signature form are:

- Title
- Data Type (Administrator managed drop-down of types…Yara, Snort, etc.)
- Description
- Data
- *Source*
- *Source Method*
- *Source Reference*
- *Bucket List*
- *Ticket*

The items in italics above are the standard form elements found in most TLOs. The Signature TLO will also contain a similar versioning and diffing capability that exists in the Raw Data TLO.

![image](https://cloud.githubusercontent.com/assets/346206/10637440/bdb96122-77d3-11e5-9085-5bb3eace3139.png)

Finally, the Signature API will be pretty standard and adhere to what the rest of the TLOs allow:

![image](https://cloud.githubusercontent.com/assets/346206/10637422/9983cae0-77d3-11e5-88e0-179c7ad8f7ab.png)

**Comment by mgoffin** [comment]
This looks great! I think you've hit on all of the appropriate fields
necessary to build up a solid TLO. Has there been any ideas on how to
display the "data" field on the details page? For example, Yara rules are
much easier to read when they are displayed as they look in a rule file,
but also look completely different from other rule types (BRO, Snort, etc.).

Also, I apologize ahead of time as adding a new TLO is not the easiest
thing in the world. I think modeling it after Raw Data was the perfect
choice, so grepping the whole code base for "RawData" will hopefully expose
all of the places you'd need to made changes/additions.

Another thought I had about relationships to a Signature. Say we had an
Indicator which was related to a Signature. It would make sense that the
relationship indicates you can leverage the Signature to find that
Indicator, but what about recording actual hits? I'm not sure how to best
record/denote that "this signature hit for this indicator on this date".
Any ideas?

**Comment by dreardon** [comment]
Thanks for the quick feedback. You're right, adding a new TLO isn't the easiest thing to tackle during my first CRITs commit; however, like you said, grepping the code base for RawData, raw_data, etc. has helped to make me sane.

Regarding the data display on the details page, for right now, I took another page from the Raw Data TLO and just used that data component; however, you're right a Yara rule is much easier to read when its displayed nicely like below.That said, since I made the Signature Data Type an environment-specific list of custom values, I'm not sure I would commit to anything here. 

![image](https://cloud.githubusercontent.com/assets/346206/10638935/85ed9b02-77db-11e5-8ead-9062b163a833.png)

This sort of leads me to your third point regarding Signatures and Indicators. I have thought about this in two ways. 
 - A possible need for updated relationship types to describe Signatures relationships with other TLOs (not groundbreaking, but maybe helpful)
 - Then, once there exists a robust list of signatures in an instance of CRITs, is using that data in either a service or possibly the core product. I'd bet there are a few services that could be updated to utilize the data as well as other internal interactions with the Samples, etc.

While it's not "ready for prime-time" yet...here is my starting point for the code impact on a new TLO.

https://github.com/crits/crits/compare/master...dreardon:new_signature_tlo

Thanks again for feedback.

**Comment by mgoffin** [comment]
I think that looks great :) I don't think there would be a hold-up for
displaying the signature in a format that is useful for that signature
type. I think we can work on that over time after the code is accepted if
need be. What you have in your screenshot looks good to me :)

I agree that we can probably add one or two relationship types to the
vocabulary which revolve around signatures and their relationship to other
TLOs.

I am also excited to see what kind of services people generate for
Signatures. I suspect there will be quite a few :)

I'll spend some time getting familiar with your code changes when I get a
chance. I'd like to stay familiar so once you feel this is ready for a PR
we can move swiftly!

**Comment by frbapolkosnik** [comment]
Good stuff!
I'll start testing shortly.
It would be great to integrate the yara rule tester into this sometime in the future. Otherwise, built in versioning and diffing seems like a perfect fit for this use case. 

I'm trying to wrap my head around how a different types of Signatures might be linked together pertaining to the same threat/vulnerability/etc.

**Comment by mgoffin** [comment]
Oh yes. The Yara Rule Tester will absolutely get a "Save as Signature"
button :)

**Comment by mgoffin** [comment]
Couple things I noticed in the code as I checked it out. Figured I'd send
them along!

https://github.com/crits/crits/compare/master...dreardon:new_signature_tlo#diff-214f62e0c716b29a6dd7850035ae835dR82
 - Should probably pick a flag that isn't "-r"

https://github.com/crits/crits/compare/master...dreardon:new_signature_tlo#diff-daba2ac84b5ccc3c0d5a35df3e03deccR23
 - Should pick a key that isn't the same as the one it was copied from

https://github.com/crits/crits/compare/master...dreardon:new_signature_tlo#diff-f72273dd156e115d09d9d1f5603abccfR7
 - I've seen line wraps cause the template to break things like this. might
be worth checking out

https://github.com/crits/crits/compare/master...dreardon:new_signature_tlo#diff-070aab321fa59564cd582a89dbf5c81dR71
 - There's a few places in the template where there's a large string like
this for checking. You'll need to add Signature in there and the other
spot(s)

I think that's really about it after a quick glance. It looks like you ran
`python manage.py collectstatic` which would be one of the things people
generally miss, so that's good :)

**Comment by dreardon** [comment]
Thanks for the quick review. I addressed the top three items; however, I'm having a hard time finding, or understanding, the last one. The link included doesn't go to a piece of the code which I think makes sense for this. Do you mean this file: https://github.com/crits/crits/compare/master...dreardon:new_signature_tlo#diff-070aab321fa59564cd582a89dbf5c81dR57 which contains some strings like "RawDataPCAPCertificateIndicatorEvent"? Thank you again.

**Comment by mgoffin** [comment]
Yep, exactly. Those lines should probably also include "Signature" in them
so that condition will trigger. I think there's at least two places in that
file where we do that large string match.

**Comment by mgoffin** [comment]
Do you think it's at a spot where you'd be willing to throw up a PR and do some final touch-ups on your branch based on the feedback it gets? If it's in a PR I can quickly give it a `git checkout` and try it locally.

I know this is for core, but a head's up that things like the Relationship Service, Timeline Service, and possibly a few others that deal with all TLOs will need some updating to support this.

**Comment by dreardon** [comment]
I think that we'll feel good pushing up a PR at some point early next week. I'm having some internal discussions with the team about metadata. I realize that the CRITs community may have different thoughts that could change the implementation, but I want to make sure that I understand all of our needs first. Thank you for checking in.
