### ISSUE TITLE
Can't take a write lock while out of disk space

### ISSUE THREAD

**Issue by cjdupreez** [crits/crits#639]
I run combine with my CRITs instance once a week. Once the cronjob runs and I access CRITs, I can see in the Dashboard that the new IPs were populated, but as soon as I click 'samples' or various other links within CRITs, an exception get's thrown saying "Can't take a write lock while out of disk space" along with a traceback. Please see attached. When I run df -h on my box, It's clear I'm not out of disk space, yet when I reboot, CRITs runs fine... until the next time Combine runs. Any idea what may be causing this? 

I'm running Python 2.7 on Ubuntu 14.04.3 with CRITs 3.1.0.

![image](https://cloud.githubusercontent.com/assets/5132774/10882838/f9528684-813b-11e5-8a80-efa5ee86a362.png)

Request Method: GET
Request URL: https://x.x.x.x/samples/details/73e266ea7f760ab37a02c3678f446fbd/

Django Version: 1.6.11
Python Version: 2.7.6
Installed Applications:
('crits.core',
 'crits.dashboards',
 'django.contrib.auth',
 'mongoengine.django.mongo_auth',
 'django.contrib.contenttypes',
 'django.contrib.messages',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.staticfiles',
 'crits.actors',
 'crits.campaigns',
 'crits.certificates',
 'crits.domains',
 'crits.emails',
 'crits.events',
 'crits.indicators',
 'crits.ips',
 'crits.locations',
 'crits.objects',
 'crits.pcaps',
 'crits.raw_data',
 'crits.relationships',
 'crits.samples',
 'crits.screenshots',
 'crits.services',
 'crits.stats',
 'crits.targets',
 'tastypie',
 'tastypie_mongoengine')
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware')

Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  112.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py" in _wrapped_view
  22.                 return view_func(request, *args, **kwargs)
File "/data/crits/crits/samples/views.py" in detail
  50.                                               format_)
File "/data/crits/crits/samples/handlers.py" in get_sample_details
  132.         remove_user_from_notification("%s" % analyst, sample.id, 'Sample')
File "/data/crits/crits/notifications/handlers.py" in remove_user_from_notification
  473.                          obj_type=obj_type).update(pull__users=username)
File "/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/base.py" in update
  450.             raise OperationError(u'Update failed (%s)' % unicode(err))

Exception Type: OperationError at /samples/details/73e266ea7f760ab37a02c3678f446fbd/
Exception Value: Update failed (exception: Can't take a write lock while out of disk space)

**Comment by mgoffin** [comment]
If this only happens after running Combine, I think the problem would be with something Combine is doing. I would work with them to figure out the issue. It could still be in CRITs, but without knowing what Combine is doing, this would be really hard to diagnose as I can't replicate it.
