### ISSUE TITLE
Add an "Add Related..." button to top of Details pages

### ISSUE THREAD

**Issue by mgoffin** [crits/crits#640]
This button, when clicked, would have a dropdown for every TLO you can add to CRITs. When one is selected, the "Add" form for that TLO is brought up.

The form would have a "Relationship Type" field added to it, but would otherwise be the same "Add" form as normal.

When submitted, the TLO will get added, the relationship will get created, and the Relationships interface in the UI will get refreshed to show the new related TLO.

This would require making changes to handlers to accept relationships for those which don't already support it.

This would also allow us to remove the "Upload Related..." buttons that exist on Samples, Emails, and other Details pages.

**Comment by brlogan** [comment]
This would be great! We currently have a drop-down with the different methods for adding a related Email to an Event, among other things. Bringing it all together and making it more comprehensive would be cool.
