### ISSUE TITLE
How to Add Services?

### ISSUE THREAD

**Issue by cfossace** [crits/crits#643]
I am following these instructions, but I can't manage to add any services 

@mgoffin any ideas?

https://github.com/crits/crits/wiki/Adding-services-to-CRITs

I am just trying to add existing services.  In my forked  "crits" directory, I put the data/crits_services folder. Is this supposed to go here? I have tried putting it other places too and it is still not working.

CRITS tells me the directory settings are successful, but obviously it is not working.  I am not sure if I am not adding the absolute file path wrong, or what is really going wrong.  I keep logging in and out and restarting the server, so no avail.

**Comment by mgoffin** [comment]
- cd /data
- git clone crits_services
- install dependencies for services
- configure /data/crits_services as a service directory in Control Panel
- restart web server

**Comment by cfossace** [comment]
Does it matter where the data folder is in my directory? should it be inside the crits GIT folder or somewhere else?

**Comment by mgoffin** [comment]
Where I noted is the recommended location. If you choose to put it elsewhere you'll need to manage any configuration changes and/or issues that come up from doing so.
