### ISSUE TITLE
fatal: Not a git repository

### ISSUE THREAD

**Issue by jwilczek** [crits/crits#645]
I'm not sure if this is a CRITs issue or not.  Google has been no help thus far.  In trying to verify my installation and configuration, I have been tailing apache's error log.  Each time I access CRITs through a browser I see this error:

fatal: Not a git repository (or any of the parent directories): .git

Anyone know what's causing this?

Thank you!

**Comment by frbapolkosnik** [comment]
Using Apache?

**Comment by jwilczek** [comment]
Yes

**Comment by mgoffin** [comment]
Probably has to do with the Control Panel settings for it being a git repo. It's normally used so people can see the branch and commit they are running from within the UI. Looks like you aren't using a git clone of the repo and just downloaded a zip.

**Comment by jwilczek** [comment]
I cloned from the master branch, ran the bootstrap, and followed the guide exactly.  I have a .git folder in the /data/crits path

**Comment by frbapolkosnik** [comment]
Are you seeing it in the browser? I normally see it in Apache logs, and it probably doesn't have much impact on anything else.

**Comment by jwilczek** [comment]
Nothing in the browser, just the apache error logs.

**Comment by frbapolkosnik** [comment]
CWD for git was not passed, so it would error out when running on Apache.
