### ISSUE TITLE
Generalize Actions

### ISSUE THREAD

**Issue by thelok** [crits/crits#649]
Just so this discussion doesn't get lost from #638 

The intention is to generalize Actions so it is not specifically tied to Indicators but can be applied to any (or most) TLOs.

I pushed up a branch:

https://github.com/thelok/crits-1/tree/initial_generalize_actions

You can review and merge these changes into your branch and continue working from there. I don't intend to finish the rest of the work... I'll leave it up to you guys if you want to change anything.

Diffs here: https://github.com/crits/crits/compare/master...thelok:initial_generalize_actions?expand=1

The biggest changes is that actions operate on obj_type and obj_id so it can apply to any TLO. Also I widget-ized the actions row widget thingy so that it can be included into any TLO details page.

Lastly there is a new base class CritsActionsDocument in crits/core/crits_mongoengine.py that a TLO needs to extend to get generalized Action functionality. I made Indicator extend this base class so that it Actions still works like before. Instead of picking and choosing which TLOs to extend you can make CritsBaseAttributes extend this class but I don't know if it will cause any issues in the larger scheme of things.

**Comment by thelok** [comment]
I missed some dialogs stuff when trying to add Actions for IPs as a first attempt at making another TLO have actions. I pushed up some code to now handle dialogs.

**Comment by mgoffin** [comment]
Just making sure I follow this properly, this adds the `actions` field to all TLOs, it does not make an `Action` class which has its own collection, linking back to the associated TLO via `object_type` and `object_id` fields?

**Comment by thelok** [comment]
Correct... because Action is NOT a TLO. The actions field would be similar to the "objects" or "sources" field where it is embedded into the object itself.

I would be open to having "Actions" be a TLO itself but I don't see much use for it because it seems weird that it would be relational when it would most of the time refer just to a single object.

**Comment by mgoffin** [comment]
The argument for having it separate is similar to having AnalysisResults be separate, just not the size issue. By having them separate they are easier to query, we can make specific views for listing just Actions, see which are on/off, what TLOs you have no actions for, etc. Also makes it easier to query for them in the API.

**Comment by thelok** [comment]
I'm not opposed to it -- having Actions separate does make searching easier but keep in mind how many tables you need to query by pulling it out of the TLO.

**Comment by thelok** [comment]
I guess what I don't want is to have to copy an Action's ID to my clipboard and then add a relationship to a TLO -- it is not user friendly.

**Comment by mgoffin** [comment]
No relationships required. It would be just like AnalysisResults. You act on a specific TLO so the type/id is added automatically.

**Comment by mgoffin** [comment]
Got this all ready to go. Going to merge my branch into Master and let the issues flow! I've done some testing and it seems to work for me, but I'm sure others will find problems I cannot :)

Thanks for writing all of this code! It worked great!
