### ISSUE TITLE
Login redirection issue

### ISSUE THREAD

**Issue by frbapolkosnik** [crits/crits#652]
I ran into a case where I had a link to a global search: "field:sha256 <SHA256>"

When I was not logged in and clicked on the link, it would redirect me to log-in, but after logging in, the link would land you with an Error showing up on the login page.

If you logged in, and clicked on the link, everything works 100%.

**Comment by mgoffin** [comment]
I believe it has to deal with the encoding to protect the initial redirect, which if it's already encoded before being encoded again, results in an invalid URL.

**Comment by frbapolkosnik** [comment]
ok, this has been fixed.
