### ISSUE TITLE
Failure to process attachments in .msg files

### ISSUE THREAD

**Issue by seanthegeek** [crits/crits#653]
In CRITs 3.1, we could upload an Outlook 2013 .msg file, and everything would get parsed properly, including attachments as samples. Since upgrading to CRITs 4, and tracking the master branch, all .msg uploads that contain any attachment report “Error uploading file”. The email object is still created, and the headers are parsed, but any attachments are missing. .msg files without attachments are processed without any errors.

No output is generated in `crits.log` or the web server error log.

**Comment by frbapolkosnik** [comment]
In this case, I think one of the attachments might be an attached email, for which extraction is not yet supported. The difference between 3.x and 4 is that my changes added the notification that this occurs. So in 3.x and early 4.x the error messages were silently dropped onto the floor.

If you want to test it, try to grab an email that was processed with 3.x and upload it to a recent test instance of 4.x, you should end up with the same results, but the difference should be that in 4.x you'll see the error mesage.

**Comment by seanthegeek** [comment]
Nope. None of the attachments are emails.

**Comment by ckane** [comment]
Hey sean,

I tested this on the latest master with the examples you sent me and it seems to work fine. Are you using the "New Email (Outlook)" or "New Email (EML)" form to upload? I used the EML form (because that's what the file extension you sent me was) and it works fine... samples are created per attachment, and the relationships are constructed.

What version of CRITs are you trying on?

**Comment by seanthegeek** [comment]
D'oh! I didn't notice that Outlook for Mac ouutputs eml files (which work fine), not msg files, like on Windows. I sent you a sample of msgs.

**Comment by seanthegeek** [comment]
I'm using the latest CRITs master

**Comment by frbapolkosnik** [comment]
I'd be interested in taking a look at the .msg files causing this too.

**Comment by ckane** [comment]
K. FWIW you can do the following on the Outlook .msg files to help extract the EML content from the rest of the binary crap, I think, and then upload as EML:
```
strings --encoding=l file.msg
```

**Comment by seanthegeek** [comment]
I finally figured out the problem after troubleshooting a separate issue. It was caused by the `python-magic` Ubuntu package. Not sure when/how it got installed, but it conflicted with what installed via pip, and that version doesn't include the `from_buffer()` method that CRITs uses all over the place.

Yet another reason I'm standing up new servers with Debian stable/testing...
