### ISSUE TITLE
Change ID's of Samples

### ISSUE THREAD

**Issue by crinchiera** [crits/crits#659]
We are using the CRITS API to upload metadata samples to the database. We are trying to upload multiple files from the same folder at once, however when they are uploaded they all receive the same ID and are treated as one sample. Is there a way that we can change the ID of each sample (possibly increment them)?

**Comment by mgoffin** [comment]
ObjectId's are generated by MongoDB and added automatically. They are combination of several factors, one being timestamp of entry, resulting in an ObjectId that is always unique. I think you most likely have a coding issue that isn't doing what you expect.
