### ISSUE TITLE
Negative values on dashboard bucket list collection counts

### ISSUE THREAD

**Issue by johnfellers** [crits/crits#662]
Hello,

I am getting negative value counts on collections for bucket lists on the bucket list overview page. For example when I look at the main bucket list overview page for a particular bucket list it shows a value of '-5' for indicators section. 

If i click on that bucket list to go to the individual bucket list details page it shows that there are 5 indicators listed.

When I query the mongodb directly for db.indicators.count( { "bucket_list" : <bucket list name> } ) it shows a positive value of '5'. I ran the mapreduce and generatenotifications to see if it would update the values correctly but no luck.

I attempted to look at the mongo documentation and search the internet for a clue but have not found anything as of yet.

anyone have an idea on this?

**Comment by thelok** [comment]
Did you run the `python manage.py bucket_counts` command?

**Comment by johnfellers** [comment]
good point! i knew i was missing something... For whatever reason when i looked at the manage.py I kept overlooking that one. thank you.
