### ISSUE TITLE
Not able to run bootstrap

### ISSUE THREAD

**Issue by atul2651** [crits/crits#663]
Hi All,

I am new to crits and i wanted to use it due to some requirement.
As per instructions, i installed 64 bit ubuntu 15.10 64 bit on vmware workstation. and i ran sh /script/bootstrap. I got following error :-1:

: not foundstrap: 9: script/bootstrap: 
: not foundstrap: 19: script/bootstrap: 
: not foundstrap: 21: script/bootstrap: {
Testing Computer's Architecture
script/bootstrap: 44: script/bootstrap: Syntax error: "elif" unexpected (expecting "then")

Its like i stuck at first step itself.

Please let me know do i need to install anything else ?
Please guide me.

Thanks.

**Comment by frbapolkosnik** [comment]
Hi and thanks for reporting! 
Did you use git?

**Comment by frbapolkosnik** [comment]
Perhaps you meant to run:
cd /data/crits
sh ./script/bootstrap

**Comment by frbapolkosnik** [comment]
Also, are you installing stable_4 or the master?

**Comment by atul2651** [comment]
@frbapolkosnik  It is master, and i used github only.
I tried executing "sh ./script/bootstrap" but no luck. I am getting same error.

Thanks.

**Comment by frbapolkosnik** [comment]
Is it still the case?
