### ISSUE TITLE
Canot able to retrive any results via API from CRITs

### ISSUE THREAD

**Issue by TejaRamachandran** [crits/crits#667]
Hi Guys,

I am trying to GET request from CRITs server via API.

Location is "http://127.0.0.1:8080/api/v1/ips/". But while i tried to GET . I am facing the error response ```<Response [500]>```

Please find the below code used to GET req:

```
import requests
url = 'http://127.0.0.1:8080/api/v1/ips/'
data = {'api_key':'xxxxxxxxxxxxxx','username': 'abcd'}
r = requests.get(url, data=data , verify=False)
print (r)
```
My requirement is to get values from CRITs server via API.
I tried the some other locations also like "domains,indicators etc.," same response 500 as for IP's. I am new to python please correct me if am wrong.

**Comment by TejaRamachandran** [comment]
Hi Guys,

I tried below code its working
```
import requests
url = 'http://127.0.0.1:8080/api/v1/ips/'
data = {'api_key':'638558d8afa1c17b6aec54fdf363eb3ee16e285c','username':'tej'}
r = requests.get(url, data=data)
print (r.text)
```
output is :

```
root@prabhu:/CRITs/API# python testapi.py 
{"error_message": "GET", "traceback": "Traceback (most recent call last):\n\n  File \"/usr/local/lib/python2.7/dist-packages/tastypie/resources.py\", line 195, in wrapper\n    response = callback(request, *args, **kwargs)\n\n  File \"/usr/local/lib/python2.7/dist-packages/tastypie/resources.py\", line 426, in dispatch_list\n    return self.dispatch('list', request, **kwargs)\n\n  File \"/usr/local/lib/python2.7/dist-packages/tastypie_mongoengine/resources.py\", line 388, in dispatch\n    assert request.method.lower() in ('put', 'post', 'patch'), request.method\n\nAssertionError: GET\n"}
root@prabhu:/CRITs/API# 
````

**Comment by dsnellgrove** [comment]
The data argument in the requests library is used for sending data in put/post HTTP verbs. You meant to use the params argument to encode the dictionary as URL parameters instead. http://docs.python-requests.org/en/latest/user/quickstart/#passing-parameters-in-urls

**Comment by TejaRamachandran** [comment]
Thanks @dsnellgrove params works fine.
