### ISSUE TITLE
Cannot open details on IPs since upgrade

### ISSUE THREAD

**Issue by cjdupreez** [crits/crits#677]
I recently upgraded my CRITs instance to the latest version via git pull and now it seems I can't open a large portion of my previously submitted IPs. When I click on details, I get the following response:

Request Method: GET
Request URL: https://x.x.x.x/ips/details/85.128.142.31/

Django Version: 1.6.1
Python Version: 2.7.6
Installed Applications:
('crits.core',
 'crits.dashboards',
 'django.contrib.auth',
 'mongoengine.django.mongo_auth',
 'django.contrib.contenttypes',
 'django.contrib.messages',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.staticfiles',
 'crits.actors',
 'crits.campaigns',
 'crits.certificates',
 'crits.domains',
 'crits.emails',
 'crits.events',
 'crits.indicators',
 'crits.ips',
 'crits.locations',
 'crits.objects',
 'crits.pcaps',
 'crits.raw_data',
 'crits.relationships',
 'crits.samples',
 'crits.screenshots',
 'crits.services',
 'crits.signatures',
 'crits.stats',
 'crits.targets',
 'tastypie',
 'tastypie_mongoengine')
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware')

Traceback:
File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  112.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/lib/python2.7/dist-packages/django/contrib/auth/decorators.py" in _wrapped_view
  22.                 return view_func(request, *args, **kwargs)
File "/data/crits/crits/ips/views.py" in ip_detail
  68.                                           analyst)
File "/data/crits/crits/ips/handlers.py" in get_ip_details
  163.         ip.sanitize("%s" % analyst)
File "/data/crits/crits/core/crits_mongoengine.py" in sanitize
  2441.                     self.sanitize_relationships(username, sources)
File "/data/crits/crits/core/crits_mongoengine.py" in sanitize_relationships
  2394.                             source__name__in=sources).only('id').first()
File "/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/base.py" in first
  256.             result = queryset[0]
File "/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/base.py" in __getitem__
  151.                                                 _auto_dereference=self._auto_dereference)
File "/data/crits/crits/core/crits_mongoengine.py" in _from_son
  461.                 doc.migrate()
File "/data/crits/crits/indicators/indicator.py" in migrate
  115.         migrate_indicator(self)
File "/data/crits/crits/indicators/migrate.py" in migrate_indicator
  8.     migrate_3_to_4(self)
File "/data/crits/crits/indicators/migrate.py" in migrate_3_to_4
  20.         self.lower = self.value.lower()

Exception Type: AttributeError at /ips/details/85.128.142.31/
Exception Value: 'NoneType' object has no attribute 'lower'

I'm aware of the upgrade.py -a -s command but not sure if I need to run it or not as I didn't 'migrate' my instance anywhere. Would running it possibly solve my issue?

Thanks in advance,
-Cornel.

**Comment by mgoffin** [comment]
You have an Indicator in your database with no value assigned to it. You can remove it using mongo shell.

**Comment by cjdupreez** [comment]
Ok great, is there any way of identifying other indicators with no values assigned? And do you happen to know how this happened so I can prevent it in the future?

Thanks,
-Cornel.

**Comment by ManoftheSea** [comment]
Thread necromancy, but I've got something that may be related:
I had a similar error appear when trying to pull up an email's detail page.  In the call trace (which I've now lost), it has a problem with an indicator: Exception Value: 'NoneType' object has no attribute 'lower'.

In mongo shell, I pull up the indicator by ObjectId, and I find a fully formed, schema version 3, indicator.  In my backtrace, the local variable for "son" has only ObjectId and Schema_version.  Thus, I believe when it tries to instantiate the Indicator from the SON, it gets a lot of empty values.

So, I go to the indicator's details page.  No problem, comes up.  In Mongo shell, I see my object now has schema version 4 (and I infer that migration happened successfully).  Back to the email page, and that comes up successfully too.

I conclude that retrieving the object as part of a different details page is getting incomplete data, breaking the migration.  But I don't know where the doc.reload() should be called.

**Comment by packet-rat** [comment]
Brad Logan can help you fix this.  We had the same issue with 100s of objects (widespread) and Brad fixed them all.

Patrick Maroney
Cell: (609)841-5104


On Jun 6, 2016, at 3:14 PM, Derek <notifications@github.com> wrote:

Thread necromancy, but I've got something that may be related:
I had a similar error appear when trying to pull up an email's detail page. In the call trace (which I've now lost), it has a problem with an indicator: Exception Value: 'NoneType' object has no attribute 'lower'.

In mongo shell, I pull up the indicator by ObjectId, and I find a fully formed, schema version 3, indicator. In my backtrace, the local variable for "son" has only ObjectId and Schema_version. Thus, I believe when it tries to instantiate the Indicator from the SON, it gets a lot of empty values.

So, I go to the indicator's details page. No problem, comes up. In Mongo shell, I see my object now has schema version 4 (and I infer that migration happened successfully). Back to the email page, and that comes up successfully too.

I conclude that retrieving the object as part of a different details page is getting incomplete data, breaking the migration. But I don't know where the doc.reload() should be called.

**Comment by ManoftheSea** [comment]
Thank you for the offer, but my PR #757 fixes the issue without needing to run an upgrade each time, as it allows for the JIT update of objects.
