### ISSUE TITLE
Trouble with migrate_3_to_4

### ISSUE THREAD

**Issue by Magicked** [crits/crits#700]
I decided to run with the latest version of stable_4. I was using an older version from last year of the same branch. 

An error was thrown here with the following indicator id:
```
/data/crits/crits/indicators/migrate.py in migrate_3_to_4
        self.lower = self.value.lower() 

<Indicator: SON([('_id', ObjectId('56ccd5e2bcb87f4ccd5741f9')) ...
```
since self.value is None. Tracking it back, it looks like the last time I had data was on (line 2394): 
```
/data/crits/crits/core/crits_mongoengine.py in sanitize_relationships
                            source__name__in=sources).only('id').first() 
```
The indicator with all its relationships are fully populated in the local vars section of the dump. In this section of crits_mongoengine.py, it looks like it is trying to return things my user is allowed to view (based on sources).

```
for r in self.relationships:
                rd = r.to_dict()
                obj_class = class_from_type(rd['type'])
                if r.rel_type not in ["Campaign", "Target"]:
                    obj = obj_class.objects(id=rd['value'],
                            source__name__in=sources).only('id').first() # error here
                else:
                    obj = obj_class.objects(id=rd['value']).only('id').first()
                if obj:
                    final_rels.append(r)
```
The object ID exists in the database and has data. It also has a source.name field that I have access to (my user should actually have access to everything).

I'm not sure where to look at this point. Any pointers?

**Comment by mgoffin** [comment]
When data is this old and needs migrating, there are some instances where a race condition can occur where you are trying to migrate and also access content it's related to that is also migrating.

One way to clear that up is to checkout the "upgrade" management command:

`python manage.py upgrade -h`

I would use `-s` to skip the prep step, and `-i` to migrate only Indicators. Once that's done see if you still have this issue.

**Comment by Magicked** [comment]
Thanks! That worked perfectly. I love easy solutions.
