### ISSUE TITLE
TLO API add_object() does not work as intended

### ISSUE THREAD

**Issue by gleblanc1783** [crits/crits#701]
Been working with @mgoffin on this throughout today. Was able to modify the example code here (https://github.com/crits/crits/pull/664) which doesn't work in the stable_4 branch with the stable_4 dependencies. 

I've gotten pretty far with it but here's my problem:

```
        newAction = {
                'object_type': objectType,
                'source': self.source,
                'reference': 'Auto Import Script',
                'value': value,
                'method': 'EMC',
                'action': 'add_object'
        }
        data = {
                'action': 'add_object',
                'tlo_action': newAction
        }
            params = {'api_key': self.critsAPIKey, 'username': self.critsUsername}
            request = requests.patch(self.critsURL + apiEndpoint + "/" + critsID + "/",  data=data, params=params, verify=False)

```

Here's the response I am getting back (it's a 200?)
`{"message": "add_object() takes at least 7 arguments (6 given)", "type": "Indicator", "return_code": 1, "id": "56ce4bd666b39378b0d21017"}`

Things I've tried:

1. In the above sample code HTTP Accept headers are supplied. I tried this and I get a JSON decode error (can paste here if needed)
2. In the above sample code @armtash doesn't end the URL with a '/' character and it gives a tastypie-mongoengine error about the PATCH request.

I'm sort of at a loss today. I've been seemingly starting at these three files all day and the solution is probably staring me in the face.

**Comment by armtash** [comment]
I will take a look at this in an hour or so.

**Comment by armtash** [comment]
I actually didn't expose the "add_object" function to the API in #664.   That had been exposed prior to my changes.

Just to clarify, your goal is to embed on object onto a TLO correct?

If so, it seems like the request does not match what the function is expecting.  You are basing your request on the example for adding an action to an object, which will not work for a function like "add_object".

Take a look at the add_object function: https://github.com/crits/crits/blob/stable_4/crits/objects/handlers.py#L190

You need to include the following **required** fields:
1. type_ (str) - Type of the TLO you are adding this object to.
2. id_ (str) - ID of the TLO you are adding this object to.
3. object_type (str) - ObjectType of the object you are adding
4. source (str) - Source of the object
5. method (str) - Method of the object
6. reference (str) - Reference of the object
7. user (str) - User executing this function.

When using the PATCH API though, you do not need to supply 1, 2, or 7 as these are included for you.

Your request should look similar to the following.  No header needs to be passed.


```
        data = {
                'action': 'add_object',
                'object_type': objectType,
                'source': self.source,
                'method': 'EMC',
                'reference': 'Auto Import Script',
                'value': value,
        }
            params = {'api_key': self.critsAPIKey, 'username': self.critsUsername}
            request = requests.patch(self.critsURL + apiEndpoint + "/" + critsID + "/",  data=data, params=params, verify=False)

```

I have not tested this as I am still at work but I'll give it a go later in the evening.  Keep in mind that I have never used this API call before so there may be something with the function itself that needs to be tweaked.

**Comment by gleblanc1783** [comment]
Yup you are correct. Trying to add an Object to a TLO (this is what we base our alerting/mitigation controls off of. I understand Objects were typically STIX-ish in nature and not intended for this but we've been doing this since we started using CRITs. It's on my road map to migrate off of Objects to something else -- but I'd still like it to work as intended.

So I made the changes you have above and now I get:
```
        data = {
                'action': 'add_object',
                'object_type': objectType,
                'source': self.source,
                'reference': 'Auto Import Script',
                'value': value,
                'method': 'EMC',
        }
```

And the response I get is:
`{"message": "TLO could not be found", "type": "Indicator", "return_code": 1, "id": "56ce609566b39378b13a99d2"}

And I've definitely been looking at both core/api.py and objects/handlers.py (even trying different debug statements in there too). 
`

**Comment by armtash** [comment]
I found the issue.  

When using the PATCH API, extra arguments are passed to all handler functions.  This is why adding **kwargs is necessary when exposing a handler function to the API.  

One of the extra arguments that is passed is 'obj'.  If you notice, this is a valid parameter for 'add_obj'.  This means that we are passing a valid argument to the function unintentionally.  

There are two ways of solving this, both of which are fairly simple.  

1. Remove the obj argument from all PATCH API requests.  This has the potential to break things if other handlers exposed to the PATCH API actually rely on the 'obj' argument. 

2.  Rename every mention of 'obj' to any other variable name in the 'add_object' function.

I'll submit a pull request to fix this issue.

**Comment by gleblanc1783** [comment]
You're definitely right -- great catch. I tested out the modified objects/handlers.py file and it works successfully. Do you think that the current solution is the best? I'll wait to close the issue before we figure that out.

**Comment by armtash** [comment]
When I exposed other handlers to the PATCH API I had to do the same thing when conflicts such as these were found.  

In my notes in #664, you can see that one of the steps I took was to rename arguments which would have conflicted with PATCH requests.  

It is in guideline 3 and 4 : 

>3 Each handler function should be passed "id_", "type_", "user", and "**kwargs" at a minimum. Functions that use similar arg names are renamed ("object_id" -> "id_", "analyst" -> "user") **kwargs is necessary to account for additional arguments which are passed to these functions.
> 
>4 Any function with "action" as an argument needs to be renamed. This conflicts with the "action" that is passed in an API call.
