### ISSUE TITLE
AttributeError when building relationships with the API

### ISSUE THREAD

**Issue by Magicked** [crits/crits#704]
Edit: Oops, I said TypeError when I meant AttributeError...

I'm currently receiving the following error when building relationships with the API with the latest stable_4.

> Error with status code 500 and message {"error_message": "'MetaDict' object has no attribute 'get_all_field_names'", "traceback": "Traceback (most recent call last):
> 
>   File \"/usr/local/lib/python2.7/dist-packages/tastypie/resources.py\", line 220, in wrapper
>     response = callback(request, *args, **kwargs)
> 
>   File \"/usr/local/lib/python2.7/dist-packages/tastypie/resources.py\", line 460, in dispatch_detail
>     return self.dispatch('detail', request, **kwargs) 
> 
>   File \"/usr/local/lib/python2.7/dist-packages/tastypie_mongoengine/resources.py\", line 430, in dispatch
>     return self._wrap_request(request, lambda: super(MongoEngineResource, self).dispatch(request_type, request, **kwargs
> 
> ))
> 
>   File \"/usr/local/lib/python2.7/dist-packages/tastypie_mongoengine/resources.py\", line 393, in _wrap_request
>     return fun()
> 
>   File \"/usr/local/lib/python2.7/dist-packages/tastypie_mongoengine/resources.py\", line 430, in <lambda>
>     return self._wrap_request(request, lambda: super(MongoEngineResource, self).dispatch(request_type, request, **kwargs))
> 
>   File \"/usr/local/lib/python2.7/dist-packages/tastypie/resources.py\", line 483, in dispatch
>     response = method(request, **kwargs)
> 
>   File \"/usr/local/lib/python2.7/dist-packages/tastypie/resources.py\", line 1662, in patch_detail
>     obj = self.cached_obj_get(bundle=basic_bundle, **self.remove_api_resource_names(kwargs))
> 
>   File \"/usr/local/lib/python2.7/dist-packages/tastypie/resources.py\", line 1174, in cached_obj_get
>     cached_bundle = self.obj_get(bundle=bundle, **kwargs)
> 
>   File \"/data/crits/crits/core/api.py\", line 552, in obj_get
>     return super(CRITsAPIResource, self).obj_get(bundle=bundle, **kwargs)
> 
>   File \"/usr/local/lib/python2.7/dist-packages/tastypie_mongoengine/resources.py\", line 568, in obj_get
>     return super(MongoEngineResource, self).obj_get(bundle=bundle, **kwargs)
> 
>   File \"/usr/local/lib/python2.7/dist-packages/tastypie/resources.py\", line 2134, in obj_get
>     field_names = self._meta.object_class._meta.get_all_field_names()
> 
> AttributeError: 'MetaDict' object has no attribute 'get_all_field_names'\n"} between these indicators: 56cf211d35cf5369e62d041e <-> 56cf211c35cf5369eab5c8c6`

Here is the relevant section of the code:

```
def submit_relationship(left_type, left_id, right_type, right_id, rel_type, rel_date, rel_confidence, rel_reason):
    type_trans = type_translation(left_type)
    submit_url = '{}/{}/{}/'.format(url, type_trans, left_id)
    headers = {
        'Content-Type' : 'application/json',
        }

    params = {
        'api_key' : api_key,
        'username' : analyst,
        }

    data = {
        'action' : 'forge_relationship',
        'right_type' : right_type,
        'right_id' : right_id,
        'right_class' : right_type,
        'rel_type' : rel_type,
        'rel_date' : rel_date,
        'rel_confidence' : rel_confidence,
        'rel_reason' : rel_reason
    }

    print('Submitting patch url: {}'.format(submit_url))
    print('Data is: {}'.format(data))
    r = requests.patch(submit_url, params=params, data=data, verify=False)
```

Here is some extra print out data:

Submitting patch url: https://[crits_host]/crits/api/v1/indicators/56cf211d35cf5369e62d041e/
Data is: {'rel_type': 'Related To', 'right_class': 'Event', 'rel_date': datetime.datetime(2016, 2, 29, 11, 59, 25), 'rel_confidence': 'high', 'right_id': '56cf211c35cf5369eab5c8c6', 'action': 'forge_relationship', 'rel_reason': 'Related during automated import', 'right_type': 'Event'}

Any ideas? Thanks!

**Comment by Magicked** [comment]
Additional information. I wrote out the contents of bundle before the return statement on line 552 of crits/core/api.py. It looks like it is empty (there should be at least some data for this indicator object).

> <Bundle for obj: '<Indicator: SON([('status', u'New'), ('created', datetime.datetime(2016, 2, 29, 15, 23, 33, 975440)), ('modified', datetime.datetime(2016, 2, 29, 15, 23, 33, 975490)), ('schema_version', 0), ('actions', []), ('source', []), ('tickets', []), ('bucket_list', []), ('campaign', []), ('locations', []), ('objects', []), ('relationships', []), ('releasability', []), ('screenshots', []), ('sectors', []), ('activity', []), ('confidence', SON([('rating', u'unknown')])), ('impact', SON([('rating', u'unknown')])), ('threat_type', u'Unknown'), ('attack_type', u'Unknown')])>' and with data: '{}'>

**Comment by mgoffin** [comment]
Update to django-tastypie 0.13.3.
