### ISSUE TITLE
mongoengine0.9.0

### ISSUE THREAD

**Issue by songlong** [crits/crits#715]
1.   def _from_son(cls, son, _auto_dereference=True, only_fields=None, created=False)
2、setting.py
SESSION_ENGINE = 'mongoengine.django.sessions'
SESSION_SERIALIZER = 'mongoengine.django.sessions.BSONSerializer'
3

**Comment by apolkosnik** [comment]
All that in settings.py?

**Comment by frbapolkosnik** [comment]
Oh, I see... #1 is for crits_mongoengine.py, the rest is settings.py. Just tested, I'll create a PR shortly. Thanks songlong!

**Comment by frbapolkosnik** [comment]
#716 created to address this.

**Comment by songlong** [comment]
using not admin database name in admin authentication 
db.authenticate(settings.MONGO_USER, settings.MONGO_PASSWORD, source='admin')
connect(MONGO_DATABASE, host=MONGO_HOST, port=MONGO_PORT, read_preference=MONGO_READ_PREFERENCE, ssl=MONGO_SSL,
            username=MONGO_USER, password=MONGO_PASSWORD, authentication_source='admin

**Comment by frbapolkosnik** [comment]
Songlong, I'm not sure what you are trying to say here. I've noticed that pymongo supports delegated authentication:
http://api.mongodb.org/python/current/examples/authentication.html#delegated-authentication
Is that what you wanted to add there?

**Comment by songlong** [comment]
yes
