### ISSUE TITLE
Error when going to the last page (by clicking on the last page button with numbers) in samples

### ISSUE THREAD

**Issue by frbapolkosnik** [crits/crits#717]
ERROR: The field 'name' does not exist on the document 'EmbeddedObject'. Sort performed on: -created

THis manifested once I figured out that I can bump up the sort buffer limit from 32MB to 64MB by using the following in the mongo shell:
db.adminCommand({setParameter: 1, internalQueryExecMaxBlockingSortBytes: <limit in bytes>})
Now I can go to the page before the last without erroring out.

**Comment by mgoffin** [comment]
This seems like more of a "be careful what you are doing and tweak this to your environment" type setting. Probably worth documenting but not enforcing as part of the installation?

**Comment by apolkosnik** [comment]
I think that it would be good for awareness, at least to solve an actual problem when it shows up in places like audit log or even sample listing. 

 I doubled, because I didn't have much free time to find a sweet spot for my instance, but I figured that I had enough free memory and swap in case it goes terribly wrong.

I'll try to track down the pagination bug when I find some spare time.

**Comment by frbapolkosnik** [comment]
ERROR: The field 'reference' does not exist on the document 'EmbeddedSource'. Sort performed on: domain

**Comment by frbapolkosnik** [comment]
ERROR: The field 'type' does not exist on the document 'Event'. Sort performed on: -created

**Comment by geekthlete** [comment]
@frbapolkosnik Did you ever solve this? I have the same issue, but didn't modify the buffer limit.

**Comment by apolkosnik** [comment]
It looks like the buffer thing is a runtime thing, and you need to set it again after restarting mongo. I guess the alternative might be to add some indices there (but don't quote me on that).

**Comment by frbapolkosnik** [comment]
A little update on this. Apparently the change needs to be done after every restart of the database.
Also, I've noticed that even doubling the buffer was not sufficient at some point (with ~30k samples). Perhaps adding an index might fix that.

**Comment by frbapolkosnik** [comment]
The permanent fix is to add an indexes.  
In mongo shell:
```use crits
db.sample.createIndex({'created':1 }, {background:true})
db.sample.createIndex({'status':1 }, {background:true})
db.sample.createIndex({'favorite':1 }, {background:true})
```

**Comment by frbapolkosnik** [comment]
Well, #808 should take care of this if you run 
```python manage.py create_indexes```
