### ISSUE TITLE
Login SESSION_KEY:  value must be an integer

### ISSUE THREAD

**Issue by thelok** [crits/crits#720]
Installed Django 1.8.11. Trying to login to CRITs with a remote user yields the following 500 error related to SESSION_KEYs:

```
[Thu Mar 17 15:14:50 2016] [error] [client ...]   File ".../lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 59, in _get_user_session_key
[Thu Mar 17 15:14:50 2016] [error] [client ...]     return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
[Thu Mar 17 15:14:50 2016] [error] [client ...]   File ".../lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 969, in to_python
[Thu Mar 17 15:14:50 2016] [error] [client ...]     params={'value': value},
[Thu Mar 17 15:14:50 2016] [error] [client ...] ValidationError: [u"'521238e4550671234123c1' value must be an integer."]
```

I see a bunch of comments in core/user.py and core/handlers.py and some changes in settings.py with the middleware stuff in addition to a custom middleware class in user.py.

Tried making a bunch of permutations and fiddling with the MIDDLEWARE_CLASSES but nothing seems to work.

Is there no workaround right now because of mongoengine?

https://github.com/crits/crits/blob/master/crits/core/handlers.py#L3363

**Comment by frbapolkosnik** [comment]
Are you on master?

**Comment by mgoffin** [comment]
And using mongoengine 0.8.8?

**Comment by thelok** [comment]
Tried both master and stable_4 with 0.8.8 on both branches.

**Comment by frbapolkosnik** [comment]
Take a look there:
https://github.com/crits/crits/blob/master/crits/core/handlers.py#L3369

**Comment by frbapolkosnik** [comment]
We override the django piece, because mongoengine makes us do so.

**Comment by thelok** [comment]
Holy crap I think I just found it:

--- a/crits/settings.py
+++ b/crits/settings.py
@@ -474,9 +474,10 @@ if REMOTE_USER:
         'django.middleware.common.CommonMiddleware',
         'django.contrib.sessions.middleware.SessionMiddleware',
         'django.contrib.auth.middleware.AuthenticationMiddleware',
-        'django.contrib.auth.middleware.RemoteUserMiddleware',
+        'django.middleware.csrf.CsrfViewMiddleware',
         'django.contrib.messages.middleware.MessageMiddleware',
         'django.middleware.clickjacking.XFrameOptionsMiddleware',
+        'crits.core.user.AuthenticationMiddleware',
     )

**Comment by frbapolkosnik** [comment]
Looks like it

**Comment by frbapolkosnik** [comment]
Is that list the same for non REMOTE_USER?

**Comment by thelok** [comment]
Alright so I added RemoteUserMiddleware back in and it breaks the login with the same error.

**Comment by thelok** [comment]
Yes, I just copied and pasted it from the non REMOTE_USER block.

**Comment by frbapolkosnik** [comment]
Try this:

    MIDDLEWARE_CLASSES = (
        'django.middleware.common.CommonMiddleware',
        'django.contrib.sessions.middleware.SessionMiddleware',
        'django.contrib.auth.middleware.AuthenticationMiddleware',
        'django.middleware.csrf.CsrfViewMiddleware',
        'django.contrib.auth.middleware.RemoteUserMiddleware',
        'django.contrib.messages.middleware.MessageMiddleware',
        'django.middleware.clickjacking.XFrameOptionsMiddleware',
        'crits.core.user.AuthenticationMiddleware',
    )
    AUTHENTICATION_BACKENDS = (
        'crits.core.user.CRITsRemoteUserBackend',
    )

**Comment by thelok** [comment]
That causes the same error. Something weird is going on with the RemoteUserMiddleware

**Comment by razuz** [comment]
just started to debug this myself and @thelok diff solves it.
running on the lastest master and mongoengine 0.9.0

**Comment by frbapolkosnik** [comment]
Downgrade to mongoengine 0.8.8, there are issues that will bite you with 0.9.0.

**Comment by razuz** [comment]
did that just now, didn't go better :
----
Django Version:	1.8.11
Exception Type:	ValidationError
Exception Value:	
[u"'560d8c74ad951d17175559bb' value must be an integer."]
Exception Location:	/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py in to_python, line 969
Python Executable:	/usr/bin/python
Python Version:	2.7.6
----

root@crits2:/data/crits/crits# pip list | grep mongo
django-tastypie-mongoengine (0.4.6)
mongoengine (0.8.8)
pymongo (2.7.2)

**Comment by thelok** [comment]
So , this will be fine as a workaround, but we really need to understand why RemoteUserMiddleware is causing this issue. Maybe we need to inherit from RemoteUserBackend somewhere in crits.core.user.CRITsRemoteUserBackend as suggested by https://docs.djangoproject.com/en/1.8/howto/auth-remote-user/

**Comment by thelok** [comment]
Source code helps https://github.com/django/django/blob/stable/1.8.x/django/contrib/auth/middleware.py

**Comment by frbapolkosnik** [comment]
This thing does it for the normal case:
https://github.com/crits/crits/blob/master/crits/core/user.py#L888

**Comment by frbapolkosnik** [comment]
do you guys have 'crits.core.user.AuthenticationMiddleware', at the bottom of MIDDLEWARE_CLASSES ?

**Comment by razuz** [comment]
yes

**Comment by razuz** [comment]
btw ... it works like that 

`if REMOTE_USER:
    MIDDLEWARE_CLASSES = (
        'django.middleware.common.CommonMiddleware',
        'django.contrib.sessions.middleware.SessionMiddleware',
        'django.contrib.auth.middleware.AuthenticationMiddleware',
        'django.middleware.csrf.CsrfViewMiddleware',
        'django.contrib.messages.middleware.MessageMiddleware',
        'django.middleware.clickjacking.XFrameOptionsMiddleware',
        'crits.core.user.AuthenticationMiddleware',
        'django.contrib.auth.middleware.RemoteUserMiddleware',
    )
    AUTHENTICATION_BACKENDS = (
        'crits.core.user.CRITsRemoteUserBackend',
    )
`

**Comment by frbapolkosnik** [comment]
I guess that makes sense, since RemoteUserMiddleware will use the custom functions now.

BTW. This change in Django is causing this mess:

https://github.com/django/django/commit/596564e808089f1263469dbf4744dcaa05b79222#diff-82ec6fd74a1cab41408fbf5bf0998f58

**Comment by thelok** [comment]
Nice find, so is this considered the proper fix? to include crits.core.user.AuthenticationMiddleware before the RemoteUserMiddleware?

**Comment by razuz** [comment]
@thelok does this patch work for you aswell ?
https://github.com/razuz/crits/commit/e9a7546fe66e2d0fa28e1689ac777ef39b913ca4

the crsf there doesn't make any difference for me

**Comment by thelok** [comment]
@razuz I can't try it right now because I reverted back to django <1.7 and stable_4 to test for our CRITs upgrade. I'll try it either tomorrow if our testing goes well or on Monday.

**Comment by frbapolkosnik** [comment]
Looks like that's it, until somebody comes up with a better fix. ;-)

**Comment by thelok** [comment]
Tried it and it works. Should merge in your fix but should also include the CSRF stuff in there too while we're already here. I don't see why we wouldn't include it unless someone knows any better?

```
django.middleware.csrf.CsrfViewMiddleware
```

**Comment by frbapolkosnik** [comment]
Good enough for a temporary solution.

**Comment by razuz** [comment]
added crsf back aswell ... shall I make a PR ?
https://github.com/crits/crits/compare/master...razuz:master

**Comment by apolkosnik** [comment]
Go ahead
