### ISSUE TITLE
CRITs API Error

### ISSUE THREAD

**Issue by jwilczek** [crits/crits#728]
If you try to add a TLO and don't specify a source, the API reports back a success (message : Success! ... and return_code:0).

However, the domain is not getting added (at least in a way that you can see through the web UI, as it does not show up in the domain list.  Since source is a required field, I think it makes more sense to return an error in this case.

**Comment by frbapolkosnik** [comment]
I suspect that the domain is in the database, but due to missing the source, it's just not being displayed.

**Comment by jwilczek** [comment]
I would bet that is the case as well.  I didn't take the time to verify that as I believe this is an issue regardless of whether it makes it to the database or not.

**Comment by frbapolkosnik** [comment]
I've seen that happening with Combine.
