### ISSUE TITLE
--allow-external removed from pip in 8.0.0

### ISSUE THREAD

**Issue by nosferatu87** [crits/crits#740]
From the changelog

> Deprecate and no-op the --allow-external, --allow-all-external, and --allow-unverified functionality that was added as part of PEP 438. With changes made to the repository protocol made in PEP 470, these options are no longer functional.

This messes with the bootstrap installation

**Comment by apolkosnik** [comment]
Ok, I'll look into that tomorrow.

**Comment by frbapolkosnik** [comment]
It's done, you can close this issue.

**Comment by nosferatu87** [comment]
Thanks!
