### ISSUE TITLE
Upload File Size (Raw)

### ISSUE THREAD

**Issue by systemxcom** [crits/crits#750]
Am I doing this correctly or is the Mongo BSON limit the limit?  And if so, can you put that in the docs?

DocumentTooLarge at /raw_data/upload/
BSON document too large (59209043 bytes) - the connected server supports BSON document sizes up to 16777216 bytes.
Request Method:
POST
Request URL:
http://XXXXXXXXX/raw_data/upload/
Django Version:
1.8.13
Exception Type:
DocumentTooLarge
Exception Value:
BSON document too large (59209043 bytes) - the connected server supports BSON document sizes up to 16777216 bytes.
Exception Location:
/usr/lib64/python2.7/site-packages/pymongo/collection.py in insert, line 409
Python Executable:
/usr/bin/python
Python Version:
2.7.5
Python Path:
[u'/home/crits/crits/crits_services/',
 '/home/crits/crits',
 '/home/crits',
 '/usr/lib/python2.7/site-packages/django_cors_headers-1.1.0-py2.7.egg',
 '/usr/lib64/python27.zip',
 '/usr/lib64/python2.7',
 '/usr/lib64/python2.7/plat-linux2',
 '/usr/lib64/python2.7/lib-tk',
 '/usr/lib64/python2.7/lib-old',
 '/usr/lib64/python2.7/lib-dynload',
 '/usr/lib64/python2.7/site-packages',
 '/usr/lib/python2.7/site-packages']
Server time:
Thu, 12 May 2016 17:26:38 +0300

**Comment by mgoffin** [comment]
MongoDB has a hard limit on documents in a collection which caps at 16MB.
