### ISSUE TITLE
Duplicate Indicators

### ISSUE THREAD

**Issue by brlogan** [crits/crits#759]
I'm having a problem with duplicate Indicators since updating to stable_4. Threat_type and attack_type are now part of the criteria for Indicator uniqueness, but Indicators that existed prior to the code update do not have this field set in the DB.  Therefore, when a user adds an Indicator, even if threat_type and attack_type are left as "Unknown", the new Indicator does not match the existing Indicator and a duplicate Indicator is created. There are several possible fixes to this problem.

The easiest solution would be to remove threat_type and attack_type as criteria for uniqueness.  I'm not sure I'm onboard with two different threat_types signifying two different Indicators. If one user adds an IP as "Malware Victim", and another adds the same IP as "Victim IP Usage", I don't think a new Indicator should be created. Even if more diverse threat_types are selected there is likely going to be duplication of data in the DB or an analyst will have to review multiple Indicators when reviewing a single IP. It just seems messy to me and I wonder if a list field, like that used for "Sectors" would be a better choice.

If threat_type and attack_type are to remain criteria for uniqueness, then one option is to set these two fields for all existing Indicators to "Unknown" using the Indicators migrate.py script.

Alternatively, we can modify the Indicator creation code to check for cases where those fields don't exist with something like this:
```python
    query = Q(ind_type=ind['type']) & Q(lower=ind['lower'])
            & (Q(threat_type=ind['threat_type']) | Q(threat_type__exists=False))
            & (Q(attack_type=ind['attack_type']) | Q(attack_type__exists=False))
    indicator = Indicator.objects(query).first()
```
Then we can set the fields with whatever values have been provided.

If anybody has input on this before I submit a PR, I'd appreciate it. Thanks!

**Comment by mgoffin** [comment]
It would be easiest to probably just set your existing indicators to have default values of "Unknown" for both. Saves on extra query lookup time and such.

This change was intended so that people who leverage indicators for sensor deployment or for historical lookup on usage could separate processing of indicators out into separate instances. Doing a quick search on "type:indicator field:value foo" would yield all foo indicators in the list with information on each ones specific criteria for how it will be used, what type of attack you are expecting if it triggers, as well as a unique C&I. Sources which see that indicator used in a specific way will now be separate from those who see it used differently. Sure, instances where that might occur can be low, but it's already being used in other threat systems this way with huge positive impact.

**Comment by brlogan** [comment]
I can see how it would be beneficial to be able to group certain Indicator attributes by Attack/Threat type, but I think one of the biggest concerns for us is the thought of having to click into several different Indicator details pages just to get the full picture for a particular domain/IP/whatever.  And then if we are enriching some of these Indicators with metadata that applies to all instances of that domain/IP/whatever, we have a bunch of redundant data that we have to add in multiple places.

I am NOT suggesting that we be more STIX-like, but this attack/threat type reminds me of the Observables & Indicators model of STIX.  It would probably be a lot of work, but it might be cool to have an "Observable" view for domain foo that consolidates the information from each of its unique Indicator attack/threat types.  With that an analyst could see everything about domain foo, all in one place.  If an Object or Comment is added to a particular Indicator, it is seen when viewing that Indicator, and in the consolidated view of the Observable, but if the Object or Comment is added to the Observable, it appears in the Observable view AND when viewing every matching Indicator. Thoughts?

In the meantime, should we add something to the Indicator migration script that sets attack_type and threat_type to "Unknown"?

**Comment by Magicked** [comment]
I wrote a quick script to fix duplicate indicators that worked when we ran into the same issue. It attempts to find most new data (references, relationships, etc.) that were added to the newer duplicate indicator, then add that data to the old indicator. Then it removes the newer indicator.

https://gist.github.com/Magicked/853be281534ca33197172ab09d64f676

You may need to modify it a bit for your needs, but I hope this helps!

**Comment by brlogan** [comment]
@mgoffin: Yes, I think that aligns pretty well with what we were looking for.

I also have a script for de-duplicating Indicators that I wrote years ago and recently updated for stable-4.  Between that script and the one @Magicked shared above, we could probably come up with something.

**Comment by mgoffin** [comment]
Ok. I say if someone has time and wants to tackle this that we go forth and
make it happen. Things that we need to do:

- basically dupe the sector code and make it work for Threat Type and
Attack Type
- provide a way to deduplicate indicators
- update the ThreatExchange service to handle importing Threat Type and
Attack Type as well as exporting (picking the first one in the list as the
default in the drop down would be fine)

Also do we want to have a way to track based on source which one provided
the associated types or do we not care? (We don't for sectors so maybe we
don't for this).

**Comment by mgoffin** [comment]
This is done.
