### ISSUE TITLE
Forge_relationship returns 501

### ISSUE THREAD

**Issue by lancemueller** [crits/crits#771]
Apologies if this is covered elsewhere. I have searched the issues and looked at the handler:
[https://github.com/crits/crits/blob/master/crits/relationships/handlers.py#L32](url)

I am trying to use the API to establish a relationship between two TLOs (email and sample).

I can successfully use the API to submit the sample and email information and get the IDs. When I then try and use the forge_relationship patch, I get an 501 error.

The two TLOs exist and I can view them in the UI. I am using this code:

    url = 'https://crits_server/api/v1/emails/577664a672002f04aac6bb5a/'
    params = {'api_key': '<key>','username': 'analyst'}

    data ={	'rel_type': 'Related To', 
		'right_type': 'Samples',
		'right_id': '577664bf72002f04a99c0487', 
		'action': 'forge_relationship'
	  }

    req = requests.post(url, params=params, data=data, verify=False)
    print req

    <Response [501]>
```

Using crits 4-master

**Comment by mgoffin** [comment]
Not sure if it's just a typo, but you are using `requests.post` instead of `requests.patch` in the above example. Is that the issue?

**Comment by lancemueller** [comment]
doh.. not a typo, just a silly oversight. 

after fixing that, I progressed to a new error which was a typo:
<Response [200]>
{"message": "Failed to get right TLO", "type": "Email", "return_code": 1, "id": "577664a672002f04aac6bb5a"}

`'right_type': 'Samples', = 'right_type': 'Sample',`

Thanks for the (super) quick reply.

**Comment by mgoffin** [comment]
Glad to help :)
