### ISSUE TITLE
API doesn't allow descrip in Samples

### ISSUE THREAD

**Issue by mike-bailey** [crits/crits#784]
Cannot assign a description to samples via the [Authenticated API](https://github.com/crits/crits/wiki/Authenticated-API) unless I'm missing something. Technically an enhancement.

**Comment by mike-bailey** [comment]
I modified this and fixed it so whenever @mgoffin says they'd actually like this as a feature I can PR it.

**Comment by mgoffin** [comment]
yea that would be a great feature! throw up the PR and we'll take a look!
