### ISSUE TITLE
DefaultType Directive Not Valid in apache2.conf

### ISSUE THREAD

**Issue by kingsalemno** [crits/crits#802]
After installation of Apache2 via the production grade install, the instructions eventually refer the user to copy the .conf files from 'extras'. The apache2.conf file found there has a directive as follows:

DefaultType text/plain

This directive fails on both Ubuntu 14.04 and Ubuntu 16.04

**Comment by mgoffin** [comment]
The instructions note to use those files as a guideline, not as a direct replacement. If folks wish to submit a PR which updates these configs to be "best effort", we can review them. But they should still be considered guidelines. Every server is different, with requirement for different versions of software. It is up to the server admin to assess their needs and setup Apache to work with CRITs appropriately.
