### ISSUE TITLE
Broken CSV and Blob upload

### ISSUE THREAD

**Issue by r3comp1le** [crits/crits#805]
Seems to error on:

> Exception Type: AttributeError at /indicators/upload/
> Exception Value: 'NoneType' object has no attribute 'split'
> Request information:

```
ind['threat_types'] = d.get('Threat Types').split(',')
ind['attack_types'] = d.get('Attack Types').split(',')
```

I removed the .split and it fixed the error for now.  There was no feedback in the GUI, just Error on Upload for the CSV and Blob wouldn't show anything.

**Comment by mgoffin** [comment]
If we don't already, we'll need to add documentation for having those columns (which should also fix your issue), and button up the code to handle situations where the column exists but there are no values in there (default to `Unknown`). Thanks!

**Comment by mgoffin** [comment]
Can you see if this is fixed in the latest master?

**Comment by r3comp1le** [comment]
looks to be working

**Comment by mgoffin** [comment]
Thanks!
