### ISSUE TITLE
Getting Fator Error in AWS Instance - RHEL 7 (pydeep.c:2:19: fatal error: fuzzy.h: No such file or directory)

### ISSUE THREAD

**Issue by TejaRamachandran** [crits/crits#810]
Hi Folks,

I am deploying CRITs in RHEL 7 AWS instance. I tried my best to resolve this issue but couldn't able to find the solution, I am not sure how to install this and resolve this issue. 

Please help me with the installation. Please find the attachment of error logs from the instance. 

If more information required from my side. Please let me know - I will upload ASAP. 

[Error Logs.txt](https://github.com/crits/crits/files/440526/Error.Logs.txt)
Thanks in advance.

**Comment by apolkosnik** [comment]
You are missing ssdeep-devel


Possibly you can try something along the lines of:


$ sudo yum groupinstall "Development Tools" $ sudo yum install epel-release
$ sudo yum install libffi-devel python-devel python-pip ssdeep-devel
ssdeep-lib

**Comment by TejaRamachandran** [comment]
I tried but, I am getting below error.

# sudo yum install libffi-devel python-devel python-pip ssdeep-devel
Loaded plugins: amazon-id, rhui-lb, search-disabled-repos
Package libffi-devel-3.0.13-16.el7.x86_64 already installed and latest version
Package python-devel-2.7.5-38.el7_2.x86_64 already installed and latest version
Resolving Dependencies
--> Running transaction check
---> Package python-pip.noarch 0:7.1.0-1.el6 will be installed
--> Processing Dependency: python(abi) = 2.6 for package: python-pip-7.1.0-1.el6.noarch
---> Package ssdeep-devel.x86_64 0:2.13-1.el6 will be installed
--> Processing Dependency: ssdeep-libs(x86-64) = 2.13-1.el6 for package: ssdeep-devel-2.13-1.el6.x86_64
--> Processing Dependency: libfuzzy.so.2()(64bit) for package: ssdeep-devel-2.13-1.el6.x86_64
--> Running transaction check
---> Package python-pip.noarch 0:7.1.0-1.el6 will be installed
--> Processing Dependency: python(abi) = 2.6 for package: python-pip-7.1.0-1.el6.noarch
---> Package ssdeep-libs.x86_64 0:2.13-1.el6 will be installed
--> Finished Dependency Resolution
Error: Package: python-pip-7.1.0-1.el6.noarch (epel)
           Requires: python(abi) = 2.6
           Installed: python-2.7.5-38.el7_2.x86_64 (@rhui-REGION-rhel-server-releases)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.5-16.el7.x86_64 (rhui-REGION-rhel-server-releases)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.5-18.el7_1.1.x86_64 (rhui-REGION-rhel-server-releases)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.5-34.el7.x86_64 (rhui-REGION-rhel-server-releases)
               python(abi) = 2.7
               python(abi) = 2.7
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

I tried this earlier, but no luck.

**Comment by apolkosnik** [comment]
Just try to install *ssdeep**-**devel*

**Comment by TejaRamachandran** [comment]
Folks,

In EC2 the installation is little bit different. By default the EPEL Package RPM will be not available. For this we need to install EPEL noarch RPM and install it depend upon your architecture.

EC2-User Please follow below link: 
https://aws.amazon.com/premiumsupport/knowledge-center/ec2-enable-epel/

And then we way good to go.
