### ISSUE TITLE
tld list doesn't support .site tlds?

### ISSUE THREAD

**Issue by mallorybobalice** [crits/crits#838]
hi,

can this please be fixed in the autodownloaded list? 

Thanks

**Comment by apolkosnik** [comment]
I just added test.site as a domain and an indicator on 4-master, is there a problem somewhere else?
Which version of CRITs are you running?

**Comment by mgoffin** [comment]
Probably just needs to update the TLP list and hasn't done it in a long time?

**Comment by mallorybobalice** [comment]
ah ok thanks i thought the list auto updates.

Updated it from the UI - seemed fine, could add the tld i needed, but after that noticed- domains from the UI are no longer sortable

https://<snip>/domains/list/jtlist/?jtStartIndex=0&jtPageSize=25&jtSorting=domain%20ASC Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR)

had to revert the server for now. Will have to get the 'more admin' crits people to have a look.(not even sure where the server side logging is)
version looks pretty old 4-master https://github.com/crits/crits/commit/b06851f9db908fa1da79bed1c61c1d2070c2cfaf in fact it can no longer find the commit :| ?

**Comment by mallorybobalice** [comment]
alright, so sorted this as well - this was caused by spaced in loaded tlds (not really tld update).
updated the tlds at the end. 

thanks again for the help.
