### ISSUE TITLE
Unable to upload a sample with API, at least md5 has is required

### ISSUE THREAD

**Issue by sparrowd** [crits/crits#843]
Using the following code, I return the following error: {"message": "At least MD5 hash is required.", "type": "Sample", "return_code": 1}

import requests
url ='http://my url/api/v1/samples/'
files = {'filedata':open('file to be uploaded', 'rb')}
data = {
'api_key':'my api key',
'username':'my user name',
'source':'my source',
'upload_type':'file',
'file_format':'raw',
}
r = requests.post(url,data=data,files=files)
print r.text

I have tried to add in 'md5':'md5 of file', but I received the same error. Any assistance would be greatly appreciated.

**Comment by apolkosnik** [comment]
try this:
files = { 'filedata': ('attachment', open('file to be uploaded', 'rb').read())}

**Comment by apolkosnik** [comment]
and replace that period with coma at the end of line with source...

**Comment by sparrowd** [comment]
That period is a typo, I have this on a off net testing machine and typed that code by hand. Sorry about that.

**Comment by sparrowd** [comment]
Even with your chance I am still getting {"message": "At least MD5 hash is required.", "type": "Sample", "return_code": 1}

**Comment by sparrowd** [comment]
Figured out the issue. The file I was trying to upload as a test file was an empty file. If the file is empty, it seems to return this error. Once I fed it a file with any data in it, the file would upload.
