### ISSUE TITLE
Login broken

### ISSUE THREAD

**Issue by seanthegeek** [crits/crits#865]
I recently did a git pull to update our CRITs instance, and now whenever any user attempts to login, it just says wait 10 seconds, but without the bad username and password message. So the creds are good. I'm not sure what commit broke it.

**Comment by apolkosnik** [comment]
Can you look with developer tools in your browser for any error messages?

**Comment by apolkosnik** [comment]
Also, can you get us some env info and provide output:
```pip freeze | grep ngo```

**Comment by seanthegeek** [comment]
Chrome console

> toast_notifications.js:160 Uncaught ReferenceError: initial_notifications_display is not defined(…)


> Django==1.8.16
> django-celery==3.1.17
> django-debug-toolbar==1.6
> django-debug-toolbar-mongo==0.1.10
> django-debug-toolbar-template-profiler==1.0.1
> django-debug-toolbar-template-timings==0.6.6
> django-debug-toolbar-vcs-info==1.2.0
> django-mongoengine==0.2.1
> django-ratelimit==0.6.0
> django-tastypie==0.13.3
> django-tastypie-mongoengine==0.4.6a0
> mongoengine==0.10.6
> pymongo==3.2.2
>

**Comment by apolkosnik** [comment]
We did add the debug toolbars, did you follow steps outlined in UPDATING?

**Comment by apolkosnik** [comment]
Sorry, I just saw the toolbars in the output. Can you try to temporarily move services to a different location, so that we can see if it runs ok without the services present?

**Comment by seanthegeek** [comment]
Removed services. Still broken.

**Comment by seanthegeek** [comment]
Never mind. I had a python dependency conflict.
