### ISSUE TITLE
Customize Navigation UI

### ISSUE THREAD

**Issue by lancemueller** [crits/crits#868]
I would like to hide some of the TLOs listed within the UI, what would be the best recommended way to accomplish that?  We are not using several of the TLOs at the moment and I would like to remove them from the navigation/menu sidebar for the time being but may eventually bring them back so I am looking for the best recommended way to visually remove them, but not necessary remove their functionality.

**Comment by mgoffin** [comment]
There is no functionality to do this currently. The Roles PR handles this, though, but that is still in testing.
