### ISSUE TITLE
Disable Indicator TLO from automatically creating IP/Domains records

### ISSUE THREAD

**Issue by lancemueller** [crits/crits#869]
I would like to disable the automatic creation of a domain and/or IP TLO when creating an indicator (domain,IPv4 Address, URI, etc.).

What would be the recommended way to accomplish this?

**Comment by mgoffin** [comment]
There is no way to do this without modifying the codebase so when an Indicator is generated it doesn't follow up with creating other TLOs and relating them together.

**Comment by lancemueller** [comment]
Thanks Mike, Appreciate your (very) quick responses. Can you point me to where this is handled in the codebase?

**Comment by mgoffin** [comment]
https://github.com/crits/crits/blob/master/crits/indicators/handlers.py#L593

That's the function. There's some bits in there you'll want to comment out. Without actually testing myself, I suspect the code starting around line 753 would be where to look.
