### ISSUE TITLE
PCAP uploads via UI never finish

### ISSUE THREAD

**Issue by apolkosnik** [crits/crits#880]
When uploading the PCAP via UI the upload never finishes (or actually the user is not notified that the upload finished). I think that the same happens on Sample uploads.
![image](https://cloud.githubusercontent.com/assets/1034814/22374387/00a2772c-e474-11e6-8d35-4314e5f8ca72.png)

**Comment by mgoffin** [comment]
Ahh, so it works but the user doesn't get the proper notification?

**Comment by apolkosnik** [comment]
That's correct.

**Comment by apolkosnik** [comment]
Ok, I think I figured it out. X_FRAME_OPTIONS was causing this mess. 
I had:
```
X_FRAME_OPTIONS = 'DENY'
```

It should have been set to:
```
X_FRAME_OPTIONS = 'SAMEORIGIN'
```
