### ISSUE TITLE
Problem with Indicator Activity API

### ISSUE THREAD

**Issue by ericwentz** [crits/crits#892]
I'm trying to use the Indicator Activity API and getting a "500" error from CRITs.  In looking at the source code, the file /crits/indicators/handler.py the function activity_add defines 3 arguments and the api.py module calls this function with only 2 causing the failure.  I ran CRITs in debug mode and verified this issue.

I was able to fix the problem with the following patch in the api.py file:
162c162
<         result = activity_add(object_id, activity, analyst)
---
>         result = activity_add(object_id, activity)

Thanks for your consideration
Eric Wentz
Eaton Corporation

**Comment by mgoffin** [comment]
I believe that's because of the deprecated API call you are using. You should be using the PATCH request to update the Indicator. This line here in the core API provides the functionality:

https://github.com/crits/crits/blob/master/crits/core/api.py#L615

The handler has been appropriately updated to use the argument format required by the PATCH requests in order to function:

https://github.com/crits/crits/blob/master/crits/indicators/handlers.py#L1029

I suspect if you use that, you should be good to go without any code changes.

**Comment by ericwentz** [comment]
Okay - I'll look at the PATCH call - I was just following the docs on the Authenticated API Wiki page - maybe an update here is indicated?
Thanks for your prompt response.

**Comment by ericwentz** [comment]
Okay - tried this with the PATCH function and had trouble:
URL: https://critsdev.etn.com/api/v1/indicators/58dce7104bc0fd086940e575/?username=apiuser&api_key=8cfcbd0885f75d0b7b565c5e976b2ccba976c265
I've got the header field "Content-Type" = "application/json"
and the body of the PATCH is
{"action": "activity_add", "description": "Second Test from API", "end_date": "2017-03-30 012:17:08.063000", "start_date": "2017-02-15 08:17:08.063000"}

I'm getting back a python error:"list indices must be integers, not str"

Do you have any successful examples of doing this PATCH?

Thanks
Eric

**Comment by ericwentz** [comment]
I've been chasing this issue through the code and there *does* seem to be a problem with this patch api - I'll keep digging, but any help would be appreciated.

Thanks
Eric

**Comment by mgoffin** [comment]
Can't tell if you are adding things in params or data, but the wiki has an example or two: https://github.com/crits/crits/wiki/Authenticated-API

**Comment by ericwentz** [comment]
Hi. Yeah, I've followed the API docs to the letter - I've been able to use the PATCH function with the "forge_relationship" action, but the "activity_add" causes the error. I've looked at the function in the code at crits.indicators.handlers.py activity_add - I put some "print" calls in the code and saw that the "activity" argument is a dict type when the function is called from the Web UI - but it's called with a list argument when called from the core.api.py function. the list is a single element array with one instance of EmbeddedActivity - this call causes an error at the line activity['analyst'] = user due to a datatype error.  I honestly believe that there is an error here in the API code - I can provide a detailed example to reproduce the issue if you need it.

I'm not sure who needs to fix this issue - but to me, it's obvious that a correction is necessary.
Thanks
Eric

**Comment by ericwentz** [comment]
I would like to respectfully submit a patch to the problem which I have been working - this would be applied to the crits.indicators.handlers.py file:
[indicators.py.patch.txt](https://github.com/crits/crits/files/889747/indicators.py.patch.txt)

I understand that there may be regression testing necessary which is why I did not just directly modify the module.

Thank you for your consideration.
Eric

**Comment by ericwentz** [comment]
Apologies, the prior post did not contain a properly formatted patch file - attached is the correction
[indicators.patch.txt](https://github.com/crits/crits/files/889753/indicators.patch.txt)

**Comment by mgoffin** [comment]
Thanks! Feel free to submit the patch as an actual PR. It'll be easier for us to test and compare than dealing with a patch file :)

**Comment by ericwentz** [comment]
Thanks again for the quick response - I've submitted the PR for testing
