### ISSUE TITLE
Issue when attempting to download as a zip

### ISSUE THREAD

**Issue by sparrowd** [crits/crits#895]
Alcon,

I set up a second Crits server on a production system (first was a dev system) and when I go to attempt to download a sample from the production server I get the following error. This only happens with zip format and not with JSON. If anyone has any idea it would be greatly appreciated. 

ZipFileError at /object/download/
u' 2 No such file or directory'
Request Method:	POST
Request URL:	hxxps://crits.xxx,xxx/object/download/
Django Version:	1.8.18
Exception Type:	ZipFileError
Exception Value:	
u' 2 No such file or directory'
Exception Location:	/data/crits/crits/core/data_tools.py in create_zip, line 157
Python Executable:	/usr/bin/python
Python Version:	2.7.12
Python Path:	
[u'/crits/crits_services',
 '/data/crits/crits',
 '/data/crits',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages']
Server time:	Wed, 12 Apr 2017 10:50:29 -0400

When looking at the traceback I get the following:

tmp	
'/tmp/tmpWbCnlI/modcalc.exe'
files	
[(u'modcalc.exe',
  'MZ\<trimmed 2419716 bytes string>
i	
1 args	
['/usr/bin/zip', '-r', '-j',
 '/tmp/tmpWbCnlI/zip.zip',
 '/tmp/tmpWbCnlI', '-P', u'infected',
 '/tmp/tmpWbCnlI/zip.zip',
 '/tmp/tmpWbCnlI']
pw_protect True
filename u'modcalc.exe'
file_data	
'MZ\<trimmed 2419697 bytes string>
crits_config	
<CRITsConfig: SON([('_id', ObjectId('58e287307868524516b6b3bf')), ('allowed_hosts', [u'*']), ('classification', u'unclassified'), ('company_name', u'XXXX'), ('create_unknown_user', False), ('crits_message', u''), ('crits_email', u'XXXXX@XXXX.com'), ('crits_email_subject_tag', u''), ('crits_email_end_tag', True), ('crits_version', u'4-master'), ('debug', True), ('depth_max', 10), ('email_host', u''), ('email_port', u''), ('enable_api', False), ('enable_toasts', False), ('git_repo_url', u'https://github.com/crits/crits'), ('http_proxy', u''), ('instance_name', u'XXXX'), ('instance_url', u'xx.xx.xx.xx'), ('invalid_login_attempts', 3), ('language_code', u'en-us'), ('ldap_auth', False), ('ldap_tls', False), ('ldap_server', u''), ('ldap_bind_dn', u''), ('ldap_bind_password', u''), ('ldap_usercn', u''), ('ldap_userdn', u''), ('ldap_update_on_login', False), ('log_directory', u'/crits/crits-master/crits/../logs'), ('log_level', u'INFO'), ('password_complexity_desc', u'8 characters, at least 1 capital, 1 lowercase and 1 number/special'), ('password_complexity_regex', u'(?=^.{8,}$)((?=.*\\d)|(?=.*\\W+))(?![.])(?=.*[A-Z])(?=.*[a-z]).*$'), ('query_caching', False), ('rel_max', 50), ('remote_user', False), ('rt_url', u'xxxxxxxxxxxxxxxxxxxxxxxxx'), ('secure_cookie', True), ('service_dirs', [u'/crits/crits_services']), ('service_model', u'process'), ('service_pool_size', 12), ('session_timeout', 12), ('splunk_search_url', u''), ('temp_dir', u'/tmp'), ('timezone', u'America/New_York'), ('total_max', 250), ('totp_web', u'Disabled'), ('totp_cli', u'Disabled'), ('zip7_path', u'/usr/bin/7z'), ('zip7_password', u'infected')])>
ex	
OSError(2, 'No such file or directory')
CRITsConfig	
<class 'crits.config.config.CRITsConfig'>
dumpdir	
'/tmp/tmpWbCnlI'
path	
'/tmp/tmpWbCnlI/modcalc.exe'
errmsg	
u' 2 No such file or directory'
zip7_password	
u'infected'

**Comment by apolkosnik** [comment]
It looks like your file disappeared. Do you have AV on that box or something?

**Comment by mgoffin** [comment]
I was thinking maybe the zip7_path in Control Panel was improperly set and can't find it when it goes to perform the zip.

**Comment by sparrowd** [comment]
The zip7 path (usr/bin/7z) works just fine as I can unzip files no issue. There is no AV on the box as it is a fresh Ubuntu linux install.

**Comment by sparrowd** [comment]
Figured out the issue. I did not have bin/zip installed, once I installed that it worked fine. Did not realize that Crits uses 7zip for unzipping and zip for downloading.
