### ISSUE TITLE
Cannot create an Admin user with manage.py -A

### ISSUE THREAD

**Issue by froschtv** [crits/crits#919]
I can't create an admin User if i enter:

sudo python manage.py -a -A -u myUsername -e myEmail

The Error is that the option -A is not existing and if i make a -h on manage.py i can't see this option so the documentation has a fault by creating a user.

Well i tried to just create a normal user but then i can't log in to the web ui with this User.

**Comment by apolkosnik** [comment]
please read UPDATING, since roles were added recently

**Comment by froschtv** [comment]
Where do I find UPDATING?

**Comment by froschtv** [comment]
Found it thank you
