### ISSUE TITLE
Error Uploading file - for 7z/zip/rar samples

### ISSUE THREAD

**Issue by soupcanx** [crits/crits#936]
I'm receiving nothing but a "Error uploading file." messages when trying to upload zip/7z/rar archives as samples through the web interface, submitting raw files works fine. Based on what i could find in the crits-users group and here, i've even tried different versions of python-magic, etc based on issues from 2014. The error i see does not seem to match others i could find. I do not see anything in the crits/apache logs nor at the console and this happens on multiple servers (test and prod).

Specifically when i trace through chrome's dev tools i see the following:

Request Method: | POST
-- | --
http://10.1.5.5:8080/samples/upload/
1.8.16
AttributeError
'str' object has no attribute 'get'
/home/forensics/crits/crits/samples/views.py in upload_file, line 294
/usr/bin/python
2.7.6
[u'/home/forensics/crits_services',  '/home/forensics/crits/crits',  '/home/forensics/crits',  '/usr/lib/python2.7',  '/usr/lib/python2.7/plat-x86_64-linux-gnu',  '/usr/lib/python2.7/lib-tk',  '/usr/lib/python2.7/lib-old',  '/usr/lib/python2.7/lib-dynload',  '/usr/local/lib/python2.7/dist-packages',  '/usr/local/lib/python2.7/dist-packages/pyimpfuzzy-0.1-py2.7-linux-x86_64.egg',  '/usr/lib/python2.7/dist-packages',  '/usr/lib/python2.7/dist-packages/PILcompat',  '/usr/lib/python2.7/dist-packages/gtk-2.0',  '/usr/lib/python2.7/dist-packages/ubuntu-sso-client']
Tue, 12 Sep 2017 11:06:33 -0400

running /usr/bin/7z from the commandline on the crits server (using the same files) host works fine and the paths are set correctly in the control panel.

thanks in advance for any assistance!

-- adam

**Comment by mgoffin** [comment]
Can you check to verify it didn't actually upload successfully and there might be faulty code in providing the actual response?

IIRC the form submission via AJAX calls another form to submit and then the JavaScript consumes that response as JSON. If it isn't JSON it errors out which might cause the error you see, but it's possible the sample(s) submitted correctly.

**Comment by soupcanx** [comment]
I can verify that the file is not there through the CRITs interface or on the filesystem. Additionally if i upload with the wrong password, i receive the below:

"Error while extracting archive 7-Zip (A) [64] 9.20 Copyright (c) 1999-2010 Igor Pavlov 2010-11-18 p7zip Version 9.20 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,2 CPUs) Processing archive: /tmp/tmp3t6luG/malware.7z Extracting dc7521c00ec2534cf494c0263ddf67ea4ba9915eb17bdc0b3ebe9e840ec63643.bin Data Error in encrypted file. Wrong password? Sub items Errors: 1"

This makes me think that at some point the actual upload works but the whole transaction fails somewhere and the file isn't added, if that makes sense. 

Appreciate your help!

**Comment by soupcanx** [comment]
This additionally appears to only occur with password protection on the archives, regualr zip files seem to work as expected.

**Comment by soupcanx** [comment]
Unclear on which troubleshooting steps seemed to correct this, likely a transient browser issue as after recent updates to chrome/firefox it seemed to resolve. Had played with permissions on the server, but issue persisted until after the browser settings and software updates. thanks for the time and help.
