### ISSUE TITLE
Problem logging in

### ISSUE THREAD

**Issue by zacharycheng** [crits/crits#940]
I tried to install crits on a new computer. After I following all the steps on the website, the console shows the following error message to me: 

345459 ERROR: Internal Server Error: /login/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/crits/crits/core/views.py", line 433, in login
    logging_in_user.get_access_list(update=True)
  File "/opt/crits/crits/core/user.py", line 978, in get_access_list
    attr = getattr(acl, p)
AttributeError: 'dict' object has no attribute 'ActorIdentifier'
[28/Sep/2017 04:35:42] "POST /login/ HTTP/1.1" 500 22182

and here is the message I have from Chrome:

`AttributeError at /login/'dict' object has no attribute 'ActorIdentifier'`

How can I solve this problem in order to log into crits? Thanks.

**Comment by mgoffin** [comment]
I'm not seeing this error, but with the traceback you provided I can do some digging and see if it might be an edge case you are hitting and I'm not.

Are you on the latest master, or a certain branch?

**Comment by zacharycheng** [comment]
yes, I am using the master one

**Comment by mgoffin** [comment]
I just pushed a new branch `remove_acl_attr`. It's untested but it'll be where I'm trying to remove all of the `setattr` and `getattr` calls with appropriate dictionary operations. It's possible (but unlikely) that it "just works" if you want to try it out!

**Comment by zacharycheng** [comment]
OK, I am going to try that on my computer to see if it could work on it.
