### ISSUE TITLE
Upgrading issue with requirements.txt

### ISSUE THREAD

**Issue by ericwentz** [crits/crits#946]
The most recent version of the crits/requirements.txt file contains an *older* version of both the mongoengine and pymongo files.  My original file was from the 2016-11-03 drop which had:
mongoengine==0.10.6
pymongo==3.2.2 
The 2017-06-20 drop called for older versions of these two packages.
mongoengine==0.8.8
pymongo==2.8.1
When in installed these older versions during my upgrade, CRITs broke.  I put the original ones back and all was well.
Please let me know if you have any questions on this issue.

Eric Wentz

**Comment by mgoffin** [comment]
The reason these packages were dropped back to earlier versions were due to horrific performance loses (primarily fueled by mongoengine).

**Comment by ericwentz** [comment]
hmm - understood, but it seemed to break my installation.  My admin account login stopped working.  Any thoughts on this?

**Comment by ericwentz** [comment]
I'd be happy to.  This is my "dev" CRITs instance, so I can fiddle with it as much as I like :) 
I'll post the logs as soon as I collect them.  Thanks for your prompt response.

**Comment by ericwentz** [comment]
Here is the contents of my /data/crits/logs/crits.log which reflects the error:
DEBUG 2017-10-19 13:08:10,080 crits.core.errors ['Traceback (most recent call last):\n', '  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n', '  File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/views.py", line 120, in logout_then_login\n    return logout(request, login_url, current_app=current_app, extra_context=extra_context)\n', '  File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/views.py", line 81, in logout\n    auth_logout(request)\n', '  File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 135, in logout\n    request.session.flush()\n', '  File "/usr/local/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 276, in flush\n    self.delete()\n', '  File "/usr/local/lib/python2.7/site-packages/mongoengine/django/sessions.py", line 112, in delete\n    MongoSession.objects(session_key=session_key).delete()\n', '  File "/usr/local/lib/python2.7/site-packages/mongoengine/queryset/base.py", line 402, in delete\n    queryset._collection.remove(queryset._query, write_concern=write_concern)\n', '  File "/usr/local/lib/python2.7/site-packages/pymongo/collection.py", line 672, in remove\n    docs, False, self.uuid_subtype, client)\n', '  File "/usr/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 1132, in _send_message\n    rv = self.__check_response_to_last_error(response, command)\n', '  File "/usr/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 1050, in __check_response_to_last_error\n    helpers._check_command_response(result, self.disconnect)\n', '  File "/usr/local/lib/python2.7/site-packages/pymongo/helpers.py", line 182, in _check_command_response\n    raise OperationFailure(msg % errmsg, code, response)\n', 'OperationFailure: unrecognized write concern field: write_concern\n']
DEBUG 2017-10-19 13:10:37,140 crits.core.errors ['Traceback (most recent call last):\n', '  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n', '  File "/data/crits/crits/core/views.py", line 462, in login\n    totp_pass=totp_pass)\n', '  File "/data/crits/crits/core/handlers.py", line 3653, in login_user\n    user_login(request, user)\n', '  File "/data/crits/crits/core/handlers.py", line 3527, in user_login\n    request.session.cycle_key()\n', '  File "/usr/local/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 287, in cycle_key\n    self.delete(key)\n', '  File "/usr/local/lib/python2.7/site-packages/mongoengine/django/sessions.py", line 112, in delete\n    MongoSession.objects(session_key=session_key).delete()\n', '  File "/usr/local/lib/python2.7/site-packages/mongoengine/queryset/base.py", line 402, in delete\n    queryset._collection.remove(queryset._query, write_concern=write_concern)\n', '  File "/usr/local/lib/python2.7/site-packages/pymongo/collection.py", line 672, in remove\n    docs, False, self.uuid_subtype, client)\n', '  File "/usr/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 1132, in _send_message\n    rv = self.__check_response_to_last_error(response, command)\n', '  File "/usr/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 1050, in __check_response_to_last_error\n    helpers._check_command_response(result, self.disconnect)\n', '  File "/usr/local/lib/python2.7/site-packages/pymongo/helpers.py", line 182, in _check_command_response\n    raise OperationFailure(msg % errmsg, code, response)\n', 'OperationFailure: unrecognized write concern field: write_concern\n']
DEBUG 2017-10-19 13:20:35,710 crits.core.errors ['Traceback (most recent call last):\n', '  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n', '  File "/data/crits/crits/core/views.py", line 462, in login\n    totp_pass=totp_pass)\n', '  File "/data/crits/crits/core/handlers.py", line 3653, in login_user\n    user_login(request, user)\n', '  File "/data/crits/crits/core/handlers.py", line 3527, in user_login\n    request.session.cycle_key()\n', '  File "/usr/local/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 287, in cycle_key\n    self.delete(key)\n', '  File "/usr/local/lib/python2.7/site-packages/mongoengine/django/sessions.py", line 112, in delete\n    MongoSession.objects(session_key=session_key).delete()\n', '  File "/usr/local/lib/python2.7/site-packages/mongoengine/queryset/base.py", line 402, in delete\n    queryset._collection.remove(queryset._query, write_concern=write_concern)\n', '  File "/usr/local/lib/python2.7/site-packages/pymongo/collection.py", line 672, in remove\n    docs, False, self.uuid_subtype, client)\n', '  File "/usr/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 1132, in _send_message\n    rv = self.__check_response_to_last_error(response, command)\n', '  File "/usr/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 1050, in __check_response_to_last_error\n    helpers._check_command_response(result, self.disconnect)\n', '  File "/usr/local/lib/python2.7/site-packages/pymongo/helpers.py", line 182, in _check_command_response\n    raise OperationFailure(msg % errmsg, code, response)\n', 'OperationFailure: unrecognized write concern field: write_concern\n']
DEBUG 2017-10-19 14:26:17,194 crits.core.errors ['Traceback (most recent call last):\n', '  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 87, in get_exception_response\n    response = callback(request, **param_dict)\n', '  File "/data/crits/crits/core/errors.py", line 32, in custom_400\n    RequestContext(request))\n', '  File "/usr/local/lib/python2.7/site-packages/django/shortcuts.py", line 45, in render_to_response\n    using=using)\n', '  File "/usr/local/lib/python2.7/site-packages/django/template/loader.py", line 115, in render_to_string\n    template_name, context, context_instance, dirs, dictionary)\n', '  File "/usr/local/lib/python2.7/site-packages/django/template/engine.py", line 217, in render_to_string\n    return t.render(context_instance)\n', '  File "/usr/local/lib/python2.7/site-packages/template_profiler_panel/panels/template.py", line 32, in template_render_wrapper\n    result = Template.tp_saved_render(self, context)\n', '  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 209, in render\n    with context.bind_template(self):\n', '  File "/usr/local/lib/python2.7/contextlib.py", line 17, in __enter__\n    return self.gen.next()\n', '  File "/usr/local/lib/python2.7/site-packages/debug_toolbar/panels/templates/panel.py", line 49, in _request_context_bind_template\n    context = processor(self.request)\n', '  File "/data/crits/crits/core/views.py", line 1230, in base_context\n    if request.user.is_authenticated():\n', "AttributeError: 'WSGIRequest' object has no attribute 'user'\n"]
DEBUG 2017-10-19 14:26:17,562 crits.core.errors ['Traceback (most recent call last):\n', '  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 87, in get_exception_response\n    response = callback(request, **param_dict)\n', '  File "/data/crits/crits/core/errors.py", line 32, in custom_400\n    RequestContext(request))\n', '  File "/usr/local/lib/python2.7/site-packages/django/shortcuts.py", line 45, in render_to_response\n    using=using)\n', '  File "/usr/local/lib/python2.7/site-packages/django/template/loader.py", line 115, in render_to_string\n    template_name, context, context_instance, dirs, dictionary)\n', '  File "/usr/local/lib/python2.7/site-packages/django/template/engine.py", line 217, in render_to_string\n    return t.render(context_instance)\n', '  File "/usr/local/lib/python2.7/site-packages/template_profiler_panel/panels/template.py", line 32, in template_render_wrapper\n    result = Template.tp_saved_render(self, context)\n', '  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 209, in render\n    with context.bind_template(self):\n', '  File "/usr/local/lib/python2.7/contextlib.py", line 17, in __enter__\n    return self.gen.next()\n', '  File "/usr/local/lib/python2.7/site-packages/debug_toolbar/panels/templates/panel.py", line 49, in _request_context_bind_template\n    context = processor(self.request)\n', '  File "/data/crits/crits/core/views.py", line 1230, in base_context\n    if request.user.is_authenticated():\n', "AttributeError: 'WSGIRequest' object has no attribute 'user'\n"]
DEBUG 2017-10-19 14:26:17,929 crits.core.errors ['Traceback (most recent call last):\n', '  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 87, in get_exception_response\n    response = callback(request, **param_dict)\n', '  File "/data/crits/crits/core/errors.py", line 32, in custom_400\n    RequestContext(request))\n', '  File "/usr/local/lib/python2.7/site-packages/django/shortcuts.py", line 45, in render_to_response\n    using=using)\n', '  File "/usr/local/lib/python2.7/site-packages/django/template/loader.py", line 115, in render_to_string\n    template_name, context, context_instance, dirs, dictionary)\n', '  File "/usr/local/lib/python2.7/site-packages/django/template/engine.py", line 217, in render_to_string\n    return t.render(context_instance)\n', '  File "/usr/local/lib/python2.7/site-packages/template_profiler_panel/panels/template.py", line 32, in template_render_wrapper\n    result = Template.tp_saved_render(self, context)\n', '  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 209, in render\n    with context.bind_template(self):\n', '  File "/usr/local/lib/python2.7/contextlib.py", line 17, in __enter__\n    return self.gen.next()\n', '  File "/usr/local/lib/python2.7/site-packages/debug_toolbar/panels/templates/panel.py", line 49, in _request_context_bind_template\n    context = processor(self.request)\n', '  File "/data/crits/crits/core/views.py", line 1230, in base_context\n    if request.user.is_authenticated():\n', "AttributeError: 'WSGIRequest' object has no attribute 'user'\n"]
DEBUG 2017-10-19 14:26:18,306 crits.core.errors ['Traceback (most recent call last):\n', '  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 87, in get_exception_response\n    response = callback(request, **param_dict)\n', '  File "/data/crits/crits/core/errors.py", line 32, in custom_400\n    RequestContext(request))\n', '  File "/usr/local/lib/python2.7/site-packages/django/shortcuts.py", line 45, in render_to_response\n    using=using)\n', '  File "/usr/local/lib/python2.7/site-packages/django/template/loader.py", line 115, in render_to_string\n    template_name, context, context_instance, dirs, dictionary)\n', '  File "/usr/local/lib/python2.7/site-packages/django/template/engine.py", line 217, in render_to_string\n    return t.render(context_instance)\n', '  File "/usr/local/lib/python2.7/site-packages/template_profiler_panel/panels/template.py", line 32, in template_render_wrapper\n    result = Template.tp_saved_render(self, context)\n', '  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 209, in render\n    with context.bind_template(self):\n', '  File "/usr/local/lib/python2.7/contextlib.py", line 17, in __enter__\n    return self.gen.next()\n', '  File "/usr/local/lib/python2.7/site-packages/debug_toolbar/panels/templates/panel.py", line 49, in _request_context_bind_template\n    context = processor(self.request)\n', '  File "/data/crits/crits/core/views.py", line 1230, in base_context\n    if request.user.is_authenticated():\n', "AttributeError: 'WSGIRequest' object has no attribute 'user'\n"]
DEBUG 2017-10-19 14:26:18,676 crits.core.errors ['Traceback (most recent call last):\n', '  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 87, in get_exception_response\n    response = callback(request, **param_dict)\n', '  File "/data/crits/crits/core/errors.py", line 32, in custom_400\n    RequestContext(request))\n', '  File "/usr/local/lib/python2.7/site-packages/django/shortcuts.py", line 45, in render_to_response\n    using=using)\n', '  File "/usr/local/lib/python2.7/site-packages/django/template/loader.py", line 115, in render_to_string\n    template_name, context, context_instance, dirs, dictionary)\n', '  File "/usr/local/lib/python2.7/site-packages/django/template/engine.py", line 217, in render_to_string\n    return t.render(context_instance)\n', '  File "/usr/local/lib/python2.7/site-packages/template_profiler_panel/panels/template.py", line 32, in template_render_wrapper\n    result = Template.tp_saved_render(self, context)\n', '  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 209, in render\n    with context.bind_template(self):\n', '  File "/usr/local/lib/python2.7/contextlib.py", line 17, in __enter__\n    return self.gen.next()\n', '  File "/usr/local/lib/python2.7/site-packages/debug_toolbar/panels/templates/panel.py", line 49, in _request_context_bind_template\n    context = processor(self.request)\n', '  File "/data/crits/crits/core/views.py", line 1230, in base_context\n    if request.user.is_authenticated():\n', "AttributeError: 'WSGIRequest' object has no attribute 'user'\n"]
DEBUG 2017-10-19 14:26:19,058 crits.core.errors ['Traceback (most recent call last):\n', '  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 87, in get_exception_response\n    response = callback(request, **param_dict)\n', '  File "/data/crits/crits/core/errors.py", line 32, in custom_400\n    RequestContext(request))\n', '  File "/usr/local/lib/python2.7/site-packages/django/shortcuts.py", line 45, in render_to_response\n    using=using)\n', '  File "/usr/local/lib/python2.7/site-packages/django/template/loader.py", line 115, in render_to_string\n    template_name, context, context_instance, dirs, dictionary)\n', '  File "/usr/local/lib/python2.7/site-packages/django/template/engine.py", line 217, in render_to_string\n    return t.render(context_instance)\n', '  File "/usr/local/lib/python2.7/site-packages/template_profiler_panel/panels/template.py", line 32, in template_render_wrapper\n    result = Template.tp_saved_render(self, context)\n', '  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 209, in render\n    with context.bind_template(self):\n', '  File "/usr/local/lib/python2.7/contextlib.py", line 17, in __enter__\n    return self.gen.next()\n', '  File "/usr/local/lib/python2.7/site-packages/debug_toolbar/panels/templates/panel.py", line 49, in _request_context_bind_template\n    context = processor(self.request)\n', '  File "/data/crits/crits/core/views.py", line 1230, in base_context\n    if request.user.is_authenticated():\n', "AttributeError: 'WSGIRequest' object has no attribute 'user'\n"]
DEBUG 2017-10-19 14:26:19,433 crits.core.errors ['Traceback (most recent call last):\n', '  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 87, in get_exception_response\n    response = callback(request, **param_dict)\n', '  File "/data/crits/crits/core/errors.py", line 32, in custom_400\n    RequestContext(request))\n', '  File "/usr/local/lib/python2.7/site-packages/django/shortcuts.py", line 45, in render_to_response\n    using=using)\n', '  File "/usr/local/lib/python2.7/site-packages/django/template/loader.py", line 115, in render_to_string\n    template_name, context, context_instance, dirs, dictionary)\n', '  File "/usr/local/lib/python2.7/site-packages/django/template/engine.py", line 217, in render_to_string\n    return t.render(context_instance)\n', '  File "/usr/local/lib/python2.7/site-packages/template_profiler_panel/panels/template.py", line 32, in template_render_wrapper\n    result = Template.tp_saved_render(self, context)\n', '  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 209, in render\n    with context.bind_template(self):\n', '  File "/usr/local/lib/python2.7/contextlib.py", line 17, in __enter__\n    return self.gen.next()\n', '  File "/usr/local/lib/python2.7/site-packages/debug_toolbar/panels/templates/panel.py", line 49, in _request_context_bind_template\n    context = processor(self.request)\n', '  File "/data/crits/crits/core/views.py", line 1230, in base_context\n    if request.user.is_authenticated():\n', "AttributeError: 'WSGIRequest' object has no attribute 'user'\n"]

Please let me know if you need any other logs.  This one seemed the most "interesting"
Eric

**Comment by ericwentz** [comment]
Okay, sorry about the long prior post - I did some further digging and found this:
1) Nothing of significance in the httpd logs.
2) Nothing of significance in the mongodb.log
3) the crits.log had this:
DEBUG 2017-10-20 08:10:30,567 crits.core.errors ['Traceback (most recent call last):\n',
 '  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n',
 '  File "/data/crits/crits/core/views.py", line 462, in login\n    totp_pass=totp_pass)\n',
 '  File "/data/crits/crits/core/handlers.py", line 3653, in login_user\n    user_login(request, user)\n',
 '  File "/data/crits/crits/core/handlers.py", line 3527, in user_login\n    request.session.cycle_key()\n',
 '  File "/usr/local/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 287, in cycle_key\n    self.delete(key)\n',
 '  File "/usr/local/lib/python2.7/site-packages/mongoengine/django/sessions.py", line 112, in delete\n    MongoSession.objects(session_key=session_key).delete()\n',
 '  File "/usr/local/lib/python2.7/site-packages/mongoengine/queryset/base.py", line 402, in delete\n    queryset._collection.remove(queryset._query, write_concern=write_concern)\n',
 '  File "/usr/local/lib/python2.7/site-packages/pymongo/collection.py", line 672, in remove\n    docs, False, self.uuid_subtype, client)\n',
 '  File "/usr/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 1132, in _send_message\n    rv = self.__check_response_to_last_error(response, command)\n',
 '  File "/usr/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 1050, in __check_response_to_last_error\n    helpers._check_command_response(result, self.disconnect)\n',
 '  File "/usr/local/lib/python2.7/site-packages/pymongo/helpers.py", line 182, in _check_command_response\n    raise OperationFailure(msg % errmsg, code, response)\n',
	 'OperationFailure: unrecognized write concern field: write_concern\n']

I'm running mongo server 3.4.3.  Here's a list of the versions of all my python modules;
amqp (2.1.4)
anyjson (0.3.3)
appdirs (1.4.3)
billiard (3.5.0.2)
biplist (1.0.1)
celery (4.0.2)
chardet (3.0.4)
CRITsAPI (1.4.3)
CrowdStrike (0.6.1)
cssselect (1.0.1)
cybox (2.1.0.13)
Cython (0.25.2)
dateutils (0.6.6)
defusedxml (0.5.0)
Django (1.8.18)
django-celery (3.2.1)
django-debug-toolbar (1.7)
django-debug-toolbar-mongo (0.1.10)
django-debug-toolbar-template-profiler (1.0.1)
django-debug-toolbar-template-timings (0.7)
django-debug-toolbar-vcs-info (1.2.0)
django-mongoengine (0.2.1)
django-tastypie (0.13.3)
django-tastypie-mongoengine (0.4.7)
enum34 (1.1.6)
future (0.16.0)
hxapi (1.1.6)
ipaddress (1.0.18)
isodate (0.5.4)
kombu (4.0.2)
libtaxii (1.1.109)
lxml (3.7.0)
M2Crypto (0.26.0)
mixbox (1.0.1)
mod-wsgi (4.5.15)
mongoengine (0.8.8)
olefile (0.44)
ordered-set (2.0.1)
ordereddict (1.1)
packaging (16.8)
pefile (2016.3.28)
Pillow (4.1.0)
pip (9.0.1)
pycrypto (2.6.1)
pydeep (0.2)
pyimpfuzzy (0.2)
pymongo (2.8.1)
pyparsing (2.2.0)
python-dateutil (2.6.0)
python-ldap (2.4.32)
python-magic (0.4.6)
python-mimeparse (1.6.0)
pytz (2017.2)
PyYAML (3.12)
qrcode (5.3)
requests (2.13.0)
setuptools (34.4.1)
simplejson (3.10.0)
six (1.10.0)
sqlparse (0.2.3)
stix (1.2.0.3)
stix-ramrod (1.1.0)
stix-validator (2.4.0)
threatconnect (2.4.17)
typing (3.6.1)
ushlex (0.99)
vine (1.1.3)
weakrefmethod (1.0.3)
wheel (0.29.0)
xlrd (1.0.0)

Please let me know if there is any additional information that I can provide.

Thanks
Eric
