### ISSUE TITLE
API error retrieving list of campaigns

### ISSUE THREAD

**Issue by ericwentz** [crits/crits#948]
Hello,
I have discovered what I believe to be an error in the API code used to retrieve the list of campaigns.  when I get the url: https://crits-instance/api/v1/campaigns?username=user&api_key=[redacted] I receive the following response: 
{
    "error_message": "Sorry, this request could not be processed. Please try again later."
}

I have tested the query with all the other TLOs which all returned the expected results.

Thanks
Eric

**Comment by ericwentz** [comment]
Any thoughts on this issue yet?

**Comment by brlogan** [comment]
What version of the code are you running?

**Comment by ericwentz** [comment]
The current PR.
