### ISSUE TITLE
Problem uploading files

### ISSUE THREAD

**Issue by jaegeral** [crits/crits#95]
I have set up crits on a fresh system:
Linux crits 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Added an admin and an normal user, added a source and added the source to the user.

When trying to upload a file (e-mail, binary, doesn't matter)

I am receiving GUI error: Error uploading file.

Console shows only:
[05/Jun/2014 08:55:43] "POST /emails/new/eml/ HTTP/1.1" 500 344305

Any suggestions how to proceed?

Thanks

**Comment by ckane** [comment]
On FreeBSD 10-stable, the following solved my problem:
```sudo pip install python-magic```
