### ISSUE TITLE
MongoDB

### ISSUE THREAD

**Issue by jimbolya0607** [crits/crits#965]
Last night went to install CRITS.  The install failed at the MongoDB, which is probably on me.  However, the architecture I'm using places all DBs off the server and onto a dedicated DB server. 

My question: where does the config file reside that allows me to point CRITS at a different MongoDB?

Jimbo

**Comment by apolkosnik** [comment]
Take a look at https://github.com/crits/crits/blob/master/crits/config/database_example.py

**Comment by jimbolya0607** [comment]
Ahh - so it's in database.py
cool - thanks!
